### DISCUSSION TITLE
using NETWORK isn't replace current network

### DISCUSSION THREAD

**Discussion by david-nano** [firecow/gitlab-ci-local#1126] [General]
The current usage, blocking me from building dockerfile (not sure what is the default network here), I've tried to add `NETWORK="host"` into file `.gitlab-ci-local-env`, but got an error:
```
Error: Command failed with exit code 125: ... --network gitlab-ci-local-319512 --network-alias=build --network host ...
```

what I'm doing wrong? 
I think the issue is here: 
https://github.com/firecow/gitlab-ci-local/blob/2053145749c5d1dd850ec55d8672bca8875dd50a/src/job.ts#L648:L655
if network provided by user, it's need to be ignored from the network provided by the tool.

**Comment by firecow** [comment]
Provide more information please. 

What's in your .gitlab-ci.yml, whats in your .gitlab-ci-local-env, what exact command did you run.
Paste the entire error.

**Reply by david-nano** [reply]
It's not a specific job, it can be a lot of jobs, for example:
```
image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
```
On my case `$CI_REGISTRY` is local one, and I can't do docker build in local CI since the network created during the job isn't know how to reach the address of `$CI_REGISTRY` , so I wanted to use `docker build --network=host` but assume I'm adding into `.gitlab-ci-local-env` the variable `NETWORK=host` I'm getting the error above.
