### DISCUSSION TITLE
How to pass variables from shell env?

### DISCUSSION THREAD

**Discussion by avoidik** [firecow/gitlab-ci-local#1347] [Q&A] [answered]
Hello,

Let's imagine I have an environment variable, which was created before I run `gitlab-ci-local` (for instance, exported via bash profile or direnv), something like:

```bash
export MY_SENSITIVE_VARIABLE='5uper5ecret'
```

I was trying to naively define it in the `variables.yaml` file as follows:

```yaml
---
global:
  MY_SENSITIVE_VARIABLE: "$MY_SENSITIVE_VARIABLE"
  MY_OTHER_VARIABLE: "$MY_SENSITIVE_VARIABLE"
```

However both of these variables have appeared empty.

I would like to understand what options `gitlab-ci-local` has to be able to pass this variable into the execution context? without redefining it over and over in the `variables.yaml` files

cheers

**Comment by firecow** [comment, marked as answer]
You have to pass it like so `gitlab-ci-local --variable MY_SENSITIVE_VARIABLE=${MY_SENSITIVE_VARIABLE}`

You could add a feature request under issue, that suggests a syntax in gitlab-ci-local variable.yml's that makes them able to auto-fetch values from the terminal env.

```yml
---
global:
  MY_SENSITIVE_VARIABLE: "{{ fromTerminalEnv('MY_SENSITIVE_VARIABLE') }} "
```

Or something like that :smile:
