### DISCUSSION TITLE
Support for tags

### DISCUSSION THREAD

**Discussion by bjornpiltz** [firecow/gitlab-ci-local#1403] [Q&A]
I am feeling like I am missing something really simple here. How do I run just the jobs in my pipeline which are tagged "docker"?

**Comment by firecow** [comment]
Paste and as simple as possible `.gitlab-ci.yml`, and what command your are running.

That way we have a chance to understand, what you are talking about :D

**Comment by bjornpiltz** [comment]
Sorry, I was thinking of something like this. Now `gitlab-ci-local` chokes on the msvc job. I would like to just skip it.

```yaml
stages:
  - build

build:msvc:
  stage: build
  tags:
    - msvc
  script:
    - echo "Running on Windows machine."
    - cmake.exe ... 

build:gcc:
  image: alpine:latest
  stage: build
  tags:
    -  docker
  script:
    - echo "Running on Linux in a docker image."
```
