### DISCUSSION TITLE
Running CI jobs as different user other than root.

### DISCUSSION THREAD

**Discussion by rbitnode** [firecow/gitlab-ci-local#1455] [Q&A]
Hi,

When I am running CI jobs using this tool, how do i configure to run jobs as different user. for example, below is my job:

my_new_job:
  stage: code_check
  image: ubuntu:latest
  script:
    - su - ubuntu
    - echo `whoami`
  needs: []

Above job prints 'root' despite of switch user command.

**Comment by firecow** [comment]
This is a question for the Gitlab CI/CD forum.

Unless you can prove that this example works as you expect on gitlab.com.

Plus you example is pretty broken... `echo whoami` ?

```
---
my_new_job:
  stage: test
  image: ubuntu:latest
  script:
    - su - ubuntu
    - whoami
  needs: []
```
This is probably what you mean


Here's what it looks like on gitlab.com, and it is exactly the same behavior exhibited by gitlab-ci-local
https://gitlab.com/firecow/gitlab-ci-debugging/-/commit/bab76b2b96c80ee7bd790fb9b82037e7de527456
https://gitlab.com/firecow/gitlab-ci-debugging/-/jobs/8632009890

**Comment by firecow** [comment]
You could use the `docker.user` instruction provided by Gitlab CI/CD mentioned here https://forum.gitlab.com/t/gitlab-ci-yaml-use-image-with-a-specific-user/72854/4

```
---
my_new_job:
  stage: test
  image:
    name: ubuntu:latest
    docker:
      user: ubuntu
  script:
    - whoami
  needs: []
```
