### DISCUSSION TITLE
how do I override/disable the cache when running a specific task?

### DISCUSSION THREAD

**Discussion by Aditeya** [firecow/gitlab-ci-local#1475] [Q&A]
```yml
check:linux:nextest:
  extends: .check:linux
  cache:
    - key: nextest
      paths: [ target/ ]
    - key: cargo
      paths: [ .cargo/ ]
  script:
    - cargo nextest run --workspace --profile ci --config-file .config/nextest.toml
  artifacts:
    when: always
    reports:
      junit: target/nextest/ci/junit.xml
```

I want to ignore the cache and artifacts when running the job. Is there a way to do this? (or atleast is there a way to delete the cache?)
