### DISCUSSION TITLE
How do I find the cause of a failure?

### DISCUSSION THREAD

**Discussion by pschmitz-anwb-nl** [firecow/gitlab-ci-local#943] [Q&A]
I'm trying to use gitlab-ci-local to test my `.gitlab-ci.yml` file, but it fails without giving any further details. How can I find out what exactly is going wrong? I did look at the --help info, but it did not appear to give any way to enable debug logging or something like that.

This is on Windows 10. I installed gitlab-ci-local by running `npm install -g gitlab-ci-local`, which gave no errors. I know it can find and parse the `.gitlab-ci.yml` file, because the --list and --preview commands work. Here is the complete output it gives when I try to build the project using the command `gitlab-ci-local assembleRelease`:

```Using fallback linux user id
parsing and downloads finished in 328 ms
assembleRelease starting 319504836072.dkr.ecr.eu-central-1.amazonaws.com/gradle:7-jdk11 (build)

 FAIL  assembleRelease
```

It just says FAIL without providing any detail about what failed or why. There is a `.\.gitlab-ci-local\builds` directory that appears to contain a correct copy of the source code, and a `.\.gitlab-ci-local\output\assembleRelease.log` file which is empty.

How can I find out more about what exactly went wrong and what the cause was?

**Comment by firecow** [comment]
A great way to get help, is to paste a stripped down version of your `.gitlab-ci.yml`

Tell us what version of `gitlab-ci-local` you are using.

**Reply by pschmitz-anwb-nl** [reply]
`gitlab-ci-local --version` says that it is version 4.42.0.

**Reply by pschmitz-anwb-nl** [reply]
I intentionally didn't post the `.gitlab-ci.yml` file since I figured I should be able to find out what's wrong myself, given enough information from gitlab-ci-local. I was just after a way to make it give more information than "FAIL". But since you ask, here it is:
```
stages:
  - build

variables:
  ECR_PROD: "[REDACTED]"

.gradle:
  image: $ECR_PROD/gradle:7-jdk11
  tags:
    - hv-tools-build-heavy-prod
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    key: $CI_COMMIT_REF_SLUG #optional: per branch caching, can be omitted
    paths:
      - .gradle/wrapper
      - .gradle/caches
      - '**/build/classes'
      - '**/build/tmp'

assembleRelease:
  extends: .gradle
  stage: build
  when:
    manual
  interruptible: true
  script:
    # grep regex for version=1.2.3.4 and then use 'cut' to return only the string after the =, prepend with 'v'
    - RELEASE=$(grep -Po 'version=.+' gradle.properties | cut -d"=" -f2 | (echo -n v && cat))
    - echo $RELEASE
    - gradle --stacktrace --build-cache --no-daemon clean war dist docs dar deploy
    - echo "ASSEMBLE_JOB_ID=${CI_JOB_ID}" > release.env
    - echo "RELEASE=${RELEASE}" >> release.env
    - cat release.env
  artifacts:
    paths:
      - build/libs/
      - build/docs/
    expire_in: 1 months
    reports:
      dotenv: release.env
```
