### ISSUE TITLE
include does not respect variable in rules

### ISSUE THREAD

**Issue by netaskd** [firecow/gitlab-ci-local#1011]
**Minimal .gitlab-ci.yml illustrating the issue**
set group/project variable

``` 
# ~/.gitlab-ci-local/variables.yml
group:
  gitlab..example.com/group/:    
    ENABLED_REWRITE: false
# or/and
project:
  gitlab.example.com/group/project.git:    
    ENABLED_REWRITE: false
```
set scripts/.job.yml
```
.job:
  script: echo job
```

set scripts/.rewrite_job.yml
```
.job:
  script: echo rewrite_job
```

set .gitlab-ci.yml
```yml
---
include:
  - local: '/scripts/.job.yml'
  - local: '/scripts/.rewrite_job.yml'
    rules:
      - if: $ENABLED_REWRITE == 'true'

some_job:
  extends:
    - .job

```
instead of content from .job.yml we got content from .rewrite_job.yml

**Expected behavior**
content from .job.yml and echo output "job"

**Host information**
Ubuntu
gitlab-ci-local 4.45.0

**Containerd binary**
docker

**Additional context**
doc is here https://docs.gitlab.com/ee/ci/yaml/includes.html#use-variables-with-include

**Comment by firecow** [comment]
Can't find a dublicate, marking this as a missing feature

**Comment by ANGkeith** [comment]
am i missing out something ? 

i can't replicate the issue

![image](https://github.com/user-attachments/assets/e06c0d99-e5d1-47d8-8548-9ae32168add6)

**Comment by ANGkeith** [comment]
To replicate the issue you'll need 2 projects:

## Project: `gitlab-ci-local-test-2`

**.gitlab-ci.yml**
```yaml
include:
  - local: one.gitlab-ci.yml
    rules:
      - if: '$INCLUDE_LOCAL == "one"'
  - local: two.gitlab-ci.yml
    rules:
      - if: '$INCLUDE_LOCAL == "two"'
```

**one.gitlab-ci.yml**
```yaml
one:
  script:
    - echo "One"
```

**two.gitlab-ci.yml**
```yaml
two:
  script:
    - echo "Two"
```

## Project: `gitlab-ci-local-test`

**.gitlab-ci.yml**
```yaml
include:
  - project: '{user/group}/gitlab-ci-local-test-2'
    ref: main
    file: .gitlab-ci.yml
```

## Variables

Even with `INCLUDE_LOCAL` not set in `~/.gitlab-ci-local/variables.yaml`, both jobs `one` and `two` run when they shouldn't. Setting `INCLUDE_LOCAL` to `one`, `two` or any other value has no impact.

_Originally posted by @ke-lit in https://github.com/firecow/gitlab-ci-local/issues/1406#issuecomment-2457241759_
