### ISSUE TITLE
exitCode is always zero when using node v20

### ISSUE THREAD

**Issue by atli-c** [firecow/gitlab-ci-local#1012]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
failing_job:
  script: ['false']
  allow_failure: false
```
`gitlab-ci-local failing_job; echo $?`

**Expected behavior**
`echo $?` should reveal that `gitlab-ci-local` exits with non-zero, but it show `0` as if the job succeeded.

**Host information**
macOS Sonoma 14.0, Intel CPU.
gitlab-ci-local 4.45.0, node v20.8.1.

**Containerd binary**
n/a -- Install with `npm -g install ...`

**Additional context**
I can _not_ replicate problem when running with node v18.18.2.
