### ISSUE TITLE
Add hosts to containers

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#103]
# Love 

Thank you very much for this great tool, that will help me a lot with a few more features 🥰

# Request

## Description

I have some DNS entries in my ubuntu's `/etc/hosts`, and the containers does not pick anything from there.

Would be nice to be able to pass parameters to every containers, in this case `--add-host`

## Symptom

`unknown host`

# Workaround

## Description

Add some lines in before_script/script :

`echo "10.x.y.z nexus.my-company.com" >> /etc/hosts`

## Impact

-  low : needs actions once before/after a debugging session
- medium : fixed using another top level .gitlab-ci.yml
- ✅ high : needs deep refactoring, everywhere in templates or everytime or both

**Comment by firecow** [comment]
Can you specify an "as small as possible" .gitlab-ci.yml for this use case ? @bcouetil

**Comment by bcouetil** [comment]
@firecow this should work with the option `--add-host fake-google.com:216.58.213.163` to `docker run`
For now I have to add the commented line.

```
job:
  image: curlimages/curl:7.69.1
  script:
    # - echo "216.58.213.163 fake-google.com" >> /etc/hosts
    - curl http://fake-google.com
```
