### ISSUE TITLE
gitlab-ci-local sometimes update original sources file when artifacts requested

### ISSUE THREAD

**Issue by airone-x1** [firecow/gitlab-ci-local#1034]
I use marmail-cli in my CI.
When using gitlab-ci-local :+1: 

* original sources files are updated while mermaid-cli run contenairized
* permissions on source directory are also updated 

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
marmaid_svg:
  image:
    name: docker.io/minlag/mermaid-cli
    entrypoint: [""]
  script:
    - MMDC="/home/mermaidcli/node_modules/.bin/mmdc -p /puppeteer-config.json"
    - $MMDC -i docs/index.md -o docs/index2.md
  artifacts:
   paths:
      - docs/
   expire_in: "30 mins"
```

**Expected behavior**
updated artifacts in .gitlab-ci-local not in original sources

**Host information**
Ubuntu
gitlab-ci-local 4.45.1

**Containerd binary**
Docker

**Additional context**

Sample project https://github.com/airone-x1/gcl-mermaidcli

After running gitlab-ci-local

* docs/ source directory become mod 777
* docs/ contains  mermaid-cli output (svg, transformed md).

* If i remove artifact statement my sources are not updated.

I expect gitlab-ci-local writing only in its own .gitlab-ci-local directory, not in my project files.

**Comment by firecow** [comment]
This must be a bug.

gitlab-ci-local is not supposed to change project specific file permissions.

**Comment by drAlberT** [comment]
I have the same problem with the artifact from a docker build.

Doing `docker save $IMAGE | gzip -c > artifact.tgz` creates the file in the project root, but I can't find a way to remove it after the artifact has been uploaded.

Tried to use `$CI_BUILDS_DIR` hoping to operate inside `.gitlab-ci-local/build/` dir but no luck.

**Comment by firecow** [comment]
```
---
test-job:
  image:
    name: alpine
  script:
    - echo "hello" > test.txt
    - chmod 777 test.txt
    - chown 0:0 text.txt
  artifacts:
    paths:
      - test.txt
```

Because of https://github.com/firecow/gitlab-ci-local#the-noartifactstosource-decorator the `test.txt` is copied to the host folder with 777 file permissions, but not with 0:0 ownership, which is expected.

Can you try to simplify your example, so it's easier for me to reproduce?
