### ISSUE TITLE
Using --umask false causes permission errors on /gcl-builds

### ISSUE THREAD

**Issue by hatvik** [firecow/gitlab-ci-local#1036]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - ls -l cmake/all_deps.cmake
    # Or
    - ci/my_script.sh
```
**Examples of failures**
`longevity                       > /gcl-cmd: line 40: ci/start_etcd.sh: Permission denied`

`longevity                       > ls: cannot access 'cmake/all_dependencies.cmake': Permission denied`

**Expected behavior**
You should be able to access files or execute scripts

**Containerd binary**
docker

**Additional context**
The problem is that the permissions on /gcl-builds are set to 0:0 and a+rw. And I am trying to run as a our image default, non-root ci user.

`drwxrwxrw-  2 root root  4096 Nov 14 15:14 cmake`

This means I cant list stuff in that directory, nor execute any files
