### ISSUE TITLE
extends: job ancestor depth limited to 1 except first extend in list

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#105]
# Love 

Thank you very much for this great tool, that will help me a lot with a few more features 🥰

# Request

## Description

When a job extends multiple templates/job, only the first one's parents are taken into account.

Here, `.level-2` is ignored.

```
.root:
  interruptible: true

.level-2:
  script:
    - echo "level 2 ancestor is called"

.level-1:
  extends: .level-2
  before_script:
    - echo "level 1 ancestor is called"

job:
  extends:
    - .root
    - .level-1
  image: maven:3.6.3-jdk-11
```
swapping `.root` and `.level-1` in `job:extends:` would work.

## Symptom

`extends:` of jobs/templates within `extends:` of current job are ignored, except for ancestors of first entry in list.

# Workaround

## Description

extends all in the top level job in the right order

```
my-test-job:
  extends:
    - .root
    - .maven
    - .maven-test
```

## Impact

- low : needs actions once before/after a debugging session
- ✅ medium : fixed using another top level .gitlab-ci.yml
- high : needs deep refactoring, everywhere in templates or everytime or both
