### ISSUE TITLE
Reference is undefined

### ISSUE THREAD

**Issue by earthiverse** [firecow/gitlab-ci-local#1054]
I get the error `!reference [.sh_functions, wait_for] is undefined` when running `gitlab-ci-local`.
It works fine in the normal GitLab CI.

**Minimal .gitlab-ci.yml illustrating the issue**

`.gitlab-ci.yml`
```yml
include:
  - project: ci-help
    file:
      - /functions/sh_functions.yml

test:minimal:
  image: php:8.2-alpine
  script:
    - !reference [ ".sh_functions", "wait_for" ]
```

`/functions/sh_functions.yml`
```yml
.sh_functions:
  version:
    # Useful for testing version compatibility (e.g. 2.0.0 > 1.9.9)
    # From https://stackoverflow.com/a/37939589
    - function version { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }
  wait_for:
    # Repeats the specified command until it successfully returns, or times out
    #
    # Example (Waiting for Elasticsearch to be available):
    #  `wait_for curl -s elasticsearch:9200`
    - >
      function wait_for {
        local X=1
        until "${@}"; do
          if [ "${X}" -gt 60 ]; then
            echo "The command did not complete within 60 seconds"
            return 1
          fi
          
          X=$((X + 3))
          sleep 3
        done
      }
```

**Expected behavior**
No errors

**Host information**
macOS Sonoma 14.1.2 (Apple Silicon M1 Pro)
gitlab-ci-local 4.45.2
