### ISSUE TITLE
Job with rules:exists referring to an existing file with a filename defined in a variable does not run

### ISSUE THREAD

**Issue by jspiers** [firecow/gitlab-ci-local#1059]
**.gitlab-ci.yml illustrating the issue**:
```yml
variables:
  MY_FILE: example.txt

stages:
  - build

this runs:
  stage: build
  script:
    - echo $CI_JOB_NAME

this does not:
  extends: this runs
  rules:
    - exists:
       - $MY_FILE
```
**example.txt**:
```
blablabla
```

**Expected behavior**
Both jobs should run as they do on GitLab (see [this](https://gitlab.com/jspiers/gitlab-ci-local-example/-/pipelines/1101411803) pipeline)

**Host information**
Ubuntu 22.04
```
$ gitlab-ci-local --version
4.45.2
$ docker --version
Docker version 24.0.7, build afdd53b 
```
