### ISSUE TITLE
Define inputs for configuration added with include

### ISSUE THREAD

**Issue by bataliero** [firecow/gitlab-ci-local#1072]
**Is your feature request related to a problem? Please describe.**

I would like to be able to use `spec:inputs` for my reusable pipelines imported with `include` in the projects.

I have tried to run an example from GitLab [documentation](https://docs.gitlab.com/ee/ci/yaml/inputs.html)

```
spec:
  inputs:
    job-stage:
    environment:
---
scan-website:
  stage: $[[ inputs.job-stage ]]
  script: echo $[[ inputs.environment ]]
```
and 
```
include:
  - local: "../<path>/main.yaml"
    inputs:
      job-stage: "example1"
      environment: "staging"
```

However `gitlab-ci-local` shows me this:

```
YAMLException: expected a single document in the stream, but found more
    at Object.load (/snapshot/firecow-gitlab-ci-local/node_modules/js-yaml/lib/loader.js:1722:9)
    at Function.loadYaml (/snapshot/firecow-gitlab-ci-local/src/parser.ts:244:21)
    at Function.init (/snapshot/firecow-gitlab-ci-local/src/parser-includes.ts:74:37)
    at Parser.init (/snapshot/firecow-gitlab-ci-local/src/parser.ts:83:44)
    at Function.create (/snapshot/firecow-gitlab-ci-local/src/parser.ts:54:9)
    at handler (/snapshot/firecow-gitlab-ci-local/src/handler.ts:96:18)
    at Object.handler (/snapshot/firecow-gitlab-ci-local/src/index.ts:36:21)
```

**Describe the solution you'd like**
I would like to have `spec:inputs` implemented.

Thanks!
