### ISSUE TITLE
includes not working

### ISSUE THREAD

**Issue by WladyX** [firecow/gitlab-ci-local#1080]
```
bat .gitlab-ci.yml
include:
  - project: "wxs/pipelines"
    ref: main
    file: "packer.yml"

variables:
  PACKER_VER: "latest"
  PACKER_ROOT: ${CI_PROJECT_DIR}/debian12
  PACKER_RG: packer_build_debian12-cube
  PKR_VAR_vm_id: "900"
  PKR_VAR_proxmox_node: "cube"
```

```
gitlab-ci-local --fetch-includes
parsing and downloads finished in 98 ms
```

no errror reported but the folders are empty:
```
tree .gitlab-ci-local
.gitlab-ci-local
└── includes
    └── gitlab.mydomain.com
        └── wxs
            └── pipelines
                └── main

6 directories, 0 files
```

my remote is:
```
git remote -v
origin	git@gitlab.mydomain.com:wxs/sched/packerox.git (fetch)
origin	git@gitlab.mydomain.com:wxs/sched/packerox.git (push)
```

```
gitlab-ci-local --list
parsing and downloads finished in 92 ms
jobNamePad is uninitialized
```
i guess this is expected because the include is not downloaded.

any ideeas on what i am doing wrong or what i could try?
thank you
