### ISSUE TITLE
includes not working as expected with custom ssh port

### ISSUE THREAD

**Issue by WladyX** [firecow/gitlab-ci-local#1081]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
include:
  - project: "wxs/pipelines"
    ref: main
    file: "packer.yml"

variables:
  PACKER_VER: "latest"
  PACKER_ROOT: ${CI_PROJECT_DIR}/debian12
  PACKER_RG: packer_build_debian12-cube
  PKR_VAR_vm_id: "900"
  PKR_VAR_proxmox_node: "cube"
```

**Expected behavior**
i would expect the list of jobs

**Host information**
MacOS 14.2
gitlab-ci-local 4.46.0

**Containerd binary**
OrbStack

**Additional context**

```
gitlab-ci-local --fetch-includes
parsing and downloads finished in 98 ms
```

no errror reported but the folders are empty:
```
tree .gitlab-ci-local
.gitlab-ci-local
└── includes
    └── gitlab.mydomain.com
        └── wxs
            └── pipelines
                └── main

6 directories, 0 files
```

my remote is:
```
git remote -v
origin	git@gitlab.mydomain.com:wxs/sched/packerox.git (fetch)
origin	git@gitlab.mydomain.com:wxs/sched/packerox.git (push)
```

```
gitlab-ci-local --list
parsing and downloads finished in 92 ms
jobNamePad is uninitialized
```
i guess this is expected because the include is not downloaded.

any ideeas on what i am doing wrong or what i could try?
thank you

**Comment by WladyX** [comment]
```
cat packer.yml
include:
  - helper/runonly.yml
  - helper/tags_cc.yml
  - helper/notifier.yml
  - helper/cleanup_jobs.yml
  - helper/stages.yml

  - packer/vars.yml
  - packer/validate.yml
  - packer/build.yml
```

is there any verbose/debug flag i could use to get more logs?
thank you for your support!

**Comment by WladyX** [comment]
I've replaced the above suspecting maybe there is an issue with include with the following:
```
cat packer.yml
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
```
pushed to the pipelines repo, did not make any difference.
