### ISSUE TITLE
Variable with null value is not supported

### ISSUE THREAD

**Issue by ANGkeith** [firecow/gitlab-ci-local#1095]
```yml
---
job:
  variables:
    FOO:
  script:
    - echo "$FOO"
```

```yml
---
variables:
  FOO:
job:
  script:
    - echo "$FOO"
```
**Expected behavior**
Pipeline should run
