### ISSUE TITLE
Incorrect nested variable expansion

### ISSUE THREAD

**Issue by ANGkeith** [firecow/gitlab-ci-local#1097]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
variables:
  DEV_URL: dev-url
  URL_DEV: url-dev

.script:
  script:
    - echo $URL

test ${URL_${ENV}}:
  extends: .script
  variables:
    URL: ${URL_${ENV}}
    ENV: DEV

test ${${ENV}_URL}:
  extends: .script
  variables:
    URL: ${${ENV}_URL}
    ENV: DEV
```

**Expected behavior**
https://gitlab.com/ANGkeith/gitlab-ci-local-test/-/commit/34b50e3b66690dd23ba63454cefcd2e54700c642

**Current behavior**
![image](https://github.com/firecow/gitlab-ci-local/assets/28011783/f7ec67b3-99fd-4a21-b908-336d8d39cf91)
