### ISSUE TITLE
$$ in ci/cd variables not working as expected 

### ISSUE THREAD

**Issue by ANGkeith** [firecow/gitlab-ci-local#1099]
[Use the $ character in CI/CD variables](https://docs.gitlab.com/ee/ci/variables/#use-the--character-in-cicd-variables)

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
$ character in CI/CD variable:
  variables:
    FLAGS: '-al'
    LS_CMD: 'ls "$FLAGS" $$TMP_DIR'
  script:
    - echo "$LS_CMD"  
```

**Expected behavior**
```
'ls -al $TMP_DIR'
```

**Current behavior**
```
'ls -al'
```
