### ISSUE TITLE
Pipeline should stop when a needed job fails, when option --needs is used

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#110]
# Love 

The more I learn and use this tool the more I love it 🥰

# Request

## Description

Pipeline should stop when a needed job fails using `--needs`.

## Symptom

```
needed:
  stage: .pre
  image: alpine
  script:
    - exit 1

needs:
  image: alpine
  needs:
    - needed
  script:
    - echo "this should not be played"
```

Both jobs play :

```
yml files processed in 39 ms
needed    starting curlimages/curl:7.69.1 (.pre)
needed    $ exit 1
needed    finished in 5.17 s exited with code 1 
needs     starting curlimages/curl:7.69.1 (test)
needs     $ echo "this should not be played"
needs     > this should not be played
needs     finished in 5.17 s

successful needs
failure needed
```

# Workaround

## Description

Ctrl+C

## Impact

- ✅ low : needs actions once before/after a debugging session
- medium : fixed using another top level .gitlab-ci.yml
- high : needs deep refactoring, everywhere in templates or everytime or both
