### ISSUE TITLE
Make `--preview` option compliant with Gitlab CI linter

### ISSUE THREAD

**Issue by e-picas** [firecow/gitlab-ci-local#1141]
### Is your feature request related to a problem? Please describe.

The actual result of the `--preview` option is not compatible with the GitLab internal `ci/lint` API route
which validates if a CI config is valid or not. As it's not the purpose of this option, I propose to add a new option doing the same job (merging the whole CI configuration) but without variable expansion. Something like the result of the "Full configuration" tool of GitLab's internal CI editor: <https://docs.gitlab.com/ee/ci/pipeline_editor/#view-full-configuration>.

### Final purpose

The final goal is to be able to validate a complete local development of CI, with all the concerned includes, sending
the result as the `ci/lint` API route `content` parameter to be able to validate a full CI local development:

```shell
jq --null-input --arg yaml "$(gitlab-ci-local --<OPTION>)" '.content=$yaml' \
| curl "https://scm.clubmed.com/api/v4/projects/${GITLAB_PROJECT_ID}/ci/lint?include_merged_yaml=true" \
  --header "Authorization: Bearer ${GITLAB_TOKEN}" \
  --header 'Content-Type: application/json' \
  --data @- \
| jq '.valid'
# should always be 'true'
```
**This could be a great feature for CI automation, like a pre-commit hook for instance.**

### Minimal `.gitlab-ci.yml` illustrating the need

I haven't tested all the combinations of all keywords but I've identify at least the following case which is failing:

```yaml
# .gitlab-ci.yml
---

.anchored_vars: &anchored_vars
  MY_VAR: 'my var'

my_job:
  rules:
    - if: $CI_COMMIT_REF_NAME
      variables:
        <<: *anchored_vars
  script:
    - echo "$MY_VAR"
  environment:
    name: $MY_VAR
```

Below is the result of the `--preview` option:

```shell
$ gitlab-ci-local --preview

---
stages:
  - .pre
  - build
  - test
  - deploy
  - .post
my_job:
  rules:
    - if: $CI_COMMIT_REF_NAME
      variables:
        MY_VAR: my var
  script:
    - echo "$MY_VAR"
  environment:
    name: ''

```

Passing this to the API will fail:

```shell
$ jq --null-input --arg yaml "$(gitlab-ci-local --preview)" '.content=$yaml' \
  | curl "https://scm.clubmed.com/api/v4/projects/${GITLAB_PROJECT_ID}/ci/lint?include_merged_yaml=true" \
    --header "Authorization: Bearer ${GITLAB_TOKEN}" \
    --header 'Content-Type: application/json' \
    --data @- \
  | jq

{
  "valid": false,
  "errors": [
    "jobs:my_job:environment name can't be blank",
    "jobs:my_job:environment name can contain only letters, digits, '-', '_', '/', '$', '{', '}', '.', and spaces, but it cannot start or end with '/'"
  ],
  "warnings": [],
  "merged_yaml": "---\nstages:\n- \".pre\"\n- build\n- test\n- deploy\n- \".post\"\nmy_job:\n  rules:\n  - if: \"$CI_COMMIT_REF_NAME\"\n    variables:\n      MY_VAR: my var\n  script:\n  - echo \"$MY_VAR\"\n  environment:\n    name: ''\n",
  "includes": []
}
```

### Expected behavior

In that particular case, the enviroment name and url should not be replaced by the variable value (which is empty as it can not be guessed outside of a tag).

In deed, if we change the payload like the following:

```yaml
# .gitlab-ci-validated.yml

---
stages:
  - .pre
  - build
  - test
  - deploy
  - .post
my_job:
  rules:
    - if: $CI_COMMIT_REF_NAME
      variables:
        MY_VAR: my var
  script:
    - echo "$MY_VAR"
  environment:
    name: '$MY_VAR'

```

We have a validated result:

```shell
$ jq --null-input --arg gitlabci "$(<.gitlab-ci-validated.yml)" '.content=$gitlabci' \
  | curl "https://scm.clubmed.com/api/v4/projects/${GITLAB_PROJECT_ID}/ci/lint?include_merged_yaml=true" \
    --header "Authorization: Bearer ${GITLAB_TOKEN}" \
    --header 'Content-Type: application/json' \
    --data @- \
  | jq


{
  "valid": true,
  "errors": [],
  "warnings": [],
  "merged_yaml": "---\nstages:\n- \".pre\"\n- build\n- test\n- deploy\n- \".post\"\nmy_job:\n  rules:\n  - if: \"$CI_COMMIT_REF_NAME\"\n    variables:\n      MY_VAR: my var\n  script:\n  - echo \"$MY_VAR\"\n  environment:\n    name: \"$MY_VAR\"\n",
  "includes": []
}
```

### Host information

* tested with gitlab-ci-local 4.46.1
