### ISSUE TITLE
Reference to reference does not work in before_script

### ISSUE THREAD

**Issue by trygve55** [firecow/gitlab-ci-local#1143]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
.snippets:
  test:
    - echo "Big bang!"

.job_b:
  content:
    - !reference [.snippets, test]

job_a:
  before_script: !reference [.job_b, content]
  script:
    - echo "Hello world!"
```

**Expected behavior**
Print "Big bang!" and "Hello world!". But instead we get `job_a before_script contains non string value`

**Host information**
Ubuntu 20.04
gitlab-ci-local 4.46.1
