### ISSUE TITLE
build directory not found

### ISSUE THREAD

**Issue by thoroc** [firecow/gitlab-ci-local#1148]
I have tried to run `gitlab-ci-local` without changes, and it seems to be failing on copying the files to the containers.

* MacOS 14.4
* Docker 25.0.3

```sh
gitlab-ci-local
parsing and downloads finished in 282 ms
dependencies          starting <aws_account_id>.dkr.ecr.eu-central-1.amazonaws.com/alpine-nodejs:18.19.0 (.pre)
dependencies          copied to docker volumes in 4.16 s
Error: ENOENT: no such file or directory, stat '/Users/thoroc/work/project//gcl-builds/package-lock.json'
```

I can see a `.gitlab-ci-local` directory that seems to be the one `gitlab-ci-local` is looking for as there is a copy of the current dir inside a `build` sub directory. It also contains an `output` directory, a `.gitignore` file and a `state.yml` file.

**Comment by firecow** [comment]
What `.gitlab-ci-yml` are you using?
What version of `gitlab-ci-local` are you using?

**Comment by thoroc** [comment]
* gitlab-ci-local: 4.47.0 (installed from homebrew)

The `gitlab-ci.yml` in the work project is quite hefty, but I have tried with the following to reproduce it. Mind that I have a bare bone `package.json` with a single dependency on cowsay (https://www.npmjs.com/package/cowsay) for the sake of introducing a node dependency

```yml
default:
  image: ${AWS_ECR}/alpine-nodejs:18.19.0


workflow:
  auto_cancel:
    on_new_commit: interruptible

.cache_node: &cache_node
  key:
    files:
      - ${CI_PROJECT_DIR}/package-lock.json
  paths:
    - ${CI_PROJECT_DIR}/node_modules

stages:
  - build
  - say

checks:
  stage: .pre
  # cache:
  #   - <<: *cache_node
  #     policy: pull-push
  script: |
    echo ${CI_PROJECT_DIR}
    ls ${CI_PROJECT_DIR}
    npm config set audit false
    npm config set cache ${CI_PROJECT_DIR}/.npm
    npm ci

say_hello:
  stage: say
  script:
    - echo "Heya"

say_cow:
  stage: say
  script:
    - cowsay "Moo"

say_goodbye:
  stage: say
  script:
    - echo "Goodbye"
```

The output is not what I had expected:

```sh
gitlab-ci-local
git remote -v didn't provide valid matches
Using fallback branch data
parsing and downloads finished in 104 ms
checks      starting <aws_account_id>.dkr.ecr.eu-central-1.amazonaws.com/alpine-nodejs:18.19.0 (.pre)
checks      copied to docker volumes in 695 ms
checks      $ echo ${CI_PROJECT_DIR} # collapsed multi-line command
checks      > /gcl-builds
checks      finished in 2.11 s
say_hello   starting <aws_account_id>.dkr.ecr.eu-central-1.amazonaws.com/alpine-nodejs:18.19.0 (say)
say_cow     starting <aws_account_id>.dkr.ecr.eu-central-1.amazonaws.com/alpine-nodejs:18.19.0 (say)
say_goodbye starting <aws_account_id>.dkr.ecr.eu-central-1.amazonaws.com/alpine-nodejs:18.19.0 (say)
say_hello   copied to docker volumes in 908 ms
say_cow     copied to docker volumes in 1.09 s
say_goodbye copied to docker volumes in 1.18 s
say_hello   $ echo "Heya"
say_hello   > Heya
say_cow     $ cowsay "Moo"
say_cow     > /gcl-cmd: line 4: cowsay: command not found
say_hello   finished in 2.08 s
say_cow     finished in 2.18 s  FAIL 127
say_goodbye $ echo "Goodbye"
say_goodbye > Goodbye
say_goodbye finished in 2.38 s

 PASS  checks
 PASS  say_hello
 PASS  say_goodbye
 FAIL  say_cow
  > /gcl-cmd: line 4: cowsay: command not found
pipeline finished in 4.69 s
```

**Comment by ANGkeith** [comment]
Thanks for the bug report.

See if this fixes your issue.
```yaml
    files:
      - ${CI_PROJECT_DIR}/package-lock.json    # > - package-lock.json
  paths:
    - ${CI_PROJECT_DIR}/node_modules           # > - node_modules
 ```
