### ISSUE TITLE
Not looking for local images

### ISSUE THREAD

**Issue by milouk** [firecow/gitlab-ci-local#1158]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
build backend-release:
  image:
    name: "gcr.io/kaniko-project/executor:v1.8.1-debug"
    entrypoint: [""]
  tags:
    - "docker_build"
  stage: build
  variables:
    BUILD_DOCKERFILE_DIR: "app/"
    BUILD_IMAGE_NAME: "app-release"
    BUILD_IMAGE_TAG: "$REGISTRY_URL/$REGISTRY_PROJECT/$BUILD_IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
  before_script:
    - echo "{\"auths\":{\"${REGISTRY_URL}\":{\"username\":\"$DOCKER_REGISTRY_USER\", \"password\":\"$DOCKER_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --no-push --context $BUILD_DOCKERFILE_DIR --destination $BUILD_IMAGE_TAG --build-arg GIT_COMMIT=$CI_COMMIT_SHORT_SHA --dockerfile $BUILD_DOCKERFILE_DIR/Dockerfile --cache=false --target production --skip-unused-stages
```

**Expected behavior**
My Dockerfile includes the following line:

`COPY --from=registry.docker.mycompany.com/app/mybinary:v1 /tmp/dist/ /tmp/dist/`

I don't have pull access to registry.docker.mycompany.com however, i have the image locally in my pc.
I would expect instead of trying to fetch remotely first, to search locally for an image with a matching tag

**Host information**
MacOS M1
gitlab-ci-local 4.46.1

**Containerd binary**
docker
