### ISSUE TITLE
not respecting rules

### ISSUE THREAD

**Issue by justinTM** [firecow/gitlab-ci-local#1169]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
push_ecr_image:
  script:
    - echo CI_COMMIT_TAG=$CI_COMMIT_TAG
    - echo CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_TAG == null
      when: never
    - if: $CI_COMMIT_TAG == ""
      when: never
    - if: '$CI_COMMIT_BRANCH'
      when: never
```

**Expected behavior**
should deny the job run, or indicate which rules restrict it from running.

**Actual behavior**
```console
❯ gitlab-ci-local 'push_ecr_image'
parsing and downloads finished in 30 ms
push_ecr_image starting shell (test)
push_ecr_image $ echo CI_COMMIT_TAG=$CI_COMMIT_TAG
push_ecr_image > CI_COMMIT_TAG=
push_ecr_image $ echo CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH
push_ecr_image > CI_COMMIT_BRANCH=TRZ-216-latest-prod-deployment
push_ecr_image finished in 14 ms

 PASS  push_ecr_image
```

**Host information**
macOS
gitlab-ci-local 4.47.0

**Containerd binary**
not in this case; shell executor. same behavior with images.

**Additional context**
