### ISSUE TITLE
implement `rules:[]:when:never`

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#117]
# Love 

Thank you very much for this great tool that will help me a lot with a few more features 🥰

# Request

## Description

`rules:[]:when:never` is not implemented or not as expected, especially for the pattern "launch everytime except a few cases".

## Symptom / minimal script

```
when-never:
  stage: .pre
  image: curlimages/curl:7.69.1
  script:
    - env | sort
  rules:
    - if: $GITLAB_CI
      when: never
    - if: $GITLAB_CI == "false"
      when: never
    - when: on_success
```

The job is launched an should not be.

# Workaround

## Description

Change all rules using `when:never` by a negative equivalent.

## Impact

- low : needs actions once before/after a debugging session
- ✅ medium : fixed using another top level .gitlab-ci.yml
- high : needs deep refactoring, everywhere in templates or everytime or both
