### ISSUE TITLE
Gcl use my username as host in includes

### ISSUE THREAD

**Issue by comm1x** [firecow/gitlab-ci-local#1178]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
include:
  - project: 'myrepo/myapp'
    ref: 'master'
    file:
      - 'config.yml'
```

**Expected behavior**
GCL download config.yml from Gitlab and use it.

**Actual behavior**
GCL use my username as `remote.host` and failed with error

```
Project include could not be fetched 
fatal: unable to access 'https://p.shorokhov/myrepo/myapp.git/': Could not resolve host: p.shorokhov
```

**Host information**
Macos
gitlab-ci-local 4.47.0

**Containerd binary**
Docker

Gcl failed in this `git clone` command: https://github.com/firecow/gitlab-ci-local/blob/c6d78471ca2b4305572cc31b131f96cb6416bd5e/src/parser-includes.ts#L190
