### ISSUE TITLE
`rules:[]:allow_failure:false` allows failure

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#118]
# Love 

Thank you very much for this great tool that will help me a lot with a few more features 🥰

# Request

## Description

`rules:[]:allow_failure:false` allows failure

## Symptom / minimal script

```
allow-failure:
  stage: .pre
  image: curlimages/curl:7.69.1
  script:
    - exit 1
  rules:
    - if: $GITLAB_CI
      allow_failure: false
```

The job ends with a warning instead of an error.

# Workaround

## Description

Remove `allow_failure: false` line

## Impact

- ✅ low : needs actions once before/after a debugging session
- medium : fixed using another top level .gitlab-ci.yml
- high : needs deep refactoring, everywhere in templates or everytime or both
