### ISSUE TITLE
Checking the absence of a variable with `rules: -if: (! $VARIABLE)` works in `gitlab-ci-local` but is rejected as invalid YAML by GitLab! 

### ISSUE THREAD

**Issue by sh-cau** [firecow/gitlab-ci-local#1189]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  riles:
    - if: (! $VARIABLE) 
   script:
    - echo "Should throw an error! This is not accepted by the GitLab yml parser, e.g. 'glab ci lint this-file.yml'
```

**Expected behavior**
`gitlab-ci-local` should throw an error when the syntax `if: (! $VARIABLE)` is used

**Host information**
Ubuntu 20.04 LTS
gitlab-ci-local 4.47.0

**Containerd binary**
No

**Additional context**
--
