### ISSUE TITLE
bad handling of an `include:local` within an `include:project`

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#119]
# Love 

Thank you very much for this great tool that will help me a lot with a few more features 🥰

# Request

## Description

when the remote project stated in `include:project` has (remotely) an `include:local`, treat it as a local file of the remote repo, not the current : download it too.

## Symptom / minimal script

Error is printed saying that something is missing.

# Workaround

## Description

Include every remote files :

```
include:
  - project: group/project
    file: .gitlab-ci.yml
    ref: master
  - project: group/project
    file: .templates.gitlab-ci.yml
    ref: master
```

## Impact

- ✅ low : needs actions once before/after a debugging session
- medium : fixed using another top level .gitlab-ci.yml
- high : needs deep refactoring, everywhere in templates or everytime or both
