### ISSUE TITLE
Non-existent artifact should not fail the producing job

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#120]
# Love 

Thank you very much for this great tool that will help me a lot with a few more features 🥰

# Request

## Description

When an artifact is not found, the producing job fails. Gitlab runner does not fail in this case.

## Symptom / minimal script

```
no-artifact:
  stage: .pre
  image: curlimages/curl:7.69.1
  script:
    - echo "script"
  artifacts:
    paths:
      - no.artifact
```

Should not fail but it is :

```
no-artifact copying artifacts to host
Error: No such container:path: d617ae24c22e4f11c209c3abf34fa88f74bca36b1e8485afb34bf418df7cd031:/builds/no.artifact
```

# Workaround

## Description

`touch no.artifact` at the end of the job if non-existent.

## Impact

- low : needs actions once before/after a debugging session
- ✅ medium : fixed using another top level .gitlab-ci.yml
- high : needs deep refactoring, everywhere in templates or everytime or both
