### ISSUE TITLE
The gitlab only condition is not work

### ISSUE THREAD

**Issue by WCY91** [firecow/gitlab-ci-local#1228]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - echo $TASK
    - echo "This job runs only when the task variable is set to 'shift'."
  only:
    variables:
      - $TASK == "shift"

```

**Expected behavior**
the task value is not equal "shift" but it also can work when i run the gitlab ci-local <job name>

**Host information**
Mac
gitlab-ci-local latest

**Containerd binary**
using docker

**Comment by PigeonF** [comment]
I believe the `only` keyword is [deprecated by gitlab](https://docs.gitlab.com/ee/ci/yaml/#only--except).

You can use `rules` instead.

```yaml
---
job:
  script:
    - echo $TASK
    - echo "This job runs only when the task variable is set to 'shift'."
  rules:
    - if: $TASK == "shift"
```

```console
$ gitlab-ci-local --variable TASK=shift --list
name  description  stage   when        allow_failure  needs
job                test    on_success  false
$ gitlab-ci-local --variable TASK=other --list
name  description  stage   when        allow_failure  needs
```
