### ISSUE TITLE
To delete, sorry

### ISSUE THREAD

**Issue by stiv-pro** [firecow/gitlab-ci-local#1237]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - echo "Heya"
```

**Expected behavior**
Paste a public job url.

**Host information**
Ubuntu
gitlab-ci-local 4.1.33

**Containerd binary**
Are you using docker or podman, or any other relevant containerization tool.

**Additional context**
