### ISSUE TITLE
Not recognized array input type 

### ISSUE THREAD

**Issue by bataliero** [firecow/gitlab-ci-local#1249]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
include: 
    - '/templates/template1.yaml'
```

template1.yaml:
```yml
spec:
  inputs:
    tags-list:
      type: array
      default: []
---
build-job:
  stage: build
  script:
    - echo "test"
  tags: $[[ inputs.tags-list ]]
```

**Expected behavior**
gitlab-ci-local accepts "array" type input

**Host information**
WSL - Ubuntu 22.04
gitlab-ci-local 4.50.0

**Additional context**
This GitLab CI configuration is invalid: `/templates/template1.yml`: header:spec:inputs:tags-list input type unknown value: array.

More information [here](https://docs.gitlab.com/ee/ci/yaml/index.html#specinputstype).
