### ISSUE TITLE
Mixing shell/docker executor jobs, doesn't play well with new docker artifacts handling.

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#125]
```bash
./ts-node --cwd examples/docker-compose-nodejs/
```

**Comment by firecow** [comment]
@bcouetil Working on a solution.

**Comment by firecow** [comment]
```
---
# @Description Install npm packages
npm-install:
  stage: .pre
  image: node:alpine
  dependencies: []
  artifacts:
    paths:
      - node_modules/
  script:
    - npm install --no-audit

# @Description Find security vulnerabilities in node_modules
npm-audit:
  stage: test
  image: node
  allow_failure: true
  needs: []
  script: npm audit

# @Description Find outdated packages in node_modules
npm-outdated:
  stage: test
  image: node
  allow_failure: true
  needs: [npm-install]
  script:
    - npx -s ncu -e2 --deprecated --packageFile package.json

# @Description Up docker-compose services
docker-compose-up:
  stage: deploy
  environment:
    url: http://localhost:8891
    name: local
  script:
    - docker-compose up -d
```

How does it sound to solve this by introducting a `# @CopyArtifactsToHost` decorator? @bcouetil 

```
# @CopyArtifactsToHost
# @Description Install npm packages
npm-install:
  stage: .pre
  image: node:alpine
  dependencies: []
  artifacts:
    paths:
      - node_modules/
  script:
    - npm install --no-audit
```
