### ISSUE TITLE
Revisit if `types` is indeed an illegal name

### ISSUE THREAD

**Issue by hverlin** [firecow/gitlab-ci-local#1263]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
types:
  script:
    - echo "test"

test:
  needs: [types]
  script:
    - echo "test"
```

**Expected behavior**
According to the documentation, it should not work.
https://docs.gitlab.com/ee/ci/jobs/#job-name-limitations

However, it does work:
https://gitlab.com/hverlin/gitlab-ci-local-tests/-/pipelines/1324968259

Probably this is a limitation that they forgot to remove from the documentation?

```shell
> gitlab-ci-local
needs: [types] for test could not be found
```

Two solutions:
- remove `types` from: https://github.com/firecow/gitlab-ci-local/blob/ba3509a42b5e0155913fb09d0885c93284df1f39/src/job.ts#L69-L73
- add a warning to the console if a job name matches an invalid name

**Comment by ANGkeith** [comment]
hmm,

1st solution, if gitlab removes that from the documentation. Because, can't really tell whether they forget to remove or they're reserving those word for future use

Thus, 2nd solution sounds good to me.

**Comment by ANGkeith** [comment]
The following all works too eventhough the docs says it's illegal lols..

```yaml
---
"true":
  script:
    - echo "test"

"false":
  script:
    - echo "test"

"nil":
  script:
    - echo "test"
```
