### ISSUE TITLE
"gitlab-ci-local --preview" Does not expand pipeline variables

### ISSUE THREAD

**Issue by rozcietrzewiacz** [firecow/gitlab-ci-local#1270]
**Minimal .gitlab-ci.yml illustrating the issue**

```yml
variables:
  IMAGE: "alpine:latest"
job:
  image: ${IMAGE}
  script:
    - echo
```

----

**Expected behavior**

Preview should include the  expanded name of `image`:
```yml
---
stages:
  - .pre
  - build
  - test
  - deploy
  - .post
job:
  image:
    name: "alpine:latest"
  script:
    - echo
```

**Actual behavior**

Variable is not expanded:
```yml
---
stages:
  - .pre
  - build
  - test
  - deploy
  - .post
job:
  image:
    name: ${IMAGE}
  script:
    - echo
```

**Comment by ANGkeith** [comment]
possibly related to https://github.com/firecow/gitlab-ci-local/issues/254#issuecomment-1997304705

**Comment by rozcietrzewiacz** [comment]
Looks related, though I'm not sure about the exact use case of the in #254.
In the example I provided, `gitlab-ci-local --preview` becomes a bit useless, as there's no way to tell what the given configuration would actually do.

**Comment by hverlin** [comment]
I think it should be a different flag than `--preview` to expand variables. 

I think the goal of `--preview` is to have something similar to the full configuration tab on GitLab
![image](https://github.com/firecow/gitlab-ci-local/assets/9151470/7aa6c6f5-d819-49f0-b3b9-753a755309d5)

> --preview  Print YML with defaults, includes, extends and reference's expanded 

Output of `--preview` is a bit different from GitLab full configuration, however.

Maybe having a command to expand everything that it can before executing could be useful, but it might require a different logic than what preview is using

**Comment by ANGkeith** [comment]
There might be some tricky scenario, 


```yaml
---
stages:
  - build
  - deploy

variables:
  IMAGE: foo

foo:
  stage: build
  image: alpine
  script:
    - echo "IMAGE=testttt" >> build.env
  artifacts:
    reports:
      dotenv: build.env

bar:
  stage: deploy
  image: $IMAGE
  script:
    - echo 1
```
In this case, the image used by the `bar` job will be `testttt`. So maybe an idea is that when `dotenv` artifacts is detected, it should not expand the pipeline variables ?

**Comment by ANGkeith** [comment]
in general, I think this is nice to have.


Do you have any scenarios which you think can be useful ? 

because based of your `image` example,
we can see what image is used by running the `.gitlab-ci.yml`

 
![image](https://github.com/firecow/gitlab-ci-local/assets/28011783/bb8a9aaf-2d6a-4c36-8475-43e6cea29541)

**Comment by rozcietrzewiacz** [comment]
@hverlin Yeah, I was expecting `gitlab-ci-local --preview` to provide the same set of information as gitlab ui does. I don't understand why it strips the `variables` section altogether for example.

@ANGkeith My specific use case is related to iterating over multiple gitlab-ci repositories to obtain various statistics on how different pipelines are structured and optimize them. So it is very useful to me to use a tool that resolves `includes` for example. The description of `--preview` feature suggests it would behave more like Gitlab's "Full configuration" view in pipeline editor, but sadly it doesn't.

**Comment by ANGkeith** [comment]
> I don't understand why it strips the variables section
ah you're referring to this

if it's about stripping of the section, it's due to
https://github.com/firecow/gitlab-ci-local/blob/397f76e881d838fbe33d3bbab9e9f92b8ce03359/src/handler.ts#L51

perhaps, shall we only delete the `hidden jobs` ? 

but this will break a few of our unit test that relies on `--preview`

**Comment by ANGkeith** [comment]
> a tool that resolves includes

does'nt gcl's `--preview`  already do this ? 

just that the `variables` are removed

**Comment by hverlin** [comment]
In the latest version (not released yet), you will have access to this file.

```
.gitlab-ci-local/expanded-gitlab-ci.yml
```
It's written for any commands (e.g., `gcl --list`)

This would be the output:
```yml
stages:
  - .pre
  - build
  - test
  - deploy
  - .post
variables:
  IMAGE: alpine:latest
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: 'false'
job:
  image:
    name: ${IMAGE}
  script:
    - echo
```

Probably `FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR` would need to be removed also :sweat_smile: 

(this produces what @ANGkeith is suggesting)
