### ISSUE TITLE
`default` is incorrectly applied to shared YAML references

### ISSUE THREAD

**Issue by hverlin** [firecow/gitlab-ci-local#1277]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
default:
  cache:
    key: 'my-key'
    paths:
      - my-file

.some-shared-yaml:
  if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"

my-job:
  script: 'echo test'
  rules:
    - !reference [.some-shared-yaml]
```
fails validation.

```
Invalid .gitlab-ci.yml configuration!
        • 'cache' property is not expected to be here at my-job.rules.0
        • '0' property type must be string at my-job.rules.0
```

Indeed, `gitlab-ci-local` generates an invalid internal pipeline definition
![image](https://github.com/firecow/gitlab-ci-local/assets/9151470/fd70b100-c55c-428a-9857-171eaa5731cf)
```yml
stages:
  - .pre
  - build
  - test
  - deploy
  - .post
default:
  cache:
    key: my-key
    paths:
      - my-file
.some-shared-yaml: &ref_0
  if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  cache:
    - &ref_1
      key: my-key
      paths:
        - my-file
      policy: pull-push
      when: on_success
my-job:
  script:
    - echo test
  rules:
    - *ref_0
  cache:
    - *ref_1
```

**Expected behavior**
![image](https://github.com/firecow/gitlab-ci-local/assets/9151470/3b9a46ed-0690-43c5-a903-48eb017a842d)

![image](https://github.com/firecow/gitlab-ci-local/assets/9151470/d8e4f2eb-3eaf-4647-a5ad-617e3e6e04b4)

The expected behavior is that the `shared-yaml` object should not extend `default` as it's not a job actually:
```
.some-shared-yaml:
  if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
```

## Additional context
This issue was not an issue before `json-schema-validation` got introduced, as using `--json-schema-validation=false`  does run the job correctly
```
❯ gcl my-job --json-schema-validation=false
parsing and downloads finished in 49 ms.
[19:45:42 1.45 ms] my-job starting shell (test)
[19:45:42 8.31 ms] my-job $ echo test
[19:45:42 8.48 ms] my-job > test
[19:45:42 9.27 ms] my-job finished in 9.27 ms

 PASS  [9.27 ms] my-job
```
