### ISSUE TITLE
Inability to work with CI processes that use nested Docker containers

### ISSUE THREAD

**Issue by ttsiodras** [firecow/gitlab-ci-local#1282]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  stage: build
  image: DockerImageA
  script:
    - do thing 1 inside DockerImageA
    - do thing 2 inside DockerImageA
    - docker run -v $CI_PROJECT_DIR:$CI_PROJECT_DIR -e CI_PROJECT_DIR --rm -it DockerImageB /bin/bash -c 'cd $CI_PROJECT_DIR ; do stuff inside DockerImageB'
```

This works fine if the gitlabrunner's config.toml has the "/builds" folder and the "/var/run/docker.sock" inside the "volumes" key for the "runners.docker". The "/builds" is basically in the host filesystem, so the nested docker can access the CI_PROJECT_DIR just as much as the initial (DockerImageA) could.

**Expected behavior**
Expected behavior is to execute commands from inside DockerImageB that can see the CI_PROJECT_DIR.

**Host information**
Not really relevant. It's an issue with how host-based folders need to be used (bind-mounted) for this to function. 

**Containerd binary**
Docker.

**Additional context**
I did try passing --volume /gsl-builds but I got an error that this folder is already mapped. Indeed it is, with a transient mapping; one that can't allow the nested Docker invocation to map it further inside the container made for DockerImageB.
