### ISSUE TITLE
CICD Component: 'allow_failure' property type must be boolean 

### ISSUE THREAD

**Issue by bataliero** [firecow/gitlab-ci-local#1287]
**Component `template.yml`:**
```yml
---
spec:
  inputs:
    allow-failure:
      type: boolean
      default: false
---
shellcheck:
  image: koalaman/shellcheck-alpine:v0.10.0
  allow_failure: $[[ inputs.allow-failure ]]
  script:
    - shellcheck
```

and 
.gitlab-ci.yml
```
include:
  - local: "common/template.yml"
```

Error message
```
Invalid .gitlab-ci.yml configuration!
        • 'allow_failure' property type must be boolean at shellcheck.allow_failure

For further troubleshooting, consider either of the following:
        • Copy the content of <path> to the pipeline editor (​https://docs.gitlab.com/ee/ci/pipeline_editor/​) to debug it
        • Use --json-schema-validation=false to disable schema validation (not recommended)
```

**Host information**
Description:    Ubuntu 22.04.3 LTS
gitlab-ci-local 4.52.1

**Containerd binary**
Docker version 26.1.4
