### ISSUE TITLE
CICD Component - cache issue - Error: ENOENT: no such file or directory key-file

### ISSUE THREAD

**Issue by bataliero** [firecow/gitlab-ci-local#1288]
**Component `template.yml`:**
```yml
---
job1:
  image: python
  script:
    - python
  variables:
    requirements_file: requirements.txt
    req_path: /tmp
  cache:
    key:
      files:
        - ${requirements_file}
    paths:
      - ${req_path}
```

and 
.gitlab-ci.yml
```
include:
  - local: "python/template.yml"
```

Error message
```
Error: ENOENT: no such file or directory, stat '<abs-path>/requirements.txt'
```

**Host information**
Description:    Ubuntu 22.04.3 LTS
gitlab-ci-local 4.52.1

**Containerd binary**
Docker version 26.1.4

**Extra context**
Everything works correctly when `requirements.txt` exist in repository which uses this component. The problem only exist if repository using this CICD Component does not need `requirements.txt` and user does not create/commit one.

This issue does not occur on the GitLab instance. If `requirements.txt` is missing, cache restoring is simply skipped, and the job proceeds to execute the `script` section.
