### ISSUE TITLE
Passing boolean input parameters

### ISSUE THREAD

**Issue by devtribe** [firecow/gitlab-ci-local#1289]
If you passing a boolean input parameter through more than one component, the type getting lost.

With the following example you get the error 
`This GitLab CI configuration is invalid: "a.gitlab-ci.yml": "abc" input: provided value is not a boolean.`

a.gitlab-ci.yml
```yml
---
spec:
  inputs:
    abc:
      type: boolean
```
b.gitlab-ci.yml
```yml
---
spec:
  inputs:
    abc:
      type: boolean

---
include:
  - component: a
    inputs:
      abc: $[[ inputs.abc ]]
```
.gitlab-ci.yml
```yml
---
include:
  - component: b
    inputs:
      abc: true

```
**Expected behavior**
Everything works fine

**Host information**
macOS 14.5
gitlab-ci-local 4.52.1

**Containerd binary**
docker
