### ISSUE TITLE
"job.artifacts.reports.annotations" property is not allowed

### ISSUE THREAD

**Issue by bohndthi** [firecow/gitlab-ci-local#1307]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - echo "Heya"
   artifacts:
        reports:
            annotations: annotations.json

  
```

Console output:
```
Invalid .gitlab-ci.yml configuration!
        • 'annotations' property is not expected to be here at job.artifacts.reports
```

**Expected behavior**
"Heya" geths 

**Host information**
Ubuntu
gitlab-ci-local 4.52.2
