### ISSUE TITLE
variables.yml : precedence should be project over group over global

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#131]
# Request

## Description

Variable precedence should be project over group over global.

For now, global takes precedence over project.

## Symptom / minimal script

```
project:
  gitlab.cicd.company.com/group/project.git:
    MY_VARIABLE: project

group:
  gitlab.cicd.company.com/group/:
    MY_VARIABLE: group

global:
  MY_VARIABLE: global
```

in pipelines, `MY_VARIABLE = global`, it should be `project`

# Workaround

## Description

Remove `MY_VARIABLE` from global.

## Impact

- ✅ low : needs actions once before/after a debugging session
- medium : fixed using another top level .gitlab-ci.yml
- high : needs deep refactoring, everywhere in templates or everytime or both
