### ISSUE TITLE
manual_confirmation validation error

### ISSUE THREAD

**Issue by shuguenot** [firecow/gitlab-ci-local#1321]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
delete_job:
  script:
    - make delete
  when: manual
  manual_confirmation: 'Are you sure you want to delete $CI_ENVIRONMENT_SLUG?'
```

**Observed behavior**
```
gitlab-ci-local --list

Invalid .gitlab-ci.yml configuration!
        • 'manual_confirmation' property is not expected to be here at delete_job
```

**Expected behavior**
No error, this configuration is valid according the official documentation
https://docs.gitlab.com/ee/ci/yaml/?query=manual_confirmation#manual_confirmation

**Host information**
macOS
gitlab-ci-local 4.52.2
