### ISSUE TITLE
coverage_format validation error

### ISSUE THREAD

**Issue by dzwicker** [firecow/gitlab-ci-local#1327]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
coverage:report:
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
```

**Observed behavior**
```bash
gitlab-ci-local --list
Invalid .gitlab-ci.yml configuration!
	• 'coverage_format' property must be one of [cobertura] (found jacoco) at kotlin:test:coverage:report.artifacts.reports.coverage_report.coverage_format
```
**Expected behavior**
No error, this configuration is valid according the official documentation (new in current release)
[artifacts:reports:coverage_report](https://docs.gitlab.com/ee/ci/yaml/artifacts_reports.html#artifactsreportscoverage_report)

**Host information**
macOS 
gitlab-ci-local 4.53.0
