### ISSUE TITLE
Validation differs from local with "when" syntax

### ISSUE THREAD

**Issue by heydonovan** [firecow/gitlab-ci-local#1328]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
x:
  script:
    - echo "this does nothing!"
  stage: .pre
  when: never
```

**Expected behavior**
An error to trigger with `gitlab-ci-local --preview` or with `gitlab-ci-local x`. Instead it runs locally but not on GitLab

```
> $ gitlab-ci-local x
x starting shell (.pre)
x $ echo "this does nothing!"
x > this does nothing!
x finished in 13 ms
```

**Host information**
macOS 14.6.1
gitlab-ci-local 4.53.0

**Additional context**

The "Pipeline editor" gives the following error:

> This GitLab CI configuration is invalid: jobs:x when should be one of: on_success, on_failure, always, manual, delayed
