### ISSUE TITLE
Issue when using unavailable variable in `rules`

### ISSUE THREAD

**Issue by dorianm** [firecow/gitlab-ci-local#133]
Hello,

First of all thank you very much for this tool, it's awesome. I use gitlab-ci a lot and it saves me a lot of time ! 😍

I have some gitlab-ci job which are run only when `$CI_COMMIT_TAG` is a version tag (eg *v1.0.0*). I test this variable with a regex (see https://docs.gitlab.com/ee/ci/variables/README.html#regex-pattern-matching) in my `.gitlab-ci.yml`.

This is a minimal example :

```yaml
job:
  script:
    - echo "Hello world"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/
```

When I run `gitlab-ci-local` with this `.gitlab-ci.yml` file, I get this error :

```
TypeError: Cannot read property 'match' of null
    at eval (eval at evaluateRuleIf (/usr/local/lib/node_modules/gitlab-ci-local/src/utils.ts:128:16), <anonymous>:1:6)
    at Function.evaluateRuleIf (/usr/local/lib/node_modules/gitlab-ci-local/src/utils.ts:128:16)
    at Function.getRulesResult (/usr/local/lib/node_modules/gitlab-ci-local/src/utils.ts:81:23)
    at new Job (/usr/local/lib/node_modules/gitlab-ci-local/src/job.ts:105:38)
    at Parser.initJobs (/usr/local/lib/node_modules/gitlab-ci-local/src/parser.ts:243:25)
    at Function.create (/usr/local/lib/node_modules/gitlab-ci-local/src/parser.ts:47:9)
    at handler (/usr/local/lib/node_modules/gitlab-ci-local/src/default-cmd.ts:61:18)
    at Object.exports.handler (/usr/local/lib/node_modules/gitlab-ci-local/src/default-cmd.ts:69:9)
```

It looks like if you use a regex test against an unavailable variable (`$CI_COMMIT_TAG` in my case), the if evaluation fails. Maybe we should substitute unavailable variable with empty string in this case ?

**Comment by firecow** [comment]
On it @dorianm

**Comment by dorianm** [comment]
@firecow : Thank you you're fast !

I tried to fix it in local, I add two tests for this : 

```typescript
test("regex match on unavailable variable", () => {
    const ruleIf = "$VAR =~ /testvalue/";
    const val = Utils.evaluateRuleIf(ruleIf, {});
    expect(val).toBe(false);
});

test("regex not match on unavailable variable", () => {
    const ruleIf = "$VAR !~ /testvalue/";
    const val = Utils.evaluateRuleIf(ruleIf, {});
    expect(val).toBe(true);
});
```

It confirms this following behaviour (test in Gitlab 13.10 this morning) : 

```yaml
---
# This job is executed on every tag/branch/… except on tags vX.Y.Z
job-not-match:
  script:
    - echo "Hello world"
  rules:
    - if: $CI_COMMIT_TAG !~ /^v\d+.\d+.\d+/

# This job is executed on tags vX.Y.Z only
job-match:
  script:
    - echo "Toto"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/
```

I just try this change (in `evaluateRuleIf` function) : 

```typescript
const expandedRule = ruleIf.replace(/[$]\w*/g, (match) => {
    const sub = envs[match.replace(/^[$]/, "")];
    return sub != null ? `'${sub}'` : "\"\"";
    //return sub != null ? `'${sub}'` : "null"; // Current version
});
```

It works but that breaks two others tests. I hope it can help you !
