### ISSUE TITLE
Service healthcheck fails for mysql:8.0.32

### ISSUE THREAD

**Issue by ArjArav98** [firecow/gitlab-ci-local#1346]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
stages:
  - test

test-job:
  image: python:3.8.19-slim-bullseye
  stage: test
  variables:
    MYSQL_ROOT_PASSWORD: random
  services:
    - name: mysql:8.0.39
      alias: test_db
  script:
    - echo "Hello"
```
When I run this using `gitlab-ci-local`, the healthcheck for the service does not pass. The `wait-for-it` script says that it's been waiting for 30 seconds. Could this be because the `mysql:8.0.39` container is taking more than 30 seconds to load?

The healthcheck passes if I modify the service image to be anything else. Please check out the examples I've provided below.

**Expected behavior**
https://gitlab.com/ArjArav98/hello-world/-/jobs/7839061521

**Host information**
MacOS
gitlab-ci-local 4.53.0

**Containerd binary**
Docker

**Additional context**
When the same job is run but with different database services, the healthcheck passes for the service. Here are examples which pass the healthcheck.
```
stages:
  - test

test-job:
  image: python:3.8.19-slim-bullseye
  stage: test
  variables:
    MYSQL_ROOT_PASSWORD: random
  services:
    - name: mysql:8.1
      alias: test_db
  script:
    - echo "Hello"
```
```
stages:
  - test

test-job:
  image: python:3.8.19-slim-bullseye
  stage: test
  variables:
    MYSQL_ROOT_PASSWORD: random
  services:
    - name: mysql:8.4
      alias: test_db
  script:
    - echo "Hello"
```
```
stages:
  - test

test-job:
  image: python:3.8.19-slim-bullseye
  stage: test
  variables:
    MYSQL_ROOT_PASSWORD: random
  services:
    - name: mysql:5.7.43
      alias: test_db
  script:
    - echo "Hello"
```
```
stages:
  - test

test-job:
  image: python:3.8.19-slim-bullseye
  stage: test
  variables:
    POSTGRES_PASSWORD: password
  services:
    - name: postgres:16.2
      alias: test_db
  script:
    - echo "Hello"
```

**Comment by ArjArav98** [comment]
This is unrelated but this seemed a good chance to say thanks for the amazing tool that has been developed here! It has saved me a ton of time _and_ Gitlab CI compute minutes at work. Please keep up the good work!

**Comment by ANGkeith** [comment]
I can't really replicate your issue

> Could this be because the mysql:8.0.39 container is taking more than 30 seconds to load?
possible, depends on your pc, but it's weird that it works for other mysql version


Have you tried running the following ? 
> docker run --env MYSQL_ROOT_PASSWORD=random -ti mysql:8.0.39


could you dump the entire `gcl` output for the following config ? 
```yaml
variables:
  MYSQL_ROOT_PASSWORD: random
default:
  image: alpine

mysql-8.0.39:
  services:
    - name: mysql:8.0.39
      alias: mysql-8.0.39
  script:
    - echo "Hello"
mysql-8.1:
  services:
    - name: mysql:8.1
      alias: mysql-8.1
  script:
    - echo "Hello"
mysql-8.4:
  services:
    - name: mysql:8.4
      alias: mysql-8.4
  script:
    - echo "Hello"
```
