### ISSUE TITLE
files not found in after_script in root folder which is created in before_script

### ISSUE THREAD

**Issue by varunpalekar** [firecow/gitlab-ci-local#1350]
Currently I am trying to access some files which are created in `/` folder in before, but not accessible in `after_script`.
For example in below example, creating `/test` file in `before_script`, is accessible in `script` but not `after_script`.

I checked this behaviour in gitlab-ci, and working fine there.

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
test:
  image: nixos/nix:2.24.6
  before_script:
    - echo "test" > /test
  script:
    - cat /test
  after_script:
    - cat /test
```

**Output**
```
> gitlab-ci-local test
parsing and downloads finished in 65 ms.
json schema validated in 86 ms
test starting nixos/nix:2.24.6 (test)
test copied to docker volumes in 895 ms
test $ echo "test" > /test
test $ cat /test
test > test
test Running after script...
test $ cat /test
test > cat: /test: No such file or directory
```

**Expected behavior**
```
> gitlab-ci-local test
parsing and downloads finished in 65 ms.
json schema validated in 86 ms
test starting nixos/nix:2.24.6 (test)
test copied to docker volumes in 895 ms
test $ echo "test" > /test
test $ cat /test
test > test
test Running after script...
test $ cat /test
test > test
```

**Host information**
MacOS 15
gitlab-ci-local 4.53.0

**Containerd binary**
docker

**Additional context**
NA
