### ISSUE TITLE
CI_PROJECT_ROOT_NAMESPACE predefined variable is not defined

### ISSUE THREAD

**Issue by rgalonso** [firecow/gitlab-ci-local#1357]
The `CI_PROJECT_ROOT_NAMESPACE` [predefined variable](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html) is not defined.

From the GitLab documentation:
> The root project namespace (username or group name) of the job. For example, if CI_PROJECT_NAMESPACE is root-group/child-group/grandchild-group, CI_PROJECT_ROOT_NAMESPACE is root-group.

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
succeed-if-defined:
  image: ubuntu
  script:
    - echo "CI_PROJECT_ROOT_NAMESPACE is '${CI_PROJECT_ROOT_NAMESPACE}'"
    - test -n "${CI_PROJECT_ROOT_NAMESPACE}"
```

**Expected behavior**
Above job succeeds

**Host information**
Ubuntu
gitlab-ci-local 4.53.0

**Containerd binary**
`docker`

**Additional context**
