### ISSUE TITLE
Cache is mixed up between node_modules and vendor directories

### ISSUE THREAD

**Issue by lk77** [firecow/gitlab-ci-local#1390]
The cache does not seems to work with gcl, a simple config as below fail with gcl but succeed with gitlab,

if i do `ls vendor` i get the files that should be in node_modules

any artisan command fails because there is no autoload.php file in vendor directory (overrided by npm install)

```yml
---
myjob:
  allow_failure: false
  image: 'myimage'
  when: manual
  script:
    - composer install
    - npm install
    - php artisan
  cache:
    key:
      files:
        - package-lock.json
        - composer.lock
    paths:
      - node_modules/
      - vendor/
```

**Expected behavior**
The cache is not mixed up between node_modules and vendor

**Host information**
Ubuntu 22
gitlab-ci-local 4.55.0

**Containerd binary**
docker runner is used, but gcl runs in wsl

thanks.

edit :

``MOUNT_CACHE=true`` seems to be the issue here in .gitlab-ci-local-env
