### ISSUE TITLE
Podman user gets `gcl-cmd: applet not found` error

### ISSUE THREAD

**Issue by elafontaine** [firecow/gitlab-ci-local#1405]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
myjob:
  stage: check
  image:
    name: mysteriouscode/cfn-lint:latest
    entrypoint: [""]
  script:
    - cfn-lint CloudFormation.yml
```

**Expected behavior**
Same behaviour as docker users, but I'm unsure why it's different on podman yet...

**Host information**
MacOS podman 
gitlab-ci-local 4.55.0

**Containerd binary**
podman

**Additional context**
We run the jobs with docker most of the team, but the license cost is starting to be a concern.  Some people were already using podman, but were unable to get the same jobs as us to run.  You have a snippet of the code that fails.  The error message seems to be caused by this line ; https://github.com/firecow/gitlab-ci-local/blob/4.55.0/src/job.ts#L872C143-L872C151
This is the only place where I found "gcl-cmd".

I will try to dig out more details.
