### ISSUE TITLE
Leaks networks and volumes on every run (some jobs)

### ISSUE THREAD

**Issue by elafontaine** [firecow/gitlab-ci-local#1407]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
docker_build:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "blablabla"
```

**Expected behavior**
After running, clear the network that was needed for the service and the job container to talk together.

**Host information**
MacOS
gitlab-ci-local 4.55.0

**Containerd binary**
docker

**Additional context**
https://github.com/firecow/gitlab-ci-local/blob/master/src/job.ts#L543 < not tracked for cleanup
