### ISSUE TITLE
Parsing of rules fails in where there is no whitespace near the parentheses

### ISSUE THREAD

**Issue by trygve55** [firecow/gitlab-ci-local#1416]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
working_job:
  script:
    - echo "Hello world!"
  rules:
    - if: '($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^perf_.*$/ ) || $CI_COMMIT_BRANCH =~ /^(master|production)$/'

error_job:
  script:
    - echo "Hello world!"
  rules:
    - if: '($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^perf_.*$/) || $CI_COMMIT_BRANCH =~ /^(master|production)$/'
```

**Expected behavior**
Both jobs should run fine. 

The first job works fine, but if the second job is added to the gitlab-ci.yml we get the error:
```
Error attempting to evaluate the following rules:
  rules:
    - if: '("push" == "merge_request_event" && null =~ /^perf_.*$/) || "LDS-4394" =~ /^(master|production)$/'
as
("push" == "merge_request_event" && false  || "LDS-4394".match(/^(master|production)$/) != null

SyntaxError: Unexpected end of input
    at eval (<anonymous>)
    at Function.evaluateRuleIf (/snapshot/firecow-gitlab-ci-local/src/utils.ts:260:23)
    at Function.getRulesResult (/snapshot/firecow-gitlab-ci-local/src/utils.ts:181:24)
    at new Ut (/snapshot/firecow-gitlab-ci-local/src/job.ts:229:38)
    at callback (/snapshot/firecow-gitlab-ci-local/src/parser.ts:179:29)
    at Function.forEachRealJob (/snapshot/firecow-gitlab-ci-local/src/utils.ts:54:13)
    at e.init (/snapshot/firecow-gitlab-ci-local/src/parser.ts:165:15)
    at async Function.create (/snapshot/firecow-gitlab-ci-local/src/parser.ts:60:9)
    at async AR (/snapshot/firecow-gitlab-ci-local/src/handler.ts:98:18)
    at async Object.handler (/snapshot/firecow-gitlab-ci-local/src/index.ts:34:21)
```

The difference between them is the whitespace character between `...E =~ /^perf_.*$/` and `)`

This works in GitLab Enterprise Edition [v17.0.8-ee] and have been working since 2022.

**Host information**
Ubuntu 20.04
gitlab-ci-local 4.55.0
