### ISSUE TITLE
Interactive job output broken

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#1437]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
# @Interactive
test:
  rules: [{when: manual}]
  script:
    - docker run -it debian bash
```

```sh
laptop:~/workspace/gitlab-com-ci-debugging$ gitlab-ci-local test
parsing and downloads finished in 53 ms.
json schema validated in 166 ms
<gclShellPromptPlaceholder> docker run -it debian bash
```

**Expected behavior**
I would expect the output to contain pretty green lines of text :laughing: 

**Host information**
Ubuntu
gitlab-ci-local 4.56.0

**Containerd binary**
Docker
