### ISSUE TITLE
Invalid .gitlab-ci.yml configuration with "environment: $env" usage

### ISSUE THREAD

**Issue by vladadmin** [firecow/gitlab-ci-local#1441]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
.shared_rules:
  test_rule:
    - if: '$CI_COMMIT_BRANCH == "test"'
      variables:
        PIPELINE_ENVIRONMENT: test

test:
  image: alpine
  environment:
    name: $PIPELINE_ENVIRONMENT
  script:
    - echo "Test"
  rules:
    - !reference [.shared_rules, test_rule]
```

**Expected behavior**
https://gitlab.com/vladadmin/gitlab-ci-local-test/-/jobs/8493797441
https://gitlab.com/vladadmin/gitlab-ci-local-test/-/blob/test/.gitlab-ci.yml

**Host information**
Rocky Linux 9.5
gitlab-ci-local 4.56.0

**Additional context**
Get error text:
```
Invalid .gitlab-ci.yml configuration!
   • 'environment' property type must be string at test.environment
   • property 'name' must not have fewer than 1 characters at test.environment.name
```
and exit code <> 0

It may be possible to limit the warning to a variable in `environment: $SOME_VAR`, but the exit-code must be 0

**Comment by ANGkeith** [comment]
![image](https://github.com/user-attachments/assets/bc625f1c-9774-4dd2-90da-9b0cfecfe684)

i'll recommend something like that instead, what do you think ?

**Comment by ANGkeith** [comment]
```yaml
---
test:
  rules:
    - if: '"test" == "test"'
      variables:
        PIPELINE_ENVIRONMENT: test
  image: alpine
  environment:
    name: $PIPELINE_ENVIRONMENT    # expects this to be expanded to `test`
  script:
    - echo $PIPELINE_ENVIRONMENT
```

**Comment by vladadmin** [comment]
Yes, it's the same thing - the same error occurs

**Comment by ANGkeith** [comment]
just take note that for the non-happy path, 
```yaml
---
test:
  rules:
    - if: '"test" != "test"'
      variables:
        PIPELINE_ENVIRONMENT: test
  image: alpine
  environment:
    name: $PIPELINE_ENVIRONMENT    # expects this to be expanded to `test`
  script:
    - echo $PIPELINE_ENVIRONMENT
```

this will fail the json-schema validation, which is expected



and to get around this, i'll recommend to define a dummy value for the `PIPELINE_ENVIRONMENT`
![image](https://github.com/user-attachments/assets/6ca20537-4e3a-4201-a77a-5ec908e96ec0)
