### ISSUE TITLE
Includes not working on self-hosted gitlab

### ISSUE THREAD

**Issue by ojsef39** [firecow/gitlab-ci-local#1442]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages: [build]
include:
  - project: 'https://git.url.de/group/gitlab-ci-templates'
    file:
      - Jobs/Job.gitlab-ci.yml
```

**Expected behavior**
Getting includes from correct URL not gitlab.com/self-hosted.url/
(Not public)

**Host information**
macOS 15.1.1 (24B91)
gitlab-ci-local 4.55.0

**Containerd binary**
podman

**Additional context**
Logs:

```bash
🚀 gitlab-ci-local --stage build --fetch-includes
(node:41459) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
git remote get-url origin didn't provide valid matches
Project include could not be fetched { project: https://git.url.de/group/gitlab-ci-templates, ref: HEAD, file: Jobs/Job.gitlab-ci.yml }
Error: Command failed with exit code 128: set -eou pipefail; git archive --remote=ssh://git@gitlab.com:22/https://git.url.de/group/gitlab-ci-templates.git HEAD Jobs/Job.gitlab-ci.yml | tar -f - -xC .gitlab-ci-local/includes/gitlab.com/https://git.url.de/group/gitlab-ci-templates/HEAD/
remote:
remote: ========================================================================
remote:
remote: ERROR: The namespace you were looking for could not be found.

remote:
remote: ========================================================================
remote:
fatal: the remote end hung up unexpectedly

🗂  repo on ⚡add_tests
🚀 git remote get-url origin
https://git.url.de/group/group/repo/
```

**Comment by ojsef39** [comment]
Ive also tried using variables to set the CI but had no luck with that, something like this:

**Comment by ojsef39** [comment]
Pretty ugly but this workaround does the trick:

```yaml
stages: [build]

include:
  - remote: 'https://git.url.de/group/gitlab-ci-templates/-/raw/main/Jobs/Job.gitlab-ci.yml'
```

**Comment by ANGkeith** [comment]
could you try with this instead ? 

```yaml
---
stages: [build]
include:
  - project:  'group/gitlab-ci-templates' 
    file:
      - Jobs/Job.gitlab-ci.yml
```

---

We currently do not supports this syntax `  - project: 'https://git.url.de/group/gitlab-ci-templates'`, don't really see it documented in gitlab docs
