### ISSUE TITLE
Ide-helper command is not shown in --list. Problem with exists in rules

### ISSUE THREAD

**Issue by NicaCego** [firecow/gitlab-ci-local#1462]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
  rules:
    - exists: [$PHP_ROOT/artisan]
      if: $IDE_HELPER_SKIP != 'true'
      when: on_success
      allow_failure: false
```

**Expected behavior**
Should display ide-helper command in `gitlab-ci-local --list`

**Host information**
Ubuntu 24.04.1 LTS
gitlab-ci-local 4.56.0

**Additional context**
`    - { if: $IDE_HELPER_SKIP != 'true', when: on_success, allow_failure: false}` seems to work

**Comment by ANGkeith** [comment]
not sure if i understood you correctly, but in the eg. you provide there's an additional `exist` key

```yaml
---
  rules:
    - exists: [$PHP_ROOT/artisan]  # remove this
      if: $IDE_HELPER_SKIP != 'true'
      when: on_success
      allow_failure: false
```

**Comment by firecow** [comment]
The problem is variable expansion in  `exists:`

I just ran an ultra simple example using 
```
---
test:
  image: debian
  rules:
    - exists: [artisan]  # remove this
      if: $IDE_HELPER_SKIP != 'true'
      when: on_success
      allow_failure: false
  script:
    - echo "I ran"

```

and it works great both locally and on gitlab.com

But the moment I introduced `$PHP_ROOT` into the equation, exists rule only worked on gitlab.com
