### ISSUE TITLE
gitlab-ci-local overwrites a pre-defined variable from gitlab-ci.yml

### ISSUE THREAD

**Issue by BenediktBertsch** [firecow/gitlab-ci-local#1465]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
test:
  stage: deploy
  variables:
    CI_PROJECT_DIR: "TEST_DIRECTORY"
  script:
    - |
      echo "CI_PROJECT_DIR: $CI_PROJECT_DIR"
```

**Expected behavior**
The expected behavior should be that the CI_PROJECT_DIR variable is overwritten by the job's variable.
Expected output should be:
"test > CI_PROJECT_DIR: TEST_DIRECTORY" instead I get "test > CI_PROJECT_DIR: /gcl-builds"

**Host information**
Ubuntu
gitlab-ci-local 4.56.2

**Containerd binary**
I'm using docker.

Thank you for this great tool.
