### ISSUE TITLE
The prefix for the cache key using files is ignored

### ISSUE THREAD

**Issue by ndurchx** [firecow/gitlab-ci-local#1478]
```yml
---
prepare:frontend-build:
  stage: build
  allow_failure: false
  cache: &npmCache
    key:
      files:
        - package.json
        - package-lock.json
      prefix: prod
    paths:
      - node_modules
    policy: pull-push
  script:
    - echo "Preparing Frontend for building"
    - npm install --omit dev
```

**Expected behavior**
The prefix config is used for cache directories

**Host information**
Ubuntu
gitlab-ci-local 4.57.0

**Containerd binary**
docker

**Additional context**
The cache directories are created with "md-" as prefix to the file checksum, but in this example, it should be "prod-". This works in gitlab runners.
