### ISSUE TITLE
Absolute paths cannot be cached

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#148]

**Comment by bcouetil** [comment]
This is expected in Gitlab Runners.

Or you have a use case for local jobs ?

**Comment by firecow** [comment]
Remote jobs, can have stuff like
```
npm-install
  image: node
  cache:
    key: npm-home
    paths:
      - /root/.npm
    script: npm install --no-audit
```

**Comment by bcouetil** [comment]
When you run that on regular runners you don't get the error `not supported: outside build directory` ? is this new ?

The corresponding feature request seems still open : https://gitlab.com/gitlab-org/gitlab/-/issues/14151

If true this is great, not being force to do this :
```
.front-template:
  image: node:10.16-alpine
  cache:
    key: "npm"
    paths:
      - front/.npm
      - front/node_modules
  before_script:
    - npm config set cache .npm
   ```
