### ISSUE TITLE
Problem with double-quotes in service entrypoint's bash -c arguments

### ISSUE THREAD

**Issue by cknzl2014** [firecow/gitlab-ci-local#1484]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
job1:
  services:
    - name: docker.io/postgres:14.3
      variables:
        POSTGRES_PASSWORD: "postgres"
      entrypoint:
        - "bash"
        - "-c"
        - |
          echo "Hello from postgres container"
          exec docker-entrypoint.sh postgres
  script:
  - echo "Hello"
```

**Expected behavior**
Executed in gitlab, this results in
`Hello from postgres container`
And, of course, the docker-entrypoint.sh should be executed.

But when run in gitlab-ci-local, I get
`Hello`
And the docker-entrypoint.sh is not executed.

When I use single quotes, i.e. `'Hello from postgres container'`, then it works as expected also with gitlab-ci-local.

**Host information**
Ubuntu
gitlab-ci-local 4.57.0

**Containerd binary**
I am using docker.

**Additional context**
Support for CI_DEBUG_SERVICES would be cool :-)
