### ISSUE TITLE
Variables in trigger job includes are not expanded

### ISSUE THREAD

**Issue by frederikschubert** [firecow/gitlab-ci-local#1490]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
.common_trigger:
  stage: triggers
  trigger:
    include:
      - local: $PROJECT_DIR/.gitlab-ci.yml

trigger_project:
  variables:
    PROJECT_DIR: path/to/project
  extends: .common_trigger
```

**Expected behavior**
The variables at [this](https://github.com/firecow/gitlab-ci-local/blob/master/src/job.ts#L1471) line should be expanded using the set of global and job variables.

**Host information**
Ubuntu
gitlab-ci-local 4.57.0

**Containerd binary**
I am using docker.

**Additional context**
