### ISSUE TITLE
Ignore empty services

### ISSUE THREAD

**Issue by ShuP1** [firecow/gitlab-ci-local#1501]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  services:
    - name: "$UNDEFINED"
  script:
    - echo "Heya"
```

**Expected behavior**
https://gitlab.com/to-be-continuous/samples/bash-sample/-/jobs/9136614996#L7
Service name is empty. So GitLab ignores this service.

**Current behavior**
Fail while trying to pull `:latest`

**Host information**
Ubuntu
gitlab-ci-local 4.75.0

**Containerd binary**
WSL and docker

**Additional context**
We are using this GitLab feature in [to-be-continuous](https://gitlab.com/to-be-continuous) to disable the tracking service by default:
```yml
.xxx-base:
  services:
    - name: "$TBC_TRACKING_IMAGE"
      command: ["--service", "xxx", "X.Y.Z"]
```
See https://gitlab.com/groups/to-be-continuous/-/epics/4#note_2083110768
