### ISSUE TITLE
`.gitlab-ci-local` build folder not updating

### ISSUE THREAD

**Issue by andrewvaughan** [firecow/gitlab-ci-local#1506]
# Updated Issue:

Upon further review, it seems the issue isn't that the folder is `/gcl-builds` but rather that this folder is outdated.

I had thought I was getting `File not found` errors due to a poor workspace, but it seems the workspace files, themselves, are out of date.

I checked my `.gitlab-ci-local/builds` directory and it matches what occurs if I do a `ls -alh /gcl-builds` on the container instead of running the `lint` Docker entrypoint. However, this doesn't match my root workspace I'm trying to run the gitlab pipeline on.

It's out of date and doesn't include recent file changes from my workspace - why might this be?

---

# ORIGINAL ISSUE

I am attempting to use the new `GCL_PROJECT_DIR_ON_HOST` to fix a similar pathing issue as #1468 -

My use case is that I am developing within a `devcontainer` (Docker container) and running `gitlab-ci-local` within that. My `lint` test (provided below) deploys another Docker container that shows the `$CI_PROJECT_DIR` path as `/gcl-builds` which is incorrect.

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
testing:
  script:
    - "echo CI_PROJECT_DIR: $CI_PROJECT_DIR"                    # /workspaces/design-system (correct)
    - "echo GCL_PROJECT_DIR_ON_HOST: $GCL_PROJECT_DIR_ON_HOST"  # ...blank?

# Workaround from #1468 - also does not work
#workaround:
#  script:
#    - echo "LOCAL_WORKING_DIR=$PWD" | tee .full-path-on-host-os.env
#  artifacts:
#    reports:
#      dotenv: .full-path-on-host-os.env

##
# @Description Code linting enforcement.
#
# https://megalinter.io/
#
lint:
  stage: test

  # See: https://megalinter.io/flavors/
  image: oxsecurity/megalinter-javascript:v8.4.0

  script: ["true"] # if script: ["true"] doesn't work, you may try ->  script: [ "/bin/bash /entrypoint.sh" ]

  # Overrides of project .mega-linter.yml file.
  #
  # See: # https://megalinter.io/configuration/
  variables:
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR #### <--- ERROR! Points to /gcl-builds in this step, unlike others

    # Validate the entire codebase if this is a merge into `staging` or `production`, otherwise only check changed
    # files in the Merge Request.
    VALIDATE_ALL_CODEBASE: |-
      ( $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "production" )
```

**Expected behavior**
I would expect `GCL_PROJECT_DIR_ON_HOST` to have the `/workspaces/design-system` devcontainer path on the parent container, but it's blank:

```sh
gitlab-ci-local testing
root ➜ /workspaces/design-system (ops/linting) $ gitlab-ci-local testing
parsing and downloads finished in 91 ms.
json schema validated in 136 ms
testing starting shell (test)
testing $ echo CI_PROJECT_DIR: $CI_PROJECT_DIR
testing > CI_PROJECT_DIR: /workspaces/design-system
testing $ echo GCL_PROJECT_DIR_ON_HOST: $GCL_PROJECT_DIR_ON_HOST
testing > GCL_PROJECT_DIR_ON_HOST:
```

(Note that `CI_PROJECT_DIR` is correct here, but is incorrect when I load it inside the `megalinter` image). My presumption is this is where I'm supposed to use `GCL_PROJECT_DIR_ON_HOST`, but the README instructions aren't clear to me. It's also blank on my run, for some reason.

**Host information**

```sh
# GCL version inside of devcontainer
$ gitlab-ci-local --version
4.57.0

# Development Container base
$ cat Dockerfile | grep FROM | head -1
FROM node:23.5-slim AS base

$ uname -a
Linux 23996c85d74d 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 GNU/Linux
```

**Additional context**
