### ISSUE TITLE
.gitlab-ci-local-env VARIABLE gets completely overriden by --variable

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#1508]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
test:
  script:
    - echo $KUBE_CONTEXT
    - echo $KUBECONFIG
    - echo $XDEBUG_MODE
```

```
# .gitlab-ci-local-env
VARIABLE=KUBE_CONTEXT=minikube KUBECONFIG=/root/.kube/config XDEBUG_MODE=develop
```

Run `gitlab-ci-local test --variable XDEBUG_MODE=debug,develop`

**Expected behavior**
I expect this job to print 

![Image](https://github.com/user-attachments/assets/df177352-291c-4393-a1df-ef66d9a25e31)

But it prints 

![Image](https://github.com/user-attachments/assets/8a6fec20-bf0f-4dd7-9416-b848aff861d8)
