### ISSUE TITLE
Cannot use variables from artifacts:reports:dotenv in other job image:name field

### ISSUE THREAD

**Issue by logical-intent** [firecow/gitlab-ci-local#1511]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
# Test with image:name:$dotenv variable
build-image-ref:
  stage: build
  needs: []
  script:
    - echo "BUILD_IMAGE_REF=alpine" > build.env
  artifacts:
    reports: { dotenv: build.env }
use-image-ref:
  stage: deploy
  needs: [build-image-ref]
  image: 
    name: ${BUILD_IMAGE_REF}
  script:
    - if [ "$BUILD_IMAGE_REF" = "" ]; then exit 1; else cat /etc/os-release; fi
```

**Expected behavior**
`image:name` can receive these variables just like `image:` can.

**Host information**
GitLab v17.8

**Additional context**
This is a variant of https://github.com/firecow/gitlab-ci-local/issues/994#issuecomment-1737100856 where the only difference is the use of `image:name` rather than `image:`.  Great work on fixing the original issue!  Would be great if it were consistent though - took me quite a while to figure out it only worked with `image:` and not with `image:name:`. These two approaches should yield the same result so users can add other `image:` properties if required.
