### ISSUE TITLE
Boolean false value on inputs breaks configuration syntax

### ISSUE THREAD

**Issue by aksrpl** [firecow/gitlab-ci-local#1528]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
# .gitlab-ci.yml 
include:
  - local: check.yml
    inputs:
      enabled: false
# check.yml 
spec:
  inputs:
    enabled:
      type: boolean
---
check:
  variables:
    IS_ENABLED: $[[ inputs.enabled ]]
  script: echo "enabled value is $IS_ENABLED"
```

**Expected behavior**
gitlab-ci-local should not report error message: 
"This GitLab CI configuration is invalid: `check.yml`: `enabled` input: required value has not been provided."

**Host information**
MacOS 15.3.2, gitlab-ci-local 4.58.0

**Containerd binary**
Brew

**Additional context**
When inputs.enabled=false is set in `.gitlab-ci.yml` file I get error message: 
"This GitLab CI configuration is invalid: `check.yml`: `enabled` input: required value has not been provided."
When inputs.enabled=true is set in `.gitlab-ci.yml`, everything works as expected.
