### ISSUE TITLE
Jobs with artifacts lead to infinite "still running..." when using podman

### ISSUE THREAD

**Issue by ebousse** [firecow/gitlab-ci-local#1539]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
stages:
  - stage1
  - stage2

task1:
  image: docker.io/library/alpine:latest
  stage: stage1
  script:
    - mkdir -p output
    - echo "hello" > output/artifact
  artifacts:
    paths:
    - output

task2:
  stage: stage2
  image: docker.io/library/alpine:latest
  script:
    - cat output/artifact
```

Note that this problem only happens when `artifacts` are declared.

**Expected behavior**

When running:
```
gitlab-ci-local --container-executable podman
```
I would expect the build to be swift and successful.

However, for an uncanny reason, the build never finishes, and this happen on my system:

```
$ gitlab-ci-local --container-executable podman
Using fallback git commit data
Unable to retrieve default remote branch, falling back to `main`.
Using fallback git remote data
parsing and downloads finished in 48 ms.
json schema validated in 174 ms
task1 starting docker.io/library/alpine:latest (stage1)
task1 copied to podman volumes in 698 ms
task1 $ mkdir -p output
task1 $ echo "hello" > output/artifact
task1 finished in 1.24 s
task1 exported artifacts in 587 ms
task1 copied artifacts to cwd in 50 ms
task2 starting docker.io/library/alpine:latest (stage2)
task2 copied to podman volumes in 567 ms
task1 > still running...
task2 > still running...
task1 > still running...
task2 > still running...
task1 > still running...
task2 > still running...
task1 > still running...
task2 > still running...
task1 > still running...
task2 > still running...
task1 > still running...
task2 > still running...
task1 > still running...
task2 > still running..
…
```

- The problem does not occur with Docker.
- I tried reseting and/or upgrading Podman, but without any change.
- This started happening I don't know exactly when, but gitlab-ci-local worked perfectly fine with Podman for years before this started happening.

**Host information**
Fedora 42

problem observed with:
- gitlab-ci-local 4.58.0
- gitlab-ci-local commit https://github.com/firecow/gitlab-ci-local/commit/530c1861c05ed7aa4293b8a681a1bfeb2531bc93

**Containerd binary**
podman version 5.4.1

**Additional context**

- I investigated my podman configuration, but it seems I am using the recommended configuration (especially for the storage driver)
- I'm using Podman outside gitlab-ci-local without any issues. I even tried reproducing what gitlab-ci-local should do, and I could not find the problem.
