### ISSUE TITLE
**/* not only includes subdirectories

### ISSUE THREAD

**Issue by brussee** [firecow/gitlab-ci-local#1543]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
include:
  - local: "**/*.yml"
```

**Expected behavior**
All .yml files in *subdirectories __only__* are included.

**Host information**
NixOS
gitlab-ci-local 4.53.0

**Containerd binary**
Docker version 27.3.1, build v27.3.1

**Additional context**
Note the difference between:
```yaml
# This matches all `.yml` files in `configs` and any subfolder in it.
include: 'configs/**.yml'

# This matches all `.yml` files only in subfolders of `configs`.
include: 'configs/**/*.yml'
```
Source: https://docs.gitlab.com/ci/yaml/includes/#use-includelocal-with-wildcard-file-paths
