### ISSUE TITLE
"pip install" fails in 4.58.0 but works fine in 4.57.0 and before

### ISSUE THREAD

**Issue by rburhum** [firecow/gitlab-ci-local#1545]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POSTGRES_DB: test_test
  POSTGRES_USER: custom_user
  POSTGRES_PASSWORD: custom_pass
  POSTGRES_HOST_AUTH_METHOD: trust
  RUN_IN_GCLOUD: "False"
  DEBUG: "True"
  DATABASE_URL: "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB"
  SECRET_KEY: "12345"

stages:
  - build

tests:
  stage: build
  image: ubuntu:24.10
  services:
    - postgres:16
  variables:
    DEBIAN_FRONTEND: "noninteractive"
    DEBCONF_NOWARNINGS: "yes"
  
  tags:
    - saas-linux-medium-amd64

  # The cache is a bit deceiving. You do save time when running
  # apt-get install and pip install in our own runner,
  # but whenever the free gitlab runner is used, the cache takes a long time pull and push.
  # By tagging with test-runner, we force the use of our own runner.
  
  cache:
    # cache contents of the pip cache and venv
    - key: python-cache
      paths:
        - .cache/pip
        - venv/
    # cache contents of apt-get
    - key: apt-cache
      paths:
        - apt-cache
  before_script:
    # To aggresively cache apt deb files, we need to make sure the deb packages that are installed are not deleted.
    # Docker images like ubuntu:24.10 usually include a config file that deletes the apt cache after
    # it gets installed. we want to remove this config file. 
    - rm -f /etc/apt/apt.conf.d/docker-clean
  
    # Additionally, gitlab ci only caches folders that are in the home directory, so we need to 
    # copy from the cache (if it exists) to the home directory and in the after_script, copy back to the cache
    - mkdir -p $CI_PROJECT_DIR/apt-cache
    - cp -r $CI_PROJECT_DIR/apt-cache/* /var/cache/apt/archives/ || true

    # we don't need to upgrade (just update) because the base image is at latest and already up to date often
    - apt-get -qq -y -o=Dpkg::Use-Pty=0 update > /dev/null; echo $?
    - apt-get -qq -y -o=Dpkg::Use-Pty=0 install python3 python3-dev python3-pip python3-venv libpq-dev postgresql-client > /dev/null 2>&1; echo $?
    - apt-get -qq -y -o=Dpkg::Use-Pty=0 install build-essential libmagic1 libgmp3-dev git > /dev/null; echo $?
    - python3 -m venv venv; echo $?
    - source venv/bin/activate; echo $?

    # fix permissions for the cache and venv when running in gitlab-ci-local
    - if [ -d ".cache/pip" ]; then chown -R $(whoami) .cache/pip; fi
    - if [ -d "venv" ]; then chown -R $(whoami) venv; fi

    # install the dependencies
    - cd test_screener; echo $?
    
    # fails in the line below
    - pip3 install --no-input -U -r requirements-dev.txt

  script:
    - echo "we dont reach this"

```

**Expected behavior**
It works fine in GitLab and in 4.57.0
This is the log when it doesn't work:
[Paste a public job url.](https://dpaste.com/DKC5FSZ7G)
Basically I get a ``> /gcl-cmd: line 27: /builds/test-consulting/test-screener-backend/venv/bin/pip3: cannot execute: required file not found``

**Host information**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.10
DISTRIB_CODENAME=oracular
DISTRIB_DESCRIPTION="Ubuntu 24.10"
gitlab-ci-local 4.58.0

**Containerd binary**
Using docker

**Additional context**
I had no problems running it locally in previous versions. Just this last version gives problems.
