### ISSUE TITLE
shopt: globstar: invalid shell option name on macOS

### ISSUE THREAD

**Issue by yangm97** [firecow/gitlab-ci-local#1547]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  artifacts:
    paths:
      - build
  script:
    - mkdir build
    - echo "Heya" > build/foo
```

**Expected behavior**
Paste a public job url.

**Host information**
Darwin runner.local 24.4.0 Darwin Kernel Version 24.4.0: Wed Mar 19 21:16:31 PDT 2025; root:xnu-11417.101.15~1/RELEASE_X86_64 x86_64
gitlab-ci-local 4.58.0
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin24)

**Containerd binary**
Are you using docker or podman, or any other relevant containerization tool.

**Additional context**

It seems like this line https://github.com/firecow/gitlab-ci-local/blob/4347267357352beea12aada2aab323d97a6f7be5/src/job.ts#L1228 is tripping on macOS shell executor because Apple insists upon using ancient bash versions.
