### ISSUE TITLE
Can't pass --build-arg with space in string value as environment variable

### ISSUE THREAD

**Issue by pudovd** [firecow/gitlab-ci-local#1550]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
alpine-image:
  services:
    - docker:dind
  needs: []
  image: docker:cli
  stage: build
  variables:
    BUILD_ARGS: --build-arg BUNDLE_WITHOUT="development test"
  script:
    - printenv BUILD_ARGS
    - docker build . $BUILD_ARGS
```

The job failed with:
```
alpine-image $ printenv BUILD_ARGS
alpine-image > --build-arg BUNDLE_WITHOUT="development test"
alpine-image $ docker build . $BUILD_ARGS
alpine-image > ERROR: docker: 'docker buildx build' requires 1 argument
alpine-image > 
alpine-image > Usage:  docker buildx build [OPTIONS] PATH | URL | -
alpine-image > 
alpine-image > Run 'docker buildx build --help' for more information
alpine-image finished in 3.03 s  FAIL 1

 FAIL  alpine-image
  > ERROR: docker: 'docker buildx build' requires 1 argument
  > Usage:  docker buildx build [OPTIONS] PATH | URL | -
  > Run 'docker buildx build --help' for more information
```

**Expected behavior**
```yml
---
alpine-image:
  services:
    - docker:dind
  needs: []
  image: docker:cli
  stage: build
  script:
    - docker build . --build-arg BUNDLE_WITHOUT="development test"
```

The job executed succesfuly:
```
...
alpine-image > #6 DONE 0.0s
alpine-image finished in 16 s

 PASS  alpine-image
```

**Host information**
Ubuntu 24.04.2 LTS
gitlab-ci-local 4.58.0

**Containerd binary**
>Are you using docker or podman, or any other relevant containerization tool

docker

**Additional context**
>Add any other context about the problem here.

No related context. Only thanks for the great tool 💪
