### ISSUE TITLE
The same names for caches with different prefix

### ISSUE THREAD

**Issue by pudovd** [firecow/gitlab-ci-local#1551]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
development-cache:
  image: bash:3.1.23
  script:
    - mkdir -p cached
    - echo "development" > cached/value.txt
  cache:
    paths:
      - cached/
    key:
      prefix: development
      files:
        - Dockerfile

production-cache:
  image: bash:3.1.23
  script:
    - mkdir -p cached
    - echo "production" > cached/value.txt
  cache:
    paths:
      - cached/
    key:
      prefix: production
      files:
        - Dockerfile
```

In the output we can see the same names for caches:
```
...
development-cache exported cache cached/ 'md-a1b640b3cf7a79ac4bae9ed8b0600bc4bd4d336c' in 519 ms
production-cache  exported cache cached/ 'md-a1b640b3cf7a79ac4bae9ed8b0600bc4bd4d336c' in 907 ms
...
```

**Expected behavior**
In the output we should see the different names for caches corresponding the `cache.key.prefix` values:
```
...
development-cache exported cache cached/ 'md-development-a1b640b3cf7a79ac4bae9ed8b0600bc4bd4d336c' in 519 ms
production-cache  exported cache cached/ 'md-production-a1b640b3cf7a79ac4bae9ed8b0600bc4bd4d336c' in 907 ms
...
```

**Host information**
Ubuntu 24.04.2 LTS
gitlab-ci-local 4.58.0

**Containerd binary**
>Are you using docker or podman, or any other relevant containerization tool.

docker

**Additional context**
>Add any other context about the problem here.

No
