### ISSUE TITLE
Self-referential dependency loop

### ISSUE THREAD

**Issue by mathias-mrsn** [firecow/gitlab-ci-local#1553]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
  - docker

[...]

docker:build:
  stage: docker
  dependencies:
    - docker:build
  needs:
    - docker:build

```

**Expected behavior**
Syntax error from `gitlab-ci-local`

**Host information**
ProductName: macOS
ProductVersion: 15.4
BuildVersion: 24E248
gitlab-ci-local 4.58.0

**Containerd binary**
Im using Docker

**Additional context**
Hello.
I encountered a problem today: when a job has its own name listed in its dependencies, the program seems to enter an infinite loop. It's impossible to exit — the process doesn’t terminate, and I have to close my shell. Ctrl+C doesn't work.
