### ISSUE TITLE
Empty rules fallbacks to when never, but gitlab.com fails hard

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#1561]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  rules: []
  script:
    - echo "Heya"
```

**Expected behavior**
I would expect gitlab-ci-local to blow up with an red error message, just like gitlab.com does

````
Unable to create pipeline
job:rules config can't be blank
````
