### ISSUE TITLE
extending  job with referenced variables

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#1562]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
.somevariables:
  variables:
    HESTHEST: ponypony

.something:
  variables: !reference [.somevariables, variables]

test-job:
  extends: [.something]
  variables:
    NICENESS: byrdalos
  script:
    - echo ${NICENESS}
```

**Expected behavior**
I would expect `echo ${NICENESS}` to print "byrdalos"
