### ISSUE TITLE
How to use DinD to build images using gitlab-ci-local

### ISSUE THREAD

**Issue by SvenFlock** [firecow/gitlab-ci-local#1565]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
frontend:
  stage: build
  needs: ["determine_profile"]
  rules:
    - if: $BUILD == "true"
  image: docker:24.0.6-dind-alpine3.18
  services:
    - name: docker:24.0.6-dind
      command: ["--tls=false"]
  before_script:
    - docker info
  script:
    - |
      #!/usr/bin/env sh
      echo "Building for profile: $PROFILE"

      # Normalize branch name to use as part of the image name
      PREFIX=$(echo "$CI_COMMIT_REF_NAME" | sed 's/[^a-zA-Z0-9]/-/g')

      # Define the profile (can be set manually or default to "dev0" or CI variable)
      PROFILE="${PROFILE:-dev0}"  # If PROFILE is not set, default to "dev0"

      # Construct the image name using both PREFIX and PROFILE
      IMAGE_NAME="$CI_REGISTRY_IMAGE/frontend:$PREFIX-$PROFILE"

      echo "Logging into Docker registry"
      echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

      echo "Building image as $IMAGE_NAME"
      docker build -t "$IMAGE_NAME" -f frontend/Dockerfile frontend

      echo "Pushing image to $CI_REGISTRY"
      docker push "$IMAGE_NAME"

      # Optional cleanup
      docker image prune -f --filter "until=24h"
```

**Expected behavior**
This step should work with gitlab-local-ci, too.

**Host information**
macOS
gitlab-ci-local latest version

**Containerd binary**
Orbstack

**Additional context**
I already tried LLM and Google to find a solution but I was not able to.

I have used a local overwrite ".gitlab-ci-local.yml" containing

```yml
---
defaults:
  script: echo "Default script"

frontend:
  services:
    - name: docker:24.0.6-dind
      alias: docker
      command: ["--host=tcp://0.0.0.0:2375", "--tls=false"]
      volumes:
        - unix:///Users/sven/.orbstack/run/docker.sock:/var/run/docker.sock
```

but I am getting the following error when runnint gitlab-ci-local

```bash
 WARN  Avoid overriding predefined variables (​https://gitlab.com/gitlab-org/gitlab/-/blob/v17.7.1-ee/doc/ci/variables/predefined_variables.md?plain=1&ref_type=tags#L15-16​) [GITLAB_USER_LOGIN,CI_REGISTRY,CI_REGISTRY_IMAGE] as it can cause the pipeline to behave unexpectedly.
parsing and downloads finished in 2.04 s.
json schema validated in 106 ms
frontend starting docker:24.0.6-dind-alpine3.18 (build)
frontend pulled docker.io/firecow/gitlab-ci-local-util:latest in 4.66 s
frontend copied to docker volumes in 5.8 s
frontend pulled docker:24.0.6-dind in 1.35 s
frontend started service image: docker:24.0.6-dind with aliases: docker in 389 ms
frontend > still running...
frontend > still running...
frontend > still running...
frontend service image: docker:24.0.6-dind healthcheck failed
frontend   Command failed with exit code 143: docker run --rm --name=gcl-wait-for-it-62066-0-2375 --network 648c2c7d949f2cf5bacce318f35eb27aec7112117a0f27ccd492ea721b00ce8a docker.io/sumina46/wait-for-it docker:2375 -t 30
frontend   Unable to find image 'sumina46/wait-for-it:latest' locally
frontend   latest: Pulling from sumina46/wait-for-it
frontend   c30352492317: Pulling fs layer
frontend   327f35d63e35: Pulling fs layer
frontend   af48a75efc0e: Pulling fs layer
frontend   6dbf8fc40b31: Pulling fs layer
frontend   6dbf8fc40b31: Waiting
frontend   af48a75efc0e: Download complete
frontend   327f35d63e35: Verifying Checksum
frontend   327f35d63e35: Download complete
frontend   c30352492317: Download complete
frontend   c30352492317: Pull complete
frontend   327f35d63e35: Pull complete
frontend   af48a75efc0e: Pull complete
frontend   6dbf8fc40b31: Verifying Checksum
frontend   6dbf8fc40b31: Download complete
frontend   6dbf8fc40b31: Pull complete
frontend   Digest: sha256:d7f14b742f5b83c1bc03c394487c2f672ca776cdc6b3dbc0922e9f9d05e30d39
frontend   Status: Image is up to date for sumina46/wait-for-it:latest
frontend   wait-for-it.sh: waiting 30 seconds for docker:2375
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   wait-for-it.sh: timeout occurred after waiting 30 seconds for docker:2375
frontend also see (.../poc/.gitlab-ci-local/services-output/frontend/docker:24.0.6-dind-0.log)
frontend service image: docker:24.0.6-dind healthcheck failed
frontend   Command failed with exit code 143: docker run --rm --name=gcl-wait-for-it-62066-0-2376 --network 648c2c7d949f2cf5bacce318f35eb27aec7112117a0f27ccd492ea721b00ce8a docker.io/sumina46/wait-for-it docker:2376 -t 30
frontend   Unable to find image 'sumina46/wait-for-it:latest' locally
frontend   latest: Pulling from sumina46/wait-for-it
frontend   c30352492317: Pulling fs layer
frontend   327f35d63e35: Pulling fs layer
frontend   af48a75efc0e: Pulling fs layer
frontend   6dbf8fc40b31: Pulling fs layer
frontend   6dbf8fc40b31: Waiting
frontend   af48a75efc0e: Verifying Checksum
frontend   af48a75efc0e: Download complete
frontend   327f35d63e35: Verifying Checksum
frontend   327f35d63e35: Download complete
frontend   c30352492317: Verifying Checksum
frontend   c30352492317: Download complete
frontend   c30352492317: Pull complete
frontend   327f35d63e35: Pull complete
frontend   af48a75efc0e: Pull complete
frontend   6dbf8fc40b31: Verifying Checksum
frontend   6dbf8fc40b31: Download complete
frontend   6dbf8fc40b31: Pull complete
frontend   Digest: sha256:d7f14b742f5b83c1bc03c394487c2f672ca776cdc6b3dbc0922e9f9d05e30d39
frontend   Status: Downloaded newer image for sumina46/wait-for-it:latest
frontend   wait-for-it.sh: waiting 30 seconds for docker:2376
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   nc: bad address 'docker'
frontend   wait-for-it.sh: timeout occurred after waiting 30 seconds for docker:2376
frontend also see (.../poc/.gitlab-ci-local/services-output/frontend/docker:24.0.6-dind-0.log)
frontend imported artifacts in 36 ms
frontend $ docker info
frontend > Client:
frontend >  Version:    24.0.6
frontend >  Context:    default
frontend >  Debug Mode: false
frontend >  Plugins:
frontend >   buildx: Docker Buildx (Docker Inc.)
frontend >     Version:  v0.11.2
frontend >     Path:     /usr/local/libexec/docker/cli-plugins/docker-buildx
frontend >   compose: Docker Compose (Docker Inc.)
frontend >     Version:  v2.23.0
frontend >     Path:     /usr/local/libexec/docker/cli-plugins/docker-compose
frontend > 
frontend > Server:
frontend > ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
frontend > errors pretty printing info
frontend finished in 42 s  FAIL 1 

 FAIL  frontend
  > Server:
  > ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  > errors pretty printing info
```
