### ISSUE TITLE
"still running..." shows for parallel matrix jobs even though its finished

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#1567]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
testhest:
  parallel:
    matrix:
      - ARCH: amd64
      - ARCH: arm64
  script:
    - echo "NoOp"

test:
  needs: [testhest]
  script:
    - sleep 11
    - echo ""
```

I'm running `gitlab-ci-local` to illustrate the problem

**Expected behavior**
I would only expect a "still running...." message for `test`, but `testhest` matrix jobs also shows the message
