### ISSUE TITLE
artifacts from previous runs are preserved if --no-needs

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#1568]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
test:
  image: debian
  artifacts:
    paths:
      - filename-*
  script:
    - echo "I ran" > filename-$(shuf -i 1-100 -n 1).txt
```

```bash
mjn@mjn-lapdows:~/workspace/mjn-gitlab-ci-debugging$ gitlab-ci-local test
parsing and downloads finished in 52 ms.
json schema validated in 143 ms
test starting debian:latest (test)
test copied to docker volumes in 574 ms
test $ echo "I ran" > filename-$(shuf -i 1-100 -n 1).txt
test finished in 1.15 s
test exported artifacts in 573 ms
test copied artifacts to cwd in 49 ms

 PASS  test
mjn@mjn-lapdows:~/workspace/mjn-gitlab-ci-debugging$ rm filename-*
mjn@mjn-lapdows:~/workspace/mjn-gitlab-ci-debugging$ gitlab-ci-local test
parsing and downloads finished in 47 ms.
json schema validated in 163 ms
test starting debian:latest (test)
test copied to docker volumes in 599 ms
test $ echo "I ran" > filename-$(shuf -i 1-100 -n 1).txt
test finished in 1.27 s
test exported artifacts in 633 ms
test copied artifacts to cwd in 47 ms

 PASS  test
````

Notice how to files are now present in your current working directory.

**Expected behavior**
I would expect `.gitlab-ci-local/artifacts/test/` folder is purged as the job starts.
