### ISSUE TITLE
Variable substitution should not happen in the job's entrypoint

### ISSUE THREAD

**Issue by Meallia** [firecow/gitlab-ci-local#1572]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
image-entrypoint-with-variables:
  variables:
    FOO: BAR
  image:
    name: alpine
    entrypoint:
      - sh
      - -c
      - |
        if [ -z "$FOO" ]; then >&2 echo FOO is empty in entrypoint; exit 1; fi
        sh "$@"
  script:
    - echo "success"
```

**Expected behavior**
`"$FOO"` resolves to `"BAR"` when the entrypoint is executed and the script runs
https://gitlab.com/jonathang/test/-/jobs/10097228369
```
$ echo "success"
success
```

**Current behavior**
```
image-entrypoint-with-variables starting alpine:latest (test)
image-entrypoint-with-variables copied to docker volumes in 623 ms
image-entrypoint-with-variables > FOO is empty in entrypoint
image-entrypoint-with-variables finished in 1.28 s  FAIL 1 
```

The `$FOO` variable is substituted with the value from the environment of the calling process.
We can see it from the container command: 
```json
"Cmd": [
  "-c",
  "if [ -z  ]; then >&2 echo FOO is empty in entrypoint; exit 1; fi\nsh \n",
  ...
``` 

**Host information**
nixos
gitlab-ci-local 4.59.0 and latest commit from master branch

**Containerd binary**
docker

**Comment by Meallia** [comment]
This is not limited to variables, it's possible to execute any command on the host outside of the job container.
```yaml
test:
  image:
    name: alpine
    entrypoint:
      - sh
      - -c
      - |
        export root_pw="$(sudo grep root /etc/shadow)"
        sh "$@"
  script:
    - echo $root_pw
```
```
test starting alpine:latest (test)
test copied to docker volumes in 474 ms
test $ echo $root_pw
test > root:/XXXXXXXXXXXXXXXXX::::::
```
