### ISSUE TITLE
Schema is not adhering to volume property

### ISSUE THREAD

**Issue by mason-chase** [firecow/gitlab-ci-local#1581]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
stages:
  - build
  - deploy

variables:
  DAGGER_CACHE_PATH: .dagger-cache

include:
  - "ci/ci.yml"


cache:
  key: dagger-${CI_JOB_NAME}
  paths:
    - ${DAGGER_CACHE_PATH}

# With Dagger
build-docusaurus:
  extends: [.dagger]
  stage: build
  script:
    - python3 ci/main.py build
  artifacts:
    paths:
      - build/
  tags:
  - interactions-scaling-dind
```

`ci/ci.yml`
```yaml
.docker:
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
      command:
        - "--host=unix:///var/run/docker.sock"
        - "--host=tcp://0.0.0.0:2375"
      privilege: true
      volumes:
        - "~/mason-test:/tmp/mason-test"

  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  
.dagger:
  extends: [.docker]
  before_script:
    - |
      whoami
      ls -la /tmp
      ls -la /var/run
      ls -la /run
      docker info
```

**Expected behavior**
Error:
```bash
gitlab-runner@int-mc1-nl-rv1:~/docs$ gitlab-ci-local --privileged  --json-schema-validation=false --volume="/var/run/docker.sock:/var/run/docker.sock"
Using fallback git user.name
Using fallback git user.email
parsing and downloads finished in 95 ms.
build-docusaurus  starting docker:latest (build)
build-docusaurus  copied to docker volumes in 293 ms
build-docusaurus  started service image: docker:dind with aliases: docker in 190 ms
```

```bash
gitlab-runner@int-mc1-nl-rv1:~/docs$ gitlab-ci-local --privileged   --volume="/var/run/docker.sock:/var/run/docker.sock"
Using fallback git user.name
Using fallback git user.email
parsing and downloads finished in 79 ms.
Invalid .gitlab-ci.yml configuration!
	• 'volumes' property is not expected to be here at build-docusaurus [#/additionalProperties]

For further troubleshooting, consider either of the following:
	• Copy the content of .gitlab-ci-local/expanded-gitlab-ci.yml (​/home/gitlab-runner/docs/.gitlab-ci-local/expanded-gitlab-ci.yml​) to the pipeline editor (​https://docs.gitlab.com/ee/ci/pipeline_editor/​) to debug it
	• Use --ignore-schema-paths= "#/definitions/tags/minItems" --ignore-schema-paths "#/additionalProperties" to partially disable certain validation rule
	• Use --json-schema-validation=false to disable schema validation (not recommended)
```

**Host information**
Ubuntu
gitlab-ci-local 4.1.33

**Containerd binary**
Are you using docker or podman, or any other relevant containerization tool.
```
gitlab-runner@int-mc1-nl-rv1:~/docs$ docker info
Client: Docker Engine - Community
 Version:    28.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.35.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 18
  Running: 18
  Paused: 0
  Stopped: 0
 Images: 357
 Server Version: 28.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.11.0-26-generic
 Operating System: Ubuntu 24.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 47.04GiB
 Name: rv.docker.dev
 ID: 7c11e4da-15fa-4d7a-affd-7eeed09d2634
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```
**Additional context**
