### ISSUE TITLE
when:manual with parallel:matrix

### ISSUE THREAD

**Issue by Winand** [firecow/gitlab-ci-local#1584]
When I run gitlab-ci-local with `--manual deploy_dev` it doesn't start if parallel:matrix is present.
And also parallel jobs run as expected if there's no `when: manual`.

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
  - release
  - deploy

deploy_dev:
  stage: deploy
  when: manual
  parallel:
    matrix:
      - host:
        - host1.com
        - host2.com
  script:
    - echo HELLO $host
```

**Host information**
Windows 10
Docker Desktop 4.36.0
gitlab-ci-local 4.60.1

I run gitlab-ci-local in Docker:
```dockerfile
FROM almalinux:10
RUN dnf install -y gzip rsync git-core 'dnf-command(config-manager)' && \
    dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
    dnf install -y docker-ce-cli && \
    dnf clean all
RUN curl -L https://github.com/firecow/gitlab-ci-local/releases/latest/download/linux.gz | \
        gunzip -c > /usr/local/bin/gitlab-ci-local && \
    chmod +x /usr/local/bin/gitlab-ci-local
WORKDIR /ci
ENTRYPOINT ["gitlab-ci-local", "--shell-executor-no-image=false", \
            "--default-image={a_custom_image:latest}"]
```

gitlab-ci-local run script:
```powershell
docker run --rm -it `
    -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd):/ci" `
    -v "${env:USERPROFILE}/.gitlab-ci-local:/root/.gitlab-ci-local" `
    gitlab-ci-local:latest @args
```
