### ISSUE TITLE
JavaScript heap out of memory when using `include` with local or remote templates

### ISSUE THREAD

**Issue by muuvmuuv** [firecow/gitlab-ci-local#1588]
My configuration somewhat fails when using include with local templates.

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
stages:
  - build

include:
  - local: templates/common.yml

build:
  stage: build
  extends: .workspace
  variables:
    GIT_DEPTH: 0
  script:
    - echo 'Build'
```

`templates/common.yml`:
```yml
.workspace:
  image: debian:12
  before_script:
    - apt-get update -y && apt-get install -yqq git gzip zip xz-utils curl
    - curl -fsSL https://moonrepo.dev/install/proto.sh | PROTO_HOME=$CI_PROJECT_DIR/.cache/proto bash -s -- latest --shell=bash --yes
    - source ~/.bashrc
    - proto install
    - pnpm config set store-dir .cache/pnpm
    - pnpm install
```

**Expected behavior**
Paste a public job url.

**Host information**
macOS 15.5 (24F74)
gitlab-ci-local 4.60.1

**Containerd binary**
Docker Desktop

**Additional context**
