### ISSUE TITLE
Release not created when using keyword

### ISSUE THREAD

**Issue by jsonc0** [firecow/gitlab-ci-local#1589]
When I try to create a release using the release keyword, the job passes but the release is not created in Gitlab. 

```
release                      starting registry.gitlab.com/gitlab-org/release-cli (release)
release                      copied to docker volumes in 1.09 s
release                      imported artifacts in 66 ms
release                      $ echo "Create release v1.0.0"
release                      > Create release v1.0.0
release                      finished in 1.99 s
```

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  image: registry.gitlab.com/gitlab-org/release-cli:v0.24.0
  script:
    - echo "Create release v1.0.0"
  release:
    tag_name: 'v1.0.0'
    description: 'v1.0.0'
```

**Expected behavior**
Release is created

**Host information**
macOS 13.7.3 
gitlab-ci-local 4.59.0

**Containerd binary**
docker

**Additional context**
I've set `GITLAB_PRIVATE_TOKEN`within `.gitlab-ci-local-variables.yml` and I'm able to create a release with the following.

```yml
---
job:
  image: registry.gitlab.com/gitlab-org/release-cli:v0.24.0
  script:
    - release-cli create --tag-name v1.0.0 --description v1.0.0
```
