### ISSUE TITLE
Including YAML from another project with file starting with / fails

### ISSUE THREAD

**Issue by icedream** [firecow/gitlab-ci-local#190]
Example:

```yaml
include:
    - project: example/repository
      ref: master
      file: /template.yml
```

While defining paths starting with `/` is valid in GitLab and will work, [this `git archive` call done to download the included YAML](https://github.com/firecow/gitlab-ci-local/blob/10671d3ec34a20275b565264c91054f999e4adc8/src/parser.ts#L358) fails due to this since it considers the path outside the repository.
