### ISSUE TITLE
parallel.matrix

### ISSUE THREAD

**Issue by jeppenodgaard** [firecow/gitlab-ci-local#205]
Example of [one dimenstional parallel](https://docs.gitlab.com/ee/ci/yaml/README.html#one-dimensional-matrix-jobs) feature:
```
test:
  script:
    - echo "NAME=${NAME}"
  parallel:
    matrix:
      - NAME: [foo, bar]
```

Output of example. Runs once and the value is unset:
```
test         rsynced to build folder in 139 ms
test         starting shell (test)
test         copied artifacts to cwd in 56 ms
test         $ echo "NAME=${NAME}"
test         > NAME=
test         finished in 225 ms
```
