### ISSUE TITLE
How to configure volumes for docker in docker?

### ISSUE THREAD

**Issue by Rush** [firecow/gitlab-ci-local#208]
Hi there! Great project!

I need to bind `/var/run/docker.sock:/var/run/docker.sock`  as a volume but I can't find anything in the documentation. Is there some config for it?

**Comment by moberghammer** [comment]
Which remote gitlab pipeline feature do you want to mimic by mounting Docker sock?

**Comment by Rush** [comment]
it's about Docker in Docker. Gitlab runners can be configures as such:
```
  [runners.docker]
    volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
```

this allows to build an image from within a Gitlab CI pipeline:
```
build-image:
  stage: prepare
  image: docker:stable
  script:
    - cd docker/ci
    - docker build -t nexus-build-$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA .
```
