### ISSUE TITLE
Running while using a GitLab template include fails.

### ISSUE THREAD

**Issue by jamesmeneghello** [firecow/gitlab-ci-local#211]
Minimal `.gitlab-ci.yml`:

```yaml

image: node:16.1

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - install

install:
  stage: install
  script:
      - apt install -y curl
      - curl -fsSL https://get.pulumi.com | sh
      - yarn
```

Running `gitlab-ci-local install` results in:

```
TypeError: undefined is not a function
    at Function.prepareIncludes (/snapshot/gitlab-ci-local/src/parser.ts:379:39)
    at Function.prepareIncludes (/snapshot/gitlab-ci-local/src/parser.ts:425:65)
    at Parser.init (/snapshot/gitlab-ci-local/src/parser.ts:225:44)
    at Function.create (/snapshot/gitlab-ci-local/src/parser.ts:54:9)
    at Object.handler (/snapshot/gitlab-ci-local/src/handler.ts:92:18)
    at Object.handler (/snapshot/gitlab-ci-local/src/index.ts:36:34)
```

Looks like it's because it generates a bad directory structure as part of the include: `.gitlab-ci-local/includes/gitlab.com/gitlab-org/-` (can't go below `-`, because `cd -` takes me up a level).
