### ISSUE TITLE
Variables can't be composed/interpolated anymore, diverges from gitlab-ci

### ISSUE THREAD

**Issue by pcuci** [firecow/gitlab-ci-local#227]
For the following code, the behavior differs in -local vs. ci.

```
variables:
  registry: '${QUAY_REGISTRY}'

...
build:
  stage: build
  script:
    - echo ${QUAY_REGISTRY}
    - echo ${registry}
```

In gitlab-ci:

```
$ echo ${QUAY_REGISTRY}
quay.ubisoft.com
$ echo ${registry}
quay.ubisoft.com
```

In gitlab-ci-local:

```
build       $ echo ${QUAY_REGISTRY}
build       > quay.ubisoft.com
build       $ echo ${registry}
build       > ${QUAY_REGISTRY}
```

Please advise, this looks like a regression with latest.

```
$ npm list -g | grep gitlab
├── gitlab-ci-local@4.23.1
```
