### ISSUE TITLE
Multilevel !reference involving lists/arrays (script, after_script etc. etc.)

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#231]
Works on remote, do not work in gitlab-ci-local
```yml
.base:
  script:
    - ls -all

.parent:
  script:
    - !reference [.base, script]
    - pwd

child:
  stage: test
  image: alpine
  script:
    - !reference [.parent, script]
    - echo "Heya"

```
