### ISSUE TITLE
YAML anchors do not work

### ISSUE THREAD

**Issue by atli-c** [firecow/gitlab-ci-local#24]
I get error from bash ("[object: command not found") when I try to use YAML anchors with gitlab-ci-local.

Steps/files to reproduce: 

With `.gitlab-ci.yml`:
```YML
stages: [test]
main:
  stage: test
  script: echo Demonstration
```
and `.gitlab-ci-local.yml`:
```YML
.example: &test_anchor
  echo 'Example'
demo:
  stage: test
  script:
    - echo 'Hello'
    - *test_anchor
    - echo 'Goodbye'
```

Expected output when running `gitlab-ci-local demo`:
> demo  starting...
> demo  $ echo 'Hello'
> demo  > Hello
> demo  $ echo 'Example'
> demo  > Example
> demo  $ echo 'Goodbye'
> demo  > Goodbye
> demo  finished in 24 ms

Actual output:
> demo  starting...
> demo  $ echo 'Hello'
> demo  > Hello
> demo  $ [object Object]
> demo  > bash: line 2: [object: command not found
> demo  finished in 25 ms exited with code 127

YAML syntax is OK. I checked with [python-yq](https://pypi.org/project/yq/)
Output from `yq -Y .demo .gitlab-ci-local.yml`:
> stage: test
> script:
>   - echo 'Hello'
>   - echo 'Example'
>   - echo 'Goodbye'
