### ISSUE TITLE
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

### ISSUE THREAD

**Issue by baizsof** [firecow/gitlab-ci-local#240]
Hello, 

First of all, excuse me if this is not the right place to ask questions. 

I tried to use your tool downloaded into debian:buster image to build a project in that "build environment" and I stumbled into an issue.

One of my gitlab-ci stage executes a shell that tries to use host's Docker daemon. I attached `-v /var/run/docker.sock:/var/run/docker.sock` to the build container, inside the build container docker cli can be called, but when the stage that contains the aforementioned shell that tries to build images, I got the following error. 

`Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

My question would be, does your tool support calling docker daemon via docker.sock? If so, how it can be accomplished?

Here is my build environment dockerfile. 

```
FROM debian:buster

RUN apt-get update
RUN apt --yes install net-tools
RUN apt --yes --no-install-recommends install apt-utils
RUN apt --yes --no-install-recommends install apt-transport-https ca-certificates curl gnupg2 software-properties-common xz-utils apt git rsync
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN echo 'deb https://download.docker.com/linux/debian buster stable' >> /etc/apt/sources.list
RUN apt --yes --no-install-recommends install docker-ce docker-ce-cli containerd.io
RUN curl -L "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m)" --output /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose
RUN curl -L https://github.com/firecow/gitlab-ci-local/releases/latest/download/linux.gz | gunzip -c > /usr/local/bin/gitlab-ci-local
RUN chmod +x /usr/local/bin/gitlab-ci-local

WORKDIR /opt/build

COPY src/ .

CMD gitlab-ci-local --manual build-docker-foo
```

How I build/run the build-env 
```
docker build -t gitlab-build-env:test -f gitlab-build-env-dockerfile .  

docker run -it --rm  -v /var/run/docker.sock:/var/run/docker.sock gitlab-build-env:test
```

**Comment by firecow** [comment]
It definently supports using `/var/run/docker.sock` in fact its required, to use the `service:` or `image:` fields

I'll try out your Dockerfile and docker run command later, and return with a answer. @baizsof 

And yes, this is the right place to ask a question :smile:

**Comment by baizsof** [comment]
Thank you for the fast reply. 

I rather looking for a solution than an exact fix for the mentioned dockerfile. Feel free to rip it apart. :)  

I can copy some part of our gitlab-ci.yaml.  Below mentioned, `build.sh` tries to execute docker build commands. 

```
build-docker-foo:
  image: debian:buster
  services:
    - name: docker:18.09-dind
      command:
        - /bin/sh
        - -c
        - echo "$CA_CERTIFICATE" | base64 -d > /usr/local/share/ca-certificates/my-ca.crt && mkdir -p /etc/docker/certs.d/repo.foo && echo "$CLIENT_CERT" | base64 -d > /etc/docker/certs.d/repo.foo/client.cert && echo "$CLIENT_KEY" | base64 -d > /etc/docker/certs.d/repo.foo/client.key && update-ca-certificates && dockerd-entrypoint.sh || exit
		
  variables:
    #some vars 
	
  tags:
    - docker

  stage: docker-foo

  dependencies:
    - build-foo

  script:
    - mkdir -p images
    - chmod +x Docker/*.sh
    - Docker/provision.sh
    - Docker/build.sh

  when: manual

  artifacts:
    name: "foo-${DEVELOP_BUILD_VERSION}"
    paths:
      #some artifacts
    expire_in: 1 hour
```
