### ISSUE TITLE
Question: fetch raw files from private Gitlab instances is possible ?

### ISSUE THREAD

**Issue by Neonox31** [firecow/gitlab-ci-local#244]
First, thanks for this amazing tool 👍

I'm trying to get gitlab-ci-local working with a private Gitlab instance from my company and it results with `Project include could not be fetched` error.
Looking at the code reveals that no private token are handled as an header to fetch raw files and I presume this is the problem, am I right ? Maybe I missed a thing ?

Thanks.

**Comment by firecow** [comment]
Hmmm... How does your include field look? @Neonox31

**Comment by Neonox31** [comment]
@firecow here is the include section :
```
include:
  project: "factory/ci-centre/ci-helpers"
  file: "/templates/.gitlab-ci-tpl.yml"
  ref: "2.10.0"
```
`factory` is a group at top level of our Gitlab self-hosted instance and because project are not publicly visible we need to use a personal token to access them.
I'm thinking of an environment variable that could contain the token and that would be injected in the node-fetch headers when it is set, what do you think ?

**Comment by firecow** [comment]
Ahaa.... That should be doable, what would be a good name constant for such an access token...

**Comment by Neonox31** [comment]
What do you thin of `GCIL_TOKEN` alias Gitlab C.I Local Token ?

**Comment by firecow** [comment]
Hmmm.... I just realized @Neonox31 
```
include:
  project: "factory/ci-centre/ci-helpers"
  file: "/templates/.gitlab-ci-tpl.yml"
  ref: "2.10.0"
```
Are fetched via `git archive` which use ssh private key as authentication method.
Are you sure, that you have ssh access to that project ?
