### ISSUE TITLE
Permission denied error with file operation in service command

### ISSUE THREAD

**Issue by ghillb** [firecow/gitlab-ci-local#248]
Hello! The `.gitlab-ci.yml` below works on `gitlab.com`, but not with `gitlab-ci-local`. I'm not sure if its a misconfiguration on my side or a bug.

```
stages:
  - build

.dind-service: &dind-service
  name: docker:20.10.7-dind
  command:
    - /bin/sh
    - -c
    - echo "$CA_CERT" > /usr/local/share/ca-certificates/ca.crt || exit

build-app-image:
  stage: build
  image: docker
  services:
    - *dind-service
  script:
    - echo "bar"
```

It throws the following error:
```
bash: line 1: /usr/local/share/ca-certificates/ca.crt: Permission denied
```
Content of `$HOME/.gitlab-ci-local/variables.yml`:

```
---
global:
group:
project:
  gitlab.com:ghillb/gitlab-ci-local-issue.git:
    CA_CERT: foo
```
Observed behavior:
![Screenshot 2021-09-28 184431](https://user-images.githubusercontent.com/35503959/135130374-a583e9f5-f3dc-455f-a568-711a79defd8c.png)

Expected behavior:
https://gitlab.com/ghillb/gitlab-ci-local-issue/-/jobs/1623422499

**Comment by firecow** [comment]
@ghillb 
https://gitlab.com/ghillb/gitlab-ci-local-issue/-/jobs/1623422499

```
*** WARNING: Service runner-72989761-project-29912125-concurrent-0-02917e66433ae32e-docker-0 probably didn't start properly.
Health check error:
service "runner-72989761-project-29912125-concurrent-0-02917e66433ae32e-docker-0-wait-for-service" timeout
Health check container logs:
Service container logs:
*********
```

You sure the service isn't just failing silently in the background here, with a error message similar to what gitlab-ci-local is reporting ?

**Comment by ghillb** [comment]
This got me thinking, so I changed
```
 - echo "$CA_CERT" > /usr/local/share/ca-certificates/ca.crt || exit
```
to
```
- echo "$CA_CERT" > ./ca.crt || exit
```
which makes the job pass in `gitlab-ci-local`:
![Screenshot 2021-09-28 184431](https://user-images.githubusercontent.com/35503959/135149800-3372cc32-2e2c-4a09-a18d-f68cf3454461.png)
and also on [gitlab.com](https://gitlab.com/ghillb/gitlab-ci-local-issue/-/jobs/1631187342), but also yields the same warning on gitlab.com.

Could it be that `gitlab-ci-local` executes the command on the host and not within the service container?

**Comment by firecow** [comment]
@ghillb Please narrow this down to an as small as possible `.gitlab-ci.yml` and a corresponding public job url?

**Comment by ghillb** [comment]
This is the minimal `.gitlab-ci.yml`:
```
stages:
  - build

build-app-image:
  stage: build
  image: alpine
  services:
    - name: docker:20.10.7-dind
      command: [ "/bin/sh", "-c", "echo foo > /foo.txt" ]
  script:
    - echo bar
```
[public job url](https://gitlab.com/ghillb/gitlab-ci-local-issue/-/jobs/1633547673)
