### ISSUE TITLE
artifacts.reports.dotenv

### ISSUE THREAD

**Issue by ck-trigfb** [firecow/gitlab-ci-local#250]
As explained here (https://docs.gitlab.com/ee/ci/variables/#pass-an-environment-variable-to-another-job) it is possible to pass a dotenv varible as an artifact from one job to another one.

But it either works with dependencies nor with needs syntax. Example of gitlab website:
```
build:
  stage: build
  script:
    - echo "BUILD_VERSION=hello" >> build.env
  artifacts:
    reports:
      dotenv: build.env

deploy:
  stage: deploy
  script:
    - echo "$BUILD_VERSION"  # Output is: 'hello'
  dependencies:
    - build
```
