### ISSUE TITLE
jobs with when:never can be considered as a artifacts producer.

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#253]
```yml
---
build:
  stage: build
  rules:
    - when: never
  artifacts:
    paths:
      - node_modules.txt
  script:
    - echo "Generate node_modules" > node_modules.txt

deploy:
  stage: deploy
  script:
    - echo "Getting artifacts from all producers"
```

```shell
gitlab-ci-local --cwd tests/test-cases/artifacts-shell/ --file .gitlab-ci-when-never.yml --shell-isolation
parsing and downloads finished in 51 ms
deploy starting shell (deploy)
tests/test-cases/artifacts-shell/.gitlab-ci-local/artifacts/build doesn't exist, did you forget --needs
```
