### ISSUE TITLE
--preview doesn't expand variable values

### ISSUE THREAD

**Issue by atli-c** [firecow/gitlab-ci-local#254]
Add support for: https://docs.gitlab.com/ee/ci/variables/#use-variables-in-other-variables

**Comment by atli-c** [comment]
I made a mistake. I thought that this wasn't supported because I didn't see what I expected from `gitlab-ci-local --preview`. I can see that it is in fact supported when running jobs.

**Comment by atli-c** [comment]
Feature request: `gitlab-ci-local --preview` should show variable values when possible.

A possible solution: show value in YAML comment.  
Job in .gitlab-ci.yml file:
```YAML
job:
  variables:
    FLAGS: '-al'
    LS_CMD: 'ls "$FLAGS" $$TMP_DIR'
```
Output from `gitlab-ci-local --preview`
```YAML
---
job:
  variables:
    FLAGS: '-al'
    LS_CMD: 'ls "$FLAGS" $$TMP_DIR' # ls "-al" $TMP_DIR
```
