### ISSUE TITLE
needs should fully contain dependencies

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#270]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  needs: [one]
  dependencies: [two]
  script:
    - echo "Should fail during parsing and never get to this script"
```

**Expected behavior**
Error should be printed that `dependencies:` is not fully contained by `needs:`

**Host information**
Ubuntu 20.04
gitlab-ci-local 4.25.0
