### ISSUE TITLE
rules evaluation does not support regex modifiers like case insensitivity

### ISSUE THREAD

**Issue by aepfli** [firecow/gitlab-ci-local#273]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - echo "Heya"
   rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release.*$/i' #does not work
    - if: '$CI_COMMIT_BRANCH =~ /^release.*$/' #works
```

**Expected behavior**
I would expect that i can also provide general regex modifiers - eg. case-insensitivity is something which might be useful.

**Host information**
Ubuntu
gitlab-ci-local 4.25.0

**Additional context**

```
ReferenceError: nulli is not defined
    at eval (eval at evaluateRuleIf (/snapshot/gitlab-ci-local/src/utils.ts:169:16), <anonymous>:1:38)
    at Function.evaluateRuleIf (/snapshot/gitlab-ci-local/src/utils.ts:169:16)
    at Function.getRulesResult (/snapshot/gitlab-ci-local/src/utils.ts:120:23)
    at new Job (/snapshot/gitlab-ci-local/src/job.ts:135:38)
    at /snapshot/gitlab-ci-local/src/parser.ts:280:25
    at Function.forEachRealJob (/snapshot/gitlab-ci-local/src/utils.ts:62:13)
    at Parser.init (/snapshot/gitlab-ci-local/src/parser.ts:276:15)
    at Function.create (/snapshot/gitlab-ci-local/src/parser.ts:54:9)
    at handler (/snapshot/gitlab-ci-local/src/handler.ts:84:18)
    at Object.handler (/snapshot/gitlab-ci-local/src/index.ts:25:34)
```
