### ISSUE TITLE
Implement cache: with proper push/pull to fix bug with caching in --shell-isolation

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#282]
Implement proper cache syncing, instead of utilizing docker volume mounts.

Basicly copy files out if `policy:` is push-pull and copy files in if `policy:` is pull or push-pull.

Also implement globstar support while at it.

```yml
---
produce-cache:
  stage: build
  cache:
    key: global
    paths: [cache/**.txt]
  script: mkdir -p cache && touch cache/file1.txt

consume-cache:
  stage: test
  needs: [produce-cache]
  dependencies: [produce-cache]
  cache:
    key: global
    paths: [cache]
    policy: pull
  script: test -f cache/file1.txt
```

Remember to test for `Not uploading cache global due to policy` line...

**Comment by firecow** [comment]
Heres a npm-install with 2460 packages taken from a nuxtjs example

```yml
# @Description Install node_modules
npm-install:
  cache:
    - { key: npm-cache, paths: [.npm] }
    - { key: { files: [package-lock.json] }, paths: [node_modules] }
  script: npm install --cache .npm --no-audit --no-progess --no-fund --no-update-notifier
 ```

#### Current
- added 2460 packages from 1091 contributors
  - 30s
- up to date
  - 8.58s

#### New
- added 2460 packages from 1091 contributors
  - 38s
- up to date in 
  - 13s
  
I would deem this rather small performance hit, totally acceptable, when considering the major upsides in debuggin, we get with this change.
I've seen file conflicts and busy file errors `/tmp/gitlab-ci-local`, when multiple jobs utilizes the cache at the same time.

@bcouetil
