### ISSUE TITLE
Error: "/gcl-scripts/" could not be found on container with docker-type runner

### ISSUE THREAD

**Issue by ben-alkov** [firecow/gitlab-ci-local#298]
docker-type runner errors out with
```sh
gitlab-ci-local
parsing and downloads finished in 57 ms
uname starting registry.fedoraproject.org/fedora:34 (do_stuff)
uname pulled registry.fedoraproject.org/fedora:34 in 231 ms
uname copied to container in 365 ms
Error: "/gcl-scripts/" could not be found on container 4615c86204aa0eaecb04a4746a644ff1d6eca4c4255b18650068370949f87079: No suchfile or directory
```

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
uname:
  image: registry.fedoraproject.org/fedora:34
  script:
    - uname -a
```

**Expected behavior**
No *public* url available.

**Host information**
Fedora 34
gitlab-ci-local 4.26.0

**Additional context**
I can't get e.g. `gitlab-runner exec docker uname` to work, as 'gitlab-runner' *requires* (seems to?) a "served" git repo to pull from (i.e. it ignores CWD, saying "fatal: 'FOO' does not appear to be a git repository. fatal: Could not read from remote repository").

Providing the actual upstream repo URL (using `--clone-url`) doesn't work due to cert issues (and neither `--docker-tlsverify=no` nor `variables: GIT_SSL_NO_VERIFY: "true"` in '.gitlabc-ci.yml' make any difference), which I'm pretty sure I have no hope of figuring out... which is why I'm here :)

**Comment by firecow** [comment]
```yml
---
uname:
  image: debian:stable-slim
  script:
    - uname -a
```
@ben-alkov 
Put this in a `.gitlab.yml` and run `gitlab-ci-local`
Paste the output here.
