### ISSUE TITLE
Undefined variables regex matching fails when used with &&

### ISSUE THREAD

**Issue by hwo411** [firecow/gitlab-ci-local#299]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
test:
  rules:
    - if: true && $ASD =~ /123/
  script:
    - echo 1
```

It results into 
TypeError: Cannot read properties of null (reading 'match')

**Expected behavior**
No error is thrown

**Host information**
Ubuntu 21.04 WSL 2
gitlab-ci-local 4.26.0

**Additional context**
The variable expression is expanded to `true && null.match(/123/) != null`

If I remove `true &&`, it's evaluated into `false`

I believe that A =~ B should expand to (A != null && A.match(B) != null) in all cases
