### ISSUE TITLE
rules/if fails is both arguments of =~ are strings

### ISSUE THREAD

**Issue by hwo411** [firecow/gitlab-ci-local#300]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
test:
  rules:
    - if: $CI_MERGE_REQUEST_IID && (($CI_COMMIT_MESSAGE =~ /ci-skip-job-/ && $CI_JOB_NAME =~ $CI_COMMIT_MESSAGE) || ($CI_COMMIT_MESSAGE =~ /ci-skip-stage-/ && $CI_JOB_STAGE =~ $CI_COMMIT_MESSAGE))
  script:
    - echo 1
```

It results into `SyntaxError: Invalid or unexpected token`

**Expected behavior**
No error is thrown

**Host information**
Ubuntu 21.04 WSL 2
gitlab-ci-local 4.26.0

**Additional context**
If clause expands to
```
false && (('Commit Title
More commit text'.match(/ci-skip-job-/) != null && 'test' =~ 'Commit Title
More commit text') || ('Commit Title
More commit text'.match(/ci-skip-stage-/) != null && 'test' =~ 'Commit Title
More commit text'))
```

**Update:** The problem is that second =~ is not converted to a code, because both arguments are strings. However, it's a valid syntax in gitlab (it matches substring in string). We use it as a workaround for issue https://gitlab.com/gitlab-org/gitlab/-/issues/25138

Reference comment for this solution: https://gitlab.com/gitlab-org/gitlab/-/issues/35438#note_381577585
