### ISSUE TITLE
!reference breaks if the "parent" isn't defined first

### ISSUE THREAD

**Issue by niki9796dk** [firecow/gitlab-ci-local#306]
**Minimal .gitlab-ci.yml illustrating the issue**
Does not work:
```yml
---
parent:
  script:
    - !reference [ .child, script ]

.child:
  script:
    - echo 'Mads'
    - !reference [ .grandchild, script ]

.grandchild:
  script:
    - echo 'Jon'
```

Works:
```yml
---
.grandchild:
  script:
    - echo 'Jon'

.child:
  script:
    - echo 'Mads'
    - !reference [ .grandchild, script ]

parent:
  script:
    - !reference [ .child, script ]
```

**Output**
```
TypeError: script.split is not a function
    at /snapshot/gitlab-ci-local/src/job.ts:399:34
    at Array.forEach (<anonymous>)
    at Job.generateScriptCommands (/snapshot/gitlab-ci-local/src/job.ts:397:17)
    at Job.execScripts (/snapshot/gitlab-ci-local/src/job.ts:549:21)
    at Job.start (/snapshot/gitlab-ci-local/src/job.ts:290:36)
```

**Expected behavior**
The `parent` job should execute.

**Host information**
Ubuntu 20.04.2 LTS
gitlab-ci-local 4.26.0

**Additional context**
