### ISSUE TITLE
cache: without key fails

### ISSUE THREAD

**Issue by GoldraK** [firecow/gitlab-ci-local#313]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
test:
  stage: test
  # Select what we should cache
  cache:
    paths:
     - vendor/
  services:
    - mysql:5.7
  image: php:8.0.0
  artifacts:
    reports:
      junit: phpunit-report.xml
      
  before_script:
  # Install git, zip, the php image doesn't have installed
  - apt-get update -yqq
  - apt-get install git -yqq
  - apt-get install zip unzip libzip-dev -yqq

  # Install mysql driver
  - docker-php-ext-install pdo_mysql

  #Install Zip
  - docker-php-ext-install zip

  #Enable Sockets
  - docker-php-ext-install sockets

  # Install Xdebug
  - pecl install xdebug
  
  # Enable Xdebug
  - docker-php-ext-enable xdebug  

  # Install composer
  - curl -sS https://getcomposer.org/installer | php

  # Install all project dependencies
  - php composer.phar install

  - chown -R 33:33 files

  script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never --log-junit phpunit-report.xml
```

**Host information**
Ubuntu
gitlab-ci-local 4.26.3

**Additional context**
Hello,
I have installed the latest version from the apt repository and from npm and in both cases it gives me the same error.

When I launch to run the CI it starts the services and then tells me that it cannot read files

Thanks for the help.

![imagen](https://user-images.githubusercontent.com/1814307/142034485-5655a029-b7dc-43ab-a2cb-7cfb28462e0d.png)

**Comment by firecow** [comment]
```yml
---
test-job:
  cache:
    paths:
      - vendor/
  script:
    - echo "Test-job"
```

Here is a smaller test `.gitlab-ci.yml`

Isn't cache.key required ? Or am I miss reading https://docs.gitlab.com/ee/ci/yaml/ ?

**Comment by firecow** [comment]
Oh, gitlab-ci just uses default, when a key isn't set. We shall do the same..

**Comment by GoldraK** [comment]
Hello,
I have added a key to the cache as you say and it keeps giving me the same error.

```yml
test:
  stage: test
  # Select what we should cache
  cache:
    keys: vendor-cache
    paths:
     - vendor/
```


I have tried the gitlab-ci.yml that you left as an example and without a key in the cache it works perfectly.
