### ISSUE TITLE
Services:entrypoint wrong assertation

### ISSUE THREAD

**Issue by alexander-bzikadze-rakuten** [firecow/gitlab-ci-local#315]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
  - testg
test: 
  image: tutum/dnsutils
  script: 
    - sleep 1
  services: 
    - entrypoint: ["redis"]
      name: "redis"
  stage: testg

```

**Expected behavior**
Entrypoint accepted, got `services:entrypoint must be an array` instead

**Host information**
MacOS 10.15.7
gitlab-ci-local 4.26.3

**Additional context**
I believe assert in [service.ts](https://github.com/firecow/gitlab-ci-local/blob/master/src/service.ts#L21) should be reverted.
