### ISSUE TITLE
extends:[] limited to single level

### ISSUE THREAD

**Issue by atli-c** [firecow/gitlab-ci-local#33]
Support for `extends` is limited to a single level.

Steps to reproduce:
```YAML
.base-demo:
    before_script: [echo "Demonstration"]
demo-extend-1:
    extends: [ .base-demo ]
    script: echo "This is '$CI_JOB_NAME' on GITLAB_CI='$GITLAB_CI'"
demo-extend-2:
    extends: [ demo-extend-1 ]
    variables:
        FOO: BAR
```

Expected output from "demo-extend-2":
> Demonstration
> This is 'demo-extend-2' on GITLAB_CI='false'

Actual output:
> This is 'demo-extend-2' on GITLAB_CI='false'
