### ISSUE TITLE
Enviroment specific variables in home variables files and project variables files

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#343]
```yml
--- # $CWD/.gitlab-ci-local-variables.yml or $HOME/.gitlab-ci-local/variables.yml
SOMEVARIABLE: 
  *stage*: 'the calm before the storm'
  *prod*: 'I'm da bomb'
```

```yml 
--- # .gitlab-ci.yml
deploy-prod:
  environment: prod
  script: echo ${SOMEVARIABLE} # Prints 'I'm da bomb'
  
deploy-stage:
  environment: stage
  script: echo ${SOMEVARIABLE} # Prints 'the calm before the storm'
```
