### ISSUE TITLE
Artifact handling is broken

### ISSUE THREAD

**Issue by DrRuhe** [firecow/gitlab-ci-local#345]
**.gitlab-ci.yml with 4 artifact related bugs:**
```yml
stages:
  - test

# does not copy text.txt into .gitlab-ci-local/artifacts/*
# text lands in cwd instead
# but this is docker container, so it should not do that?
test1:
  image:
    name: alpine
    entrypoint: [""]
  stage: test
  artifacts:
    paths:
      - test.txt
  script:
    - echo Lorem ipsum dolor sit amet > test.txt
    - cat test.txt

# still copies files into cwd, even with decorator

# @NoArtifactsToSource
test2:
  image:
    name: alpine
    entrypoint: [""]
  stage: test
  artifacts:
    paths:
      - test.txt
  script:
    - echo Lorem ipsum dolor sit amet > test.txt
    - cat test.txt


# throws TypeError
test3:
  image:
    name: alpine
    entrypoint: [""]
  stage: test
  artifacts:
    - test.txt
  script:
    - echo Lorem ipsum dolor sit amet > test.txt
    - cat test.txt

# also throws TypeError
test4:
  image:
    name: alpine
    entrypoint: [""]
  stage: test
  artifacts:
    paths:
      - test.txt
  script:
    - echo Lorem ipsum dolor sit amet > test.txt
    - cat test.txt
```

**Host information**
Manjaro
gitlab-ci-local 4.13 (I know its old version but its 2am and node apparently doesn't want to upgrade :/)
