### ISSUE TITLE
Error in substitution when rules contains a regex with a eol-match

### ISSUE THREAD

**Issue by d-schiffner** [firecow/gitlab-ci-local#350]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /master$/
  script:
    - echo "Heya"
```

**Expected behavior**
The job should be executed if on the master branch

**Host information**
Ubuntu
gitlab-ci-local 4.28.0

**Additional context**
I traced down the issue to the `null` substitution in `utils.ts` in the evaluateRuleIf function: https://github.com/firecow/gitlab-ci-local/blob/master/src/utils.ts#L131

The regex substitution currently uses `\w*` which can be empty, so a single $ will be replaced with null. Changing the expression to `\w+` should fix the issue
