### ISSUE TITLE
artifacts cause `when: always` to fail when it should not

### ISSUE THREAD

**Issue by bevrist** [firecow/gitlab-ci-local#358]
When a previous stage that generates artifacts fails, a later stage with `when: always` also fails to start (the stage should start anyway).  

```yml
---
stages:
  - first
  - second
  - final

job1:
  stage: first
  script:
    - echo "some output" > output1.log
  artifacts:
    paths:
      - output1.log

job2:
  stage: second
  script:
    - exit 1
  artifacts:
    paths:
      - a-file-that-didnt-get-created.txt

job3: # this one should run anyway but fails due to stage2 artifacts missing
  when: always
  script:
    - echo "hello there"
```

**Expected behavior**  
In a real gitlab CI instance the `when: always` stage will always run with whatever artifacts are available.  

This is useful for having a cleanup stage that always runs at the end of a pipeline, e.g. for cleaning up external resources.  

Implementing a decorator such as `# @DontUseArtifacts` could be a simple workaround for this issue.  

**Host information**  
CentOS 7  
gitlab-ci-local 4.1.33  

**Additional context**  
Using docker runner.
