### ISSUE TITLE
`include:template:` field

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#37]

**Comment by mjrider** [comment]
i"m hitting this issue, because i use merge requests pipelines.
https://docs.gitlab.com/13.8/ee/ci/yaml/#workflowrules-templates
a partial implementation could be that when the template value is one of the documented values of gitlab self, that the include is ignored because it has no impact on the joblist

**Comment by firecow** [comment]
Can you paste a minimal `.gitlab-ci.yml` that illustrates your needs? @mjrider 
I'm sure i'll be able to implement `include:template` pretty fast, since they are just a preset of regular remote includes.

**Comment by mjrider** [comment]
Something like this
```yaml
---

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

foobar:
  image: alpine:latest
  stage: test
  script:
    - echo "foobar"
  

```
