### ISSUE TITLE
gitlab-ci-local --fetch-includes should handle imports like gitlab (http/https as remote import)

### ISSUE THREAD

**Issue by typoworx-de** [firecow/gitlab-ci-local#371]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
include:
  - 'https://gitlab.com/..../raw/master/pipeline/my-deploy.yml'
```

**Expected behavior**
Gitlab will fetch the "remote" Yaml-Config. gitlab-ci-local will fail even with ```gitlab-ci-local --fetch-includes```

**Comment by firecow** [comment]
@typoworx-de Hmmm... Thought that already worked. I'll have a look.

**Comment by firecow** [comment]
@typoworx-de Please paste a concrete example instead of the pseudo one.
We already have a test to verify that this functionality works in https://github.com/firecow/gitlab-ci-local/blob/master/tests/test-cases/include-remote/.gitlab-ci.yml

So we need more info to debug from.

Reopen the issue, once you got a real life example, that I can debug.

**Comment by firecow** [comment]
Oh, i think I know, what the issue is now...
http|https has specielt mening, and auto interprets as `remote:` on it

**Comment by firecow** [comment]
@typoworx-de Fixed in https://github.com/firecow/gitlab-ci-local/commit/4db7812418334d90073340c3e46a7284507ccb63
Thanks for the bug report, even though I didn't get the problem at first :smile:

**Comment by typoworx-de** [comment]
Hello @firecow,
thanks for resolving. Sorry I haven't been in office for the last few days, so I couldn't react to your questions. But I noticed you already figured out the "remote:" thing as Gitlab automatically determines http|https as remote without explicitly giving it the hint "remote:". Sorry if I have not been concrete enough. I'll try my best next time :-D

**Comment by firecow** [comment]
@typoworx-de No problemo :smiley:

**Comment by typoworx-de** [comment]
Great work, just checked the new release and it works like a charm now :-D

**Comment by firecow** [comment]
Great, keep coming 👍

**Comment by justinTM** [comment]
@firecow first of all thanks for making this. what an undertaking of a project. 

second of, i'm not sure if this is the right place, but i'm getting an include fetch error:

```console
% gitlab-ci-local "Plan Dev" --fetch-includes
Remote include could not be fetched https://gitlab.com/gitlab-org/gitlab/-/raw/HEAD/lib/gitlab/ci/templates/Workflows/Branch-Pipelines.gitlab-ci.yml
AggregateError
```

but if i plug in that URL to a browser, i get:

```yml
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Workflows/Branch-Pipelines.gitlab-ci.yml

# Read more on when to use this template at
# https://docs.gitlab.com/ee/ci/yaml/#workflowrules

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
```

the include in yaml:
```yml
include:
  - template: "Workflows/Branch-Pipelines.gitlab-ci.yml"
```
