### ISSUE TITLE
Unknown argument: oudCredentials

### ISSUE THREAD

**Issue by fabiocruzcoelho** [firecow/gitlab-ci-local#373]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - echo "Heya"
```

**Expected behavior**
Paste a public job url.

**Host information**
Ubuntu
gitlab-ci-local 4.28.2

**Additional context**
run gitlab-ci-local --list return Unknown argument: oudCredentials. or any command
