### ISSUE TITLE
CI_COMMIT_MESSAGE env variable contains a newline which is expanded when printing env

### ISSUE THREAD

**Issue by byrdal** [firecow/gitlab-ci-local#393]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - env | grep -n1 CI_COMMIT_MESSAGE
```

**Expected behavior**

I would expect CI_COMMIT_MESSAGE to be

CI_COMMIT_MESSAGE=Commit Title\nMore commit text

**Host information**
MacOS
gitlab-ci-local 4.28.2

**Additional context**
