### ISSUE TITLE
Support rules:changes

### ISSUE THREAD

**Issue by ck-trigfb** [firecow/gitlab-ci-local#395]
In Gitlab CI you can add the keyword "rules:changes" for a job that should only be executed if specified file changed.: https://docs.gitlab.com/ee/ci/yaml/#ruleschanges

Example:
```
build:
  script:
    - echo "building"
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      changes:
        - src/**/*
```

What i want to achieve with that: Assuming you multiple services and all of them will be compiled in a big pipeline. So if i only change something in one of the services i have to wait since the whole pipeline finished building. With "rules:changes" i want to achieve something similar other tools like skaffold do: Only build that service / container where changes in code / configuration happend.

Actual problem: gitlab-ci-local seems to completely ignore that setting. I dont get an error but the job runs regardless of whether changes take place or not.
