### ISSUE TITLE
variable description/value handling

### ISSUE THREAD

**Issue by chrisfromredfin** [firecow/gitlab-ci-local#420]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
variables:
  # These are top level vars so they appear on the Run Pipeline form https://docs.gitlab.com/ee/ci/pipelines/#prefill-variables-in-manual-pipelines
  PHP_TAG:
    value: "7.4"
    description: The version of PHP to use for this Pipeline.

default:
  image:
    name: wodby/php:$PHP_TAG-dev

composer:
  stage: build
  script:
    - "echo hello"
```

**Expected behavior**
Reconciles the variable into the command.

**Host information**
MacOS X 12.3 (Monterey)
gitlab-ci-local 4.29.0

**Additional context**
It seems that the variable is being interpreted as an Object in JavaScript. Here is output when running `gitlab-ci-local` with the above .gitlab-ci.yml:

```
❯ gitlab-ci-local
parsing and downloads finished in 13 ms
composer starting wodby/php:[object Object]-dev (build)
Pulling wodby/php:[object Object]-dev
"docker pull" requires exactly 1 argument.
See 'docker pull --help'.

Usage:  docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Pull an image or a repository from a registry
```
