### ISSUE TITLE
Lookup ref if not specified in include

### ISSUE THREAD

**Issue by node13h** [firecow/gitlab-ci-local#423]
**Minimal .gitlab-ci.yml illustrating the issue**
`parser-includes.ts` defaults the `ref` value to `master` when not specified. Some projects use `main` instead of `master` as the default branch name these days. 

The following won't work if the `my-group/my-project` project does not have the `master` branch: 

```yml
---
include:
  - project: 'my-group/my-project'
    file: '/templates/.gitlab-ci-template.yml'
```
A workaround is to always set `ref` like so:

```yml
---
include:
  - project: 'my-group/my-project'
    file: '/templates/.gitlab-ci-template.yml'
    ref: main
```
 but this could cause breakage if projects change their default branch in the future.

**Expected behavior**
When `ref` is not specified, the include should pick the file from the default branch, not `master`.

**Host information**
GitLab SaaS

**Additional context**
Perhaps defaulting `ref` to `HEAD` instead of `master` would fix the problem? According the [the documentation](https://docs.gitlab.com/ee/ci/yaml/#includefile) `HEAD` is what GitLab itself defaults to:
> You can also specify a `ref`. If you do not specify a value, the ref defaults to the `HEAD` of the project
