### ISSUE TITLE
rules/if fails when regexp match contains /

### ISSUE THREAD

**Issue by hakalb** [firecow/gitlab-ci-local#424]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(develop$|release\/.*|master$)/'
  script:
    - echo "..."
```

**Expected behavior**
No exception.

```sh
$ gitlab-ci-local --preview
SyntaxError: Unexpected token '{'
```

**Host information**
macOS Monterey 
gitlab-ci-local 4.30.1

**Additional context**
If statement expands to
```yml
'my-branch'.match(/^(develop$|release\/) != null.*|master$)/
```
The function `evaluateRuleIf` have special handling for `/` which makes this break.

Without forward slashes it correctly expands to
```sh
# '$CI_COMMIT_REF_NAME =~ /^(develop$|release.*|master$)/'

'my-branch'.match(/^(develop$|release.*|master$)/) != null
```

Anchor example from GitLab CI itself using forward slashes
```yml
if-fork-merge-request: &if-fork-merge-request-gitlab
  if: '$CI_PROJECT_NAMESPACE !~ /^gitlab(-org)?($|\/)/ && $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_LABELS !~ /pipeline:run-all-rspec/'
```
