### ISSUE TITLE
Error with rules and !reference

### ISSUE THREAD

**Issue by atli-c** [firecow/gitlab-ci-local#426]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
.pipeline_rules:
  rules:
    - if: $GITLAB_CI == 'false'
      when: manual
foo:
  rules:
    - if: $UPSTREAM_CI_COMMIT_BRANCH == 'asdfqwerwetysdfv'
      when: on_success
    - !reference [.pipeline_rules, rules]
    - when: never
  script:
    - echo 'foobar'
```
Output from `gitlab-ci-local --preview`:
```yml
  rules:
    - if: $UPSTREAM_CI_COMMIT_BRANCH == 'asdfqwerwetysdfv'
      when: on_success
    - - if: $GITLAB_CI == 'false'
        when: manual
    - when: never
```
Note the nested list. 

**Expected behavior**
"foo" job should be "manual", not "on_success".  I was expecting the list to be flattened.
```yml
  rules:
    - if: $UPSTREAM_CI_COMMIT_BRANCH == 'asdfqwerwetysdfv'
      when: on_success
    - if: $GITLAB_CI == 'false'
      when: manual
    - when: never
```

**Host information**
macOS Monterey 12.3.1
gitlab-ci-local 4.30.1

**Additional context**
n/a

**Comment by bcouetil** [comment]
Hello 😊

Did not interract with you in a while, but I stille rely heavily on this wonderful tool 🥰

I was about to post an issue, and found this one, so I'm adding a repro case :

```
variables:
  SIMPLY_FALSE: "false"

.never:
  rules:
    - if: $SIMPLY_FALSE == "false"
      when: never

test:
  script:
    - echo "SIMPLY_FALSE=$SIMPLY_FALSE, should not run"
  rules:
    - !reference [.never, rules]
    - if: $SIMPLY_FALSE != "true"
      when: never
```

The job runs but should not :

```
parsing and downloads finished in 46 ms
test starting shell (test)
test $ echo "SIMPLY_FALSE=$SIMPLY_FALSE, should not run"
test > SIMPLY_FALSE=false, should not run
test finished in 10 ms

 PASS  test
pipeline finished in 3.49 s
```
