### ISSUE TITLE
Remote, Home and Project variables from files override's job specific variables

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#429]
```yml
# .gitlab-ci-local-variables.yml, could also be remote or home variables
---
TEST:
  values:
    '*': remote-value
```

```yml
---
job:
  variables:
    TEST: job-value
  script:
    - echo "${TEST}" # remote-value, it should be job-value to mimic real gitlab more correctly
```
