### ISSUE TITLE
Multiple aliased service declarations will never pass healthchecks.

### ISSUE THREAD

**Issue by jamesmeneghello** [firecow/gitlab-ci-local#432]
Example yaml chunk:

```yaml
services:
    - name: postgres:14
      alias: postgresql
    - name: postgres:14
      alias: postgresql2
```

See: https://github.com/firecow/gitlab-ci-local/blob/ff514e5b8acb56d4c677e9b6e0630dd13f158a70/src/job.ts#L981

Because `aliases[0]` is the only hostname checked, the healthcheck will always fail. `./wait-for-it.sh` will look for `postgres:5432`, which doesn't exist. You can work around this by re-tagging the docker image locally (e.g. `docker tag postgres:14 postgresql:14`), which allows you to instead use the image name `postgresql`, giving it the correct hostname to check for.
