### ISSUE TITLE
External pipeline includes which further include templates don't work

### ISSUE THREAD

**Issue by dus7eh** [firecow/gitlab-ci-local#438]
Having a pipeline build from pieces as presented below:
### local project
```yml
# .gitlab-ci.yml
include:
  - project: "some_external_project"
    ref: master
    file: "pipeline.yml"

main:
  script:
    - echo "Hello"
```

### external project
```yml
# pipeline.yml
include: "components.yml"
```
```yml
# components.yml
prep:
  script:
    - echo "Pre-processing"
```

Trying to retrieve pipeline job list with `gitlab-ci-local --list` results in an error similar to:
```
TypeError: Cannot assign to read only property '0' of string 'components.yml'
    at /snapshot/gitlab-ci-local/src/parser-includes.ts:55:46
    at Array.forEach (<anonymous>)
```

**Expected behavior**
It is possible to retrieve the job list and run the specified job.

**Host information**
Ubuntu
gitlab-ci-local 4.30.1
