### ISSUE TITLE
Project dir changes between jobs which breaks some tools.

### ISSUE THREAD

**Issue by matclab** [firecow/gitlab-ci-local#440]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
image:
  name: bash

import:
  script: # import project under eclispe generate a workspace
    - set -eo pipefail
    - echo $CI_PROJECT_DIR
    - mkdir -p workspace && echo "$(pwd)/project" > workspace/config
  artifacts:
    paths:
      - workspace

gen:
  needs:
    - import
  dependencies:
    - import
  script:
    - set -eo pipefail
    - echo $CI_PROJECT_DIR
    - cd $(cat workspace/config)

```

**Expected behavior**
Should pass : https://gitlab.com/matclab/gitlab-ci-local-test/-/pipelines/527043993
Whereas it gives: 
```
parsing and downloads finished in 32 ms
import starting bash:latest (test)
import pulled bash:latest in 57 ms
import copied to container in 59 ms
import $ set -eo pipefail
import $ echo $CI_PROJECT_DIR
import > /builds/import
import $ mkdir -p workspace && echo "$(pwd)/project" > workspace/config
import exported artifacts in 755 ms
import copied artifacts to cwd in 55 ms
import finished in 1.97 s
gen    starting bash:latest (test)
gen    pulled bash:latest in 112 ms
gen    copied to container in 93 ms
gen    imported artifacts in 90 ms
gen    $ set -eo pipefail
gen    $ echo $CI_PROJECT_DIR
gen    > /builds/gen
gen    $ cd $(cat workspace/config)
gen    > /gcl-scripts/gen: line 8: cd: /builds/import/project: No such file or directory
gen    finished in 1.51 s  FAIL 1  

 PASS  import
 FAIL  gen   
  > /builds/gen
  > /gcl-scripts/gen: line 8: cd: /builds/import/project: No such file or directory
```

**Host information**
Arch linux 
gitlab-ci-local 4.30.1.r16.g000a3ef (from git)

**Additional context**
When using a docker runner, the projetc path is not consistent between each jobs and thus the artifacts paths may change between jobs.
Some tools (like eclipse) use absolute paths when configured (for exemple when importing existing eclipse projects) and as such they need to have a stable project paths between jobs.
