### ISSUE TITLE
cache:paths config should be an array of strings

### ISSUE THREAD

**Issue by atli-c** [firecow/gitlab-ci-local#442]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
example_job:
  variables:
    NPM_CONFIG_CACHE: ./.npm/cache
    cache:
       - key: "${CI_PROJECT_PATH_SLUG}-${CI_PROJECT_NAME}-npm"
          paths: ./.npm/cache
  script:
    - npm ci --prefer-offline
```
gitlab-ci-local works.

**Expected behavior**
`gitlab-ci-local` should give the same/similar error as gitlab-ci:
> Found errors in your .gitlab-ci.yml:
> jobs:example_job:cache:paths config should be an array of strings

**Host information**
macOS
gitlab-ci-local 4.30.1

**Additional context**
n/a
