### ISSUE TITLE
Infer CI variables in cache key

### ISSUE THREAD

**Issue by lcswillems** [firecow/gitlab-ci-local#466]
In the following example, `$CI_COMMIT_REF_SLUG` will be replaced by its real value in `script` but not in cache `key`.

```
build:
  image: node16
  stage: build
  script:
    - echo $CI_COMMIT_REF_SLUG
    - ...
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
```

If somebody could tell me roughly how to modify the repository to add this feature, I could do a PR

**Comment by lcswillems** [comment]
Thanks!!!

**Comment by lcswillems** [comment]
@firecow I have tried the new version of the package and I still have the issue...

For example this `.gitlab-ci.yml`:

```
variables:
  prefix: production

test:
  image: node
  script:
    - mkdir folder
    - echo "Hi" > folder/file.txt
  cache:
    key: $PREFIX-file
    paths:
      - folder/
```

I get these logs:

```
test starting node:latest (test)
test > still running...
test > still running...
test pulled node:latest in 22 s
test copied to container in 129 ms
test $ mkdir folder
test $ echo "Hi" > folder/file.txt
test exported cache folder/ '-file' in 784 ms
test finished in 26 s
```

The cache is saved in '-file' folder instead of 'production-file' folder.
