### ISSUE TITLE
only keyword 

### ISSUE THREAD

**Issue by naweiss** [firecow/gitlab-ci-local#467]
In Gitlab CI you can add the keyword "only" for a job that should only be executed if specified condition is met: https://docs.gitlab.com/ee/ci/yaml/#only--except

For example to execute only on tagged commits:

```yaml
build:
  script:
    - echo "building"
  only:
    - tags
```
gitlab-ci-local seems to completely ignore that setting. I don't get an error but the job runs regardless of whether changes take place or not.
