### ISSUE TITLE
Project/Group/Runner variables imported from file in users home dir

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#48]
```
gitlab-ci-local --set-global-var SSH_PRIVATE_KEY < $(cat ~/.ssh/id_rsa)
```

```yml
yarn-install:
  stage: .pre
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - cd client
    - yarn install
```

This will definently be needed sooner or later.
