### ISSUE TITLE
YAML Script anchor does not work if it's not a list

### ISSUE THREAD

**Issue by greenmaid** [firecow/gitlab-ci-local#484]
**Minimal .gitlab-ci.yml illustrating the issue**

Same example as #24 

```yml
---
.example: &test_anchor
  echo 'Example'
demo:
  stage: test
  script:
    - echo 'Hello'
    - *test_anchor
```

I got:
```
TypeError: Cannot create property 'extends' on string 'echo 'Example''
    at Object.jobExtends (/usr/lib/node_modules/gitlab-ci-local/src/job-expanders.ts:25:24)
    at Parser.init (/usr/lib/node_modules/gitlab-ci-local/src/parser.ts:84:22)
    at Function.create (/usr/lib/node_modules/gitlab-ci-local/src/parser.ts:54:9)
    at handler (/usr/lib/node_modules/gitlab-ci-local/src/handler.ts:115:18)
    at Object.handler (/usr/lib/node_modules/gitlab-ci-local/src/index.ts:25:34)
```

**Expected behavior**
It should work exactly as:
```yml
---
demo:
  stage: test
  script:
    - echo 'Hello'
    - echo 'Example'
```
as it's YAML equivalent

**Host information**
Ubuntu
gitlab-ci-local 4.31.0

**Additional context**
this issue is easy to workaround by using an array:
```yaml
.example: &test_anchor
  - echo 'Example'
```

but it is really an issue when including external pipeline code such [to-be-continuous templates](https://gitlab.com/to-be-continuous)
