### ISSUE TITLE
Invalid environment matching

### ISSUE THREAD

**Issue by lcswillems** [firecow/gitlab-ci-local#485]
I have this in my `variables.yml` file:

```
KEY:
    values:
        "*": X
        "production": Y
```

and my `.gitlab-ci.yml` file is the following:

```
build:
    script:
        - echo $KEY
    environment:
        name: production
```

However when the CI runs on my computer, this prints "X" instead of "Y" as it would print on Gitlab.

**Comment by lcswillems** [comment]
No problem!

**Comment by firecow** [comment]
I can't reproduce this.
In a clean folder I place 
`.gitlab-ci.yml`
```yml
build:
  script:
    - echo $KEY
  environment:
    name: production
```

I then place a `.gitlab-ci-local-variables.yml` inside the same folder
```yml
KEY:
  values:
    "*": X
    "production": Y
```

I then run `gitlab-ci-local`

![image](https://user-images.githubusercontent.com/973602/170261367-a507d4dc-a803-40bf-9725-0172fe247b1a.png)
