### ISSUE TITLE
Cache across different runs. 

### ISSUE THREAD

**Issue by damjad** [firecow/gitlab-ci-local#495]
**Is your feature request related to a problem? Please describe.**
Whenever we run GitLab docker runner in GitLab UI. The cache is preserved across different runs. It's useful in speeding up pipelines by avoiding downloading dependencies every time. 

I am unable to do that locally. 

git ci file. 
```
variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip

cache:
  paths:
    - $PIP_CACHE_DIR

default:
  image: alpine:3.12

stages:
  - test

.config_docker: &config_docker
  before_script:
    - apk add python3 py-pip gcc g++ python3-dev libc-dev musl-dev && pip3 install awscli
    - cd ${CI_PROJECT_DIR}
    - pip install -r requirements.txt
test:
  stage: test
  <<: *config_docker
  script:
    - echo "hello"
```

cli command used:
```
gitlab-ci-local test --no-needs --shell-isolation
```

**Describe the solution you'd like**
I would like the cache to be preserved across different runs.

**Describe alternatives you've considered**

**Additional context**
