### ISSUE TITLE
Interactive decorator

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#51]
```yaml
# @Interactive
# @Description Opens an interactive shell attached to the stack
interactive-shell:
  stage: .post
  rules:
    - if: $GITLAB_CI == 'false'
      when: manual
  script:
    - docker run -it -u $(id -u):$(id -g) -w /app/ -v "$PWD/:/app/" debian bash
 ```
 
 ![image](https://user-images.githubusercontent.com/973602/105366820-0e9f2c00-5c00-11eb-90a1-7a1eab860c5e.png)
