### ISSUE TITLE
gcl-entry script makes assumptions about the container being copied into

### ISSUE THREAD

**Issue by jboyens** [firecow/gitlab-ci-local#511]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  image:
    name: gcr.io/kaniko-project/executor:v1.6.0-debug
    entrypoint: ['']
  script:
    - |
      /kaniko/executor \
        --context "." \
        --dockerfile "./Dockerfile" \
        --snapshotMode=redo \
        --destination=doesntmatter
```

**Observed behavior**
```
job starting gcr.io/kaniko-project/executor:v1.6.0-debug (test)
job copied to container in 71 ms
job > exec /gcl-entry: no such file or directory
job finished in 1.03 s  FAIL 1  
```

This happens because the kaniko image does not have a `/bin/sh`, only `/busybox/sh`.

**Expected behavior**
The build would successfully progress.

**Host information**
NixOS unstable (repeatable on other platforms)
gitlab-ci-local latest `master` (696c83df33e3528a90936189ca2464364f16ed25)

**Additional context**
I'd attempt to provide a PR, but I'm still spelunking through the recent changes to the code base and don't have a solid grasp of everything just yet.
