### ISSUE TITLE
Variables are not being set inside rules/if section

### ISSUE THREAD

**Issue by mjcollin** [firecow/gitlab-ci-local#527]
When I put a variables section inside a rules/if section in either the job or workflow, it appears they don't get set. However when the job runs on GitLab the variables are correctly set.

This is consistent with how running `gitlab-runner exec shell my_job` locally behaves, but it would be incredibly useful to support this behavior locally since it does work on GitLab. Being able to do this in the workflow section is less important to me personally but it is supported.

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
variables:
  GLOBAL_VAR: "YES"

workflow:
  rules:
    - if: $GLOBAL_VAR == "YES"
      variables:
        WORKFLOW_RULE_VAR: "YES"
    - variables:
        WORKFLOW_RULE_VAR: "NO"

my_job:
  variables:
    JOB_VAR: "YES"
  rules:
    - if: $GLOBAL_VAR == "YES"
      variables:
        JOB_RULE_VAR: "YES"
    - variables:
        JOB_RULE_VAR: "NO"
  script:
    - echo $GLOBAL_VAR
    - echo $WORKFLOW_RULE_VAR
    - echo $JOB_VAR
    - echo $JOB_RULE_VAR
  when:
    always
```

**Expected behavior**
```bash
% gitlab-ci-local my_job         
parsing and downloads finished in 65 ms
my_job starting shell (test)
my_job $ echo $GLOBAL_VAR
my_job > YES
my_job $ echo $WORKFLOW_RULE_VAR
my_job > YES
my_job $ echo $JOB_VAR
my_job > YES
my_job $ echo $JOB_RULE_VAR
my_job > YES
my_job finished in 14 ms
```

**Host information**
MacOS
gitlab-ci-local 4.32

**Additional context**
Actual gitlab-ci-local output:

```bash
% gitlab-ci-local my_job         
parsing and downloads finished in 65 ms
my_job starting shell (test)
my_job $ echo $GLOBAL_VAR
my_job > YES
my_job $ echo $WORKFLOW_RULE_VAR
my_job $ echo $JOB_VAR
my_job > YES
my_job $ echo $JOB_RULE_VAR
my_job finished in 14 ms
```

Actual gitlab-runner exec output:

```bash
% gitlab-runner exec shell my_job
...
Executing "step_script" stage of the job script
$ echo $GLOBAL_VAR
YES
$ echo $WORKFLOW_RULE_VAR

$ echo $JOB_VAR
YES
$ echo $JOB_RULE_VAR

Job succeeded
```

Actual job output from running on a runner at GitLab:

```bash
Executing "step_script" stage of the job script
00:00
Using docker image sha256:b0757c55a1fdbb59c378fd34dde3e12bd25f68094dd69546cf5ca00ddbaa7a33 for docker:stable with digest docker@sha256:fd4d028713fd05a1fb896412805daed82c4a0cc84331d8dad00cb596d7ce3e3a ...
$ echo $GLOBAL_VAR
YES
$ echo $WORKFLOW_RULE_VAR
YES
$ echo $JOB_VAR
YES
$ echo $JOB_RULE_VAR
YES
```

Note that toggling $GLOBAL_VAR to "NO" will correctly result in the *_RULE_VAR variables being "NO" when run on GitLab as well.
