### ISSUE TITLE
My job ran successfully despite to invalid yml.

### ISSUE THREAD

**Issue by muarts** [firecow/gitlab-ci-local#533]
I deleted the install job before the run started, although my test job ran successfully.

```yml
---
test:
  stage: test
  script:
    - echo "Heya"
  dependincies:
    - install
```

**Host information**
MacOS
gitlab-ci-local 4.32.0
