### ISSUE TITLE
Support dynamic pipelines

### ISSUE THREAD

**Issue by synergiator** [firecow/gitlab-ci-local#57]
Since GitLab 13.4, it's possible to write CI/CD pipelines which [dynamically create sub-pipelines](https://gitlab.com/gitlab-org/gitlab/-/issues/212373).

It would be great to have support for that.

Currently, the tool considers to be the "trigger" stance to be a malformed job and suggests to use "script" tag in it.

**Comment by gilzow** [comment]
Just came here to ask if child/dynamic pipelines is on the road map. Definite +1 from me

**Comment by firecow** [comment]
Two makes a crowd, now i'm definitely intrigued 😃 I will post an idea in this thread once I get to a PC

**Comment by firecow** [comment]
@gilzow @synergiator Can any of you guys paste an as small as possible .gitlab-ci.yml that illustrates, what you are looking for? And perhaps a small description of how you would actually start such a triggered pipeline via CLI commands.

**Comment by firecow** [comment]
```yml
---
pipe-gen-job:
  script:
    - cat .gitlab-ci-tmpl.yml | envsubst > .gitlab-ci-child.yml
     
trigger_job:
  trigger:
    include: .gitlab-ci-child.yml
```

Here is what I think you guys want, but please confirm, before I start development of such a feature.

**Comment by synergiator** [comment]
Hi there, here is what I would suggest:

```
---
stages:
  - generate
  - run

default:
  tags:
    - insert_your_runner_name

pipe-gen-job:
  stage: generate
  script:
    - echo "here comes logic to create a dynamic child pipeline"
    - mv .gitlab-ci-child.yml.tpl .gitlab-ci-child.yml
  artifacts:
    paths:
      - .gitlab-ci-child.yml

trigger_job:
  stage: run
  trigger:
      strategy: depend
      include:
        - artifact: .gitlab-ci-child.yml
          job: pipe-gen-job
```
