### ISSUE TITLE
include local with "/" as prefix is not recognized

### ISSUE THREAD

**Issue by alexander-matthiesen** [firecow/gitlab-ci-local#573]
**Minimal .gitlab-ci.yml illustrating the issue**

structure:
```text
 |- .gitlab-ci.yml
 |- test
     |- nested.yml 
```

.gitlab-ci.yml
```yml
---
include:
  - local: '/test/nested.yml'
```

common/nested.yml
```yml
---
job:
  script:
    - echo "Heya"
```

**Expected behavior**
"/common/nested.yml" is found
