### ISSUE TITLE
Support CI_JOB_STATUS in after_script

### ISSUE THREAD

**Issue by greenmaid** [firecow/gitlab-ci-local#581]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - echo "Heya"
  after_script:
    - echo $CI_JOB_STATUS
```
=> CI_JOB_STATUS is empty

**Expected behavior**
Variable CI_JOB_STATUS should be set with "success" here (or "failed" if main script failed)
See [doc](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html)

**Host information**
Ubuntu 20.04
gitlab-ci-local 4.1.33
