### ISSUE TITLE
cache:key in combination with mount-cache=true ca lead to error: "invalid characters for local volume"

### ISSUE THREAD

**Issue by ck-trigfb** [firecow/gitlab-ci-local#585]
If you use cache:key with option --mount-cache=true, then depending on the value of cache:key it will create an illegal name for a docker volume. It is a similar problem like the "unsafe jobname" issue in #186.

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  image: maven:3.8.4-openjdk-11-slim  
  script:
    - echo "Heya"
  cache:
    key: "problem/" 
```

**Expected behavior**
Job will be executed without errors.

**Additional context**
Since cache:key will be used as a part of the volume name, the job will fail if cache:key consists of illegal characters.

I recognized that error because i used $CI_PROJECT_DIR as cache:key, which become "/gcl-builds" if using an image for the job.
