### ISSUE TITLE
after_script with services tries to create network that already exists

### ISSUE THREAD

**Issue by kleijnweb** [firecow/gitlab-ci-local#600]
To reproduce (on master):

```
test:
  image: php:8.1
  services:
    - name: mysql:5.7.31
      alias: db
  after_script:
    - echo "after_script"
  script:
    - echo "script"
```

```
parsing and downloads finished in 43 ms
codeception starting php:8.1 (test)
codeception started service image: mysql:5.7.31 with aliases: mysql, db in 346 ms
codeception > still running...
codeception > still running...
codeception > still running...
codeception service image: mysql:5.7.31 healthcheck failed: mysql:33060
codeception service image: mysql:5.7.31 healthcheck passed in 31 s
codeception service image: mysql:5.7.31 healthcheck failed: mysql:3306
codeception copied to container in 142 ms
codeception $ echo "script"
codeception > script
Error: Command failed with exit code 1: docker network create gitlab-ci-local-538741
Error response from daemon: network with name gitlab-ci-local-538741 already exists
    at makeError (/snapshot/gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/snapshot/gitlab-ci-local/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Job.createDockerNetwork (/snapshot/gitlab-ci-local/src/job.ts:928:37)
    at Job.execScripts (/snapshot/gitlab-ci-local/src/job.ts:534:17)
    at Job.start (/snapshot/gitlab-ci-local/src/job.ts:393:42)
```

Passes:

```
test:
  image: php:8.1
  #services:
  #  - name: mysql:5.7.31
  #    alias: db
  after_script:
    - echo "after_script"
  script:
    - echo "script"
```

Passes:

```
test:
  image: php:8.1
  services:
    - name: mysql:5.7.31
      alias: db
  #after_script:
  #  - echo "after_script"
  script:
    - echo "script"
 ```
