### ISSUE TITLE
Mock scripts using match / replace

### ISSUE THREAD

**Issue by kleijnweb** [firecow/gitlab-ci-local#601]
It would be extremely handy if gcl was able to mock lines of `script`, by replacing it with a local script when it matches a certain regular expression.

Right now the only way to mock a feature that is actually from an image, is override a variable that hold the image tag, push a different version with different behavior, and then use that. That is doable but not ideal.

**Comment by firecow** [comment]
Please elaborate.

I don't quite understand the feature request.

**Comment by bcouetil** [comment]
There is sometimes situations when we don't want do to the same commands locally.

For these cases, I use $GITLAB_CI variable, which is "true" only in CI.

````
- if [ "$GITLAB_CI" == "true" ]; then ...
```

Would it solve your problem ?

**Comment by kleijnweb** [comment]
Lets say you have this in a job:

```
scripts:
  - ./do-something.sh arg1 arg2
```
It would be handy if we could have something completely different executed, without having to modify it and check for the $GITLAB_CI variable.

Additionally and perhaps more importantly, if you have something like this:

```
image: someimage
scripts:
  - ./do-something-with-script-in-image.sh
```

Lets say that script does something you don't want to happen locally, perhaps connecting remote infrastructure. The image might be managed by a completely different department, making it hard to modify. You can create a new image that does what you want it to for testing, but that is a PITA. It would be a lot easier and cleaner if you had a script on the host machine that is mounted and then executed.

In general, it would be better to add as little customization needed purely for GCL to the GitLab templates.

Config in GCL for something like that could look like this:

```
script_mocks:
  shell:
    - { match: '^./do-something.sh arg1', run: '/some/path/do-something-else.sh foo bar' }
  docker:
    someimage:
      - { match: '^./do-something.sh arg1', run: '/some/path/on/host/which/will/be/mounted/do-something-else.sh foo bar' }
```
