### ISSUE TITLE
JUnit report artifacts not exported

### ISSUE THREAD

**Issue by haydenseitz** [firecow/gitlab-ci-local#615]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
test_artifact:
  script:
    - touch junit.xml
    - touch test.env
  artifacts:
    reports:
      junit: junit.xml
      dotenv: test.env
```

**Expected behavior**
Junit reports are exported at the end of the job.

**Actual behavior**
Junit is not exported. In above example, only the dotenv file is exported

**Host information**
Ubuntu 20.04.4
gitlab-ci-local 4.34.0

**Additional context**

Job output from above example:
```shell
$ gitlab-ci-local test_artifact
parsing and downloads finished in 164 ms
test_artifact      starting shell (tests)
test_artifact      $ touch junit.xml
test_artifact      $ touch test.env
test_artifact      exported artifacts in 13 ms
test_artifact      finished in 29 ms
```

Editor showing only test.env artifact:
![image](https://user-images.githubusercontent.com/17074342/195201796-a63207b6-e156-4d1e-a0e4-20022532e92f.png)

When trying to only export a junit report, it returns "no artifacts was copied":

```yaml
test_artifact:
  stage: tests
  script:
    - touch junit.xml
  artifacts:
    reports:
      junit: junit.xml
```

Job output:
```shell
$ gitlab-ci-local test_artifact
parsing and downloads finished in 221 ms
test_artifact      starting shell (tests)
test_artifact      $ touch junit.xml
test_artifact      !! no artifacts was copied !!
test_artifact      finished in 23 ms
```
