### ISSUE TITLE
Source files missing from service container

### ISSUE THREAD

**Issue by haydenseitz** [firecow/gitlab-ci-local#616]
**Is your feature request related to a problem? Please describe.**
According to [the docs](https://docs.gitlab.com/ee/ci/services/#how-docker-integration-works), GitLab runners mount the $CI_PROJECT_DIR (`/builds/group-name/project-name/`) to both _job_ containers and _service_ containers. This allows docker-in-docker jobs like [browser_performance](https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Verify/Browser-Performance.gitlab-ci.yml) to share files between the job container and the dind service container. It seems that gitlab-ci-local does not mount the build directory to service containers, which leads to the issue described in [this older gitlab issue](https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227).

**Describe the solution you'd like**
Mount the same build volume that is generated for each job (`gcl-job_name-xxxxxx-build`) in all service containers

**Describe alternatives you've considered**
Might be able to use the `--volume` argument to mount something in `.gitlab-ci-local/builds` to be shared by both job and service containers?

**Additional context**
Example of the browser_performance job failing:
```yaml
---
include:
  - template: Verify/Browser-Performance.gitlab-ci.yml

browser_performance:
  variables:
    URL: https://example.com
```

**Comment by haydenseitz** [comment]
Sorry for two issues in same day 😅

**Comment by bcouetil** [comment]
Hello 😊

Very interesting, since you have created this issue, it means that it works that way. I've never heard of that.

On the documentation you provide, it says at step 6 : `Checkout code in: /builds/group-name/project-name/`

But it does not say that it is on both containers.

Is it the right piece of documentation ?

**Comment by firecow** [comment]
We should be able to implement this...

**Comment by haydenseitz** [comment]
I don't have private DIND Gitlab runners, so I haven't confirmed myself that the build didn't rectory is shared. But at the bottom of [this section](https://docs.gitlab.com/ee/ci/services/#how-the-health-check-of-services-works) is reads:

> The service container is not providing any networking service, but it’s doing something with the job’s directory (**all services have the job directory mounted as a volume under /builds**). In that case, the service does its job, and because the job is not trying to connect to it, it does not fail.

**Comment by haydenseitz** [comment]
Just to double check, I created a test repo to verify.

Here is the job with gitlab-ci-local:
```terminal
$ gitlab-ci-local 
parsing and downloads finished in 42 ms
dind_service starting docker:stable (test)
dind_service started service image: docker:stable-dind with aliases: docker in 1.24 s
dind_service service image: docker:stable-dind healthcheck passed in 2.32 s
dind_service copied to container in 140 ms
dind_service $ printenv CI_PROJECT_DIR
dind_service > /gcl-builds
dind_service $ pwd
dind_service > /gcl-builds
dind_service $ touch newfile
dind_service $ echo "Project files and 'newfile' on the job container:"
dind_service > Project files and 'newfile' on the job container:
dind_service $ ls -a
dind_service > .
dind_service > ..
dind_service > .git
dind_service > README.md
dind_service > newfile
dind_service $ echo "Project files and 'newfile' on the service container:"
dind_service > Project files and 'newfile' on the service container:
dind_service $ docker run --rm -v $(pwd):/work --workdir /work alpine ls -a
dind_service > Unable to find image 'alpine:latest' locally
dind_service > latest: Pulling from library/alpine
dind_service > 213ec9aee27d: Pulling fs layer
dind_service > 213ec9aee27d: Verifying Checksum
dind_service > 213ec9aee27d: Download complete
dind_service > 213ec9aee27d: Pull complete
dind_service > Digest: sha256:bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad
dind_service > Status: Downloaded newer image for alpine:latest
dind_service > .
dind_service > ..
dind_service finished in 11 s

 PASS  dind_service
pipeline finished in 11 s
```

And here is the gitlab pipeline: https://gitlab.com/hseitz/dind-service-example/-/jobs/3164209642

**Comment by firecow** [comment]
![image](https://user-images.githubusercontent.com/973602/195903578-ff029872-3609-4e31-b43e-563faa493d62.png)

![image](https://user-images.githubusercontent.com/973602/195903287-149cda38-698c-4456-9b57-a2dfa8486fcb.png)

```yml
# .gitlab-ci.yml
---
shell-build-job:
  tags: [shared-shell-executor]
  script:
    - |
      docker build -t firecow/debug-issue616:ci-${CI_PIPELINE_IID} -f - . <<EOF
      FROM alpine
      CMD cat README.md | tee test.txt
      EOF
    - docker push firecow/debug-issue616:ci-${CI_PIPELINE_IID}

image-debug-job:
  tags: [shared-docker-executor]
  needs: [shell-build-job]
  image: alpine
  services:
    - name: firecow/debug-issue616:ci-${CI_PIPELINE_IID}
  script:
    - pwd
    - ls -all
```

The build folder is not copied/mounted into service container, when I try to reproduce.
Feel free to a full example illustrating the behavior described in the issue and reopen issue :smile:
