### ISSUE TITLE
Remote include could not be fetched (AxiosError: Request failed with status code 400)

### ISSUE THREAD

**Issue by mamyn0va** [firecow/gitlab-ci-local#630]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
include:
  - project: to-be-continuous/golang
    ref: 4.0.0
    file: templates/gitlab-ci-golang.yml
  - project: to-be-continuous/docker
    ref: 3.2.2
    file: /templates/gitlab-ci-docker.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
```

**Expected behavior**
It works! :)

**Host information**
Manjaro
gitlab-ci-local 4.33.1

**Additional context**
The repo is hosted on a private gitlab instance, and it many templates.

```
Remote include could not be fetched https://gitlab.com/gitlab-org/gitlab/-/raw/HEAD/lib/gitlab/ci/templates/Jobs/SAST.gitlab-ci.yml AxiosError: Request failed with status code 400
```

I don't know why gitlab-ci-local tries to fetch some templates from gitlab.com instead of my private gitlab instance.
The 400 error may be due to a proxy error (I'm behind a corporate proxy).

**Comment by firecow** [comment]
@mamyn0va Can you provide the the full gitlab-ci-local ouput
```
gitlab-ci-local > textformjn.txt
```
and paste it here.

**Comment by mamyn0va** [comment]
There is nothing more :

```
$ gitlab-ci-local
Remote include could not be fetched https://gitlab.com/gitlab-org/gitlab/-/raw/HEAD/lib/gitlab/ci/templates/Jobs/Secret-Detection.gitlab-ci.yml AxiosError: Request failed with status code 400
```

Thanks!

**Comment by firecow** [comment]
Nothing about missing remote's or anything ?

**Comment by mamyn0va** [comment]
No, and it's easily reproducible with this file:

```yaml
include:
  - template: Jobs/SAST.gitlab-ci.yml
  ```

**Comment by firecow** [comment]
![image](https://user-images.githubusercontent.com/973602/196226576-dd6cb5e2-490e-4210-bbad-d5546bf0174a.png)

![image](https://user-images.githubusercontent.com/973602/196226605-4b9d8ab6-811e-470c-b155-2bcf350cf94a.png)


Not that easy apparently :smiley:

**Comment by firecow** [comment]
Why is it that you think templates shouldn't be fetched from gitlab.com ?

**Comment by mamyn0va** [comment]
I thought that templates were fetched from the same instance as the .gitlab-ci.yml's one.

-------- Message d'origine --------

**Comment by firecow** [comment]
And what makes you think that?

**Comment by mamyn0va** [comment]
The fact that other templates are fetched from my own instance.

**Comment by firecow** [comment]
No templates have ever been downloaded from your private gitlab instance.

Nah, not really...
Can you do regular curl against gitlab.com?

**Comment by bcouetil** [comment]
Hey 😊 

From what I see in the doc, it seems to be fetched... from the same instance, in a specific folder : https://docs.gitlab.com/ee/ci/yaml/#includetemplate

**Comment by mamyn0va** [comment]
Thanks, so the question is : why gitlab-ci-local fetches the template from gitlab.com ?

**Comment by firecow** [comment]
> Hey 😊 
> 
> From what I see in the doc, it seems to be fetched... from the same instance, in a specific folder : https://docs.gitlab.com/ee/ci/yaml/#includetemplate

The link point directly to gitlab.com.
Where do you see that information?

**Comment by firecow** [comment]
I just tried replacing gitlab.com with gitlab.firecow.dk in this https://gitlab.com/gitlab-org/gitlab/-/raw/master/lib/gitlab/ci/templates/Jobs/SAST.gitlab-ci.yml link, and the file is 404 on my private instance.

**Comment by bcouetil** [comment]
It's expected the 404, by default an instance has no template.

This piece of documentation in particular :

`Templates are stored in lib/gitlab/ci/templates. Not all templates are designed to be used with include:template, so check template comments before using one.`

Uses a relative path, and it must be empty in your instance.

I agree that the 400 error is something else, that we won't tackle together.

**Comment by bcouetil** [comment]
Unfortunately I can't test all of this, my current clients are on gitlab.com.

**Comment by bcouetil** [comment]
Because templates are defined by the admin, and you did not put any in your folder ? And on the OP instance, they are defined by the admins...

Just guessing at this stage, I can't test any of my assumptions.

**Comment by firecow** [comment]
You think they are manually added to self hosted instances?

I find that unlikely, since my templates are fetched from gitlab.com, when run on gitlab.firecow.dk...

**Comment by greenmaid** [comment]
I think I can confirm this error is caused by proxy :
```
---
include:
  - remote: "https://gitlab.com/Orange-OpenSource/lfn/ci_cd/gitlab-ci-templates/-/raw/master/markdown.gitlab-ci.yml"

job:
  image: alpine
  script:
    - echo 'hello'
```

this works perfectly without proxy but I got `Remote include could not be fetched https://gitlab.com/Orange-OpenSource/lfn/ci_cd/gitlab-ci-templates/-/raw/master/markdown.gitlab-ci.yml AxiosError: Request failed with status code 400` as soon I have with a proxy
