### ISSUE TITLE
Recursive combination of !reference + extends is not working

### ISSUE THREAD

**Issue by arg0d** [firecow/gitlab-ci-local#644]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
.default-variables:
  variables:
    FOO: foo

.variables-wrapper:
  variables:
    !reference [.default-variables, variables]

.variables:
  extends: .variables-wrapper

job:
  variables: !reference [.variables, variables]
  script:
    - echo $FOO
```

**Actual behavior**
```
> gitlab-ci-local job
!reference [.variables, variables] is undefined
```

**Expected behavior**
Job prints "foo"

**Host information**
Ubuntu
gitlab-ci-local 4.34.0

**Additional context**
