### ISSUE TITLE
Manual jobs with needs: still run even if the job before it fails

### ISSUE THREAD

**Issue by trygve55** [firecow/gitlab-ci-local#658]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
first-job:
  script:
    - exit 1

manual-job:
  when: manual
  needs:
    - first-job
  script:
    - echo "this should not run"

auto-job:
  needs:
    - first-job
  script:
    - echo "works"
```

**Expected behavior**
**manual-job** should not start when **first-job** fails.

**Host information**
Ubuntu 20.04 LTS
gitlab-ci-local 4.35.0

**Additional context**
There two commands:
```bash
gitlab-ci-local first-job manual-job auto-job
gitlab-ci-local --needs manual-job auto-job
```
This is the gitlab-ci-local log:
```
first-job  starting shell (test)
first-job  $ exit 1
first-job  finished in 11 ms  FAIL 1  
manual-job starting shell (test)
manual-job $ echo "this should not run"
manual-job > this should not run
manual-job finished in 8.73 ms

 PASS  manual-job
 FAIL  first-job 
```
