### ISSUE TITLE
Artifacts not being copied over on failure

### ISSUE THREAD

**Issue by grahambryan** [firecow/gitlab-ci-local#662]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
myjob:
  stage: build
  script:
    - echo "my artifact" > artifact.txt
    -  exit 1
  artifacts:
    when: always
    untracked: true
    paths:
      - artifact.txt

myjob2:
  image: ubuntu:18.04
  stage: build
  script:
    - echo "my artifact" > artifact.txt
    - exit 1
  artifacts:
    when: always
    untracked: true
    paths:
      - artifact.txt
```

**Expected behavior**

`artifacts/myjob/artifact.txt`

```bash
$ ls .gitlab-ci-local/
builds   includes output   scripts
```

`artifacts/myjob2/artifact.txt`

```bash
$ ls .gitlab-ci-local/
builds   includes output   scripts
```

**Host information**
Mac (shell environment) / ubuntu:18.04 with docker executor
gitlab-ci-local 4.35.0

* Everything works as intended when passing

Also. side note. I am EXTREMELY happy with this tool. Thank you so much.
