### ISSUE TITLE
Data not copied from container to host when using service container

### ISSUE THREAD

**Issue by ticapix** [firecow/gitlab-ci-local#664]
Hi,

Using gitlab-ci-local  built from https://github.com/firecow/gitlab-ci-local/commit/0919a11010305c1d2f5ce1b20ce0eaf334734c43

and the simple sample from https://gitlab.com/pierre.gronlier/gitlab-ci-local-issue/

I have a different behavior between Gitlab Runner and gitlab-ci-local.

**Minimal .gitlab-ci.yml illustrating the issue**

```yml
test:
  stage: test
  image: docker:stable
  services:
    - docker:dind
  script:
    - echo ${CI_PROJECT_DIR}
    - ls ${CI_PROJECT_DIR}/
    - docker run --name catme --volume ${CI_PROJECT_DIR}/:/docs --interactive --tty -d alpine:latest
    - docker exec catme touch /docs/touchme.txt
    - ls -lh ${CI_PROJECT_DIR}/touchme.txt
  after_script:
    - docker rm --force catme
 ```

**Expected behavior**
https://gitlab.com/pierre.gronlier/gitlab-ci-local-issue/-/jobs/3314139568
```shell
$ docker run --name catme --volume ${CI_PROJECT_DIR}/:/docs --interactive --tty -d alpine:latest
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
ca7dd9ec2225: Pulling fs layer
ca7dd9ec2225: Verifying Checksum
ca7dd9ec2225: Download complete
ca7dd9ec2225: Pull complete
Digest: sha256:b95359c2505145f16c6aa384f9cc74eeff78eb36d308ca4fd902eeeb0a0b161b
Status: Downloaded newer image for alpine:latest
ffb40c49fac023f85023c5c791a85f3fc73b3f440cf51d855a68a5b702bddc3b
$ docker exec catme touch /docs/touchme.txt
$ ls -lh ${CI_PROJECT_DIR}/touchme.txt
-rw-r--r--    1 root     root           0 Nov 12 22:06 /builds/pierre.gronlier/gitlab-ci-local-issue/touchme.txt
```

**Observed behavior**

```shell
debian@work:~/workspace/gitlab-ci-local-issue$ gitlab-ci-local test
parsing and downloads finished in 93 ms
test starting docker:stable (test)
test started service image: docker:dind with aliases: docker in 696 ms
test service image: docker:dind healthcheck passed in 2.9 s
test copied to container in 146 ms
test $ echo ${CI_PROJECT_DIR}
test > /gcl-builds
test $ ls ${CI_PROJECT_DIR}/
test > catme.txt
test $ docker run --name catme --volume ${CI_PROJECT_DIR}/:/docs --interactive --tty -d alpine:latest
test > Unable to find image 'alpine:latest' locally
test > latest: Pulling from library/alpine
test > ca7dd9ec2225: Pulling fs layer
test > ca7dd9ec2225: Verifying Checksum
test > ca7dd9ec2225: Download complete
test > ca7dd9ec2225: Pull complete
test > Digest: sha256:b95359c2505145f16c6aa384f9cc74eeff78eb36d308ca4fd902eeeb0a0b161b
test > Status: Downloaded newer image for alpine:latest
test > 30460899a7e13a4caaa3911f3ce289f5d6dcf249f91a97aee6936b62bc47f14a
test $ docker exec catme touch /docs/touchme.txt
test $ ls -lh ${CI_PROJECT_DIR}/touchme.txt
test > ls: /gcl-builds/touchme.txt: No such file or directory
test finished in 8.78 s  FAIL 1
test copied to container in 158 ms
test $ docker rm --force catme
test > catme
test finished in 11 s

 FAIL  test
  > 30460899a7e13a4caaa3911f3ce289f5d6dcf249f91a97aee6936b62bc47f14a
  > ls: /gcl-builds/touchme.txt: No such file or directory
  > catme
```
