### ISSUE TITLE
Artifacts with absolute paths don't get imported/exported correctly

### ISSUE THREAD

**Issue by trygve55** [firecow/gitlab-ci-local#674]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job_a:
  image:
    name: busybox
  script:
    - echo "$CI_PROJECT_DIR"
    - pwd
    - echo "Hello world" > test.txt
    - realpath test.txt
    - realpath "$CI_PROJECT_DIR/test.txt"
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/test.txt"

job_b:
  image:
    name: busybox
  needs:
    - job_a
  script:
    - ls /gcl-builds/gcl-builds
    - cat "test.txt"
```

**Expected behavior**
This artifact would be at the correct path for job_b.

The artifact appears as `/gcl-builds/gcl-builds/lol/target/test.txt` instead of the correct `/gcl-builds/lol/target/test.txt`.

**Host information**
Ubuntu 20.04 LTS
gitlab-ci-local 4.36.0
