### ISSUE TITLE
Extending from unspecified job error message have job names switched around

### ISSUE THREAD

**Issue by trygve55** [firecow/gitlab-ci-local#679]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  extends: non_existent_job
  script:
    - echo "Hello world!"

```

**Expected behavior**
We get:
`non_existent_job is extended from job, but is unspecified`, but it should be `job is extended from non_existent_job, but is unspecified`.

**Host information**
Ubuntu 20.04
gitlab-ci-local 4.36.1
