### ISSUE TITLE
Manually triggered jobs should not be executed together with other jobs

### ISSUE THREAD

**Issue by kamichal** [firecow/gitlab-ci-local#680]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
manually_triggered_job:
  image: python:3.10
  stage: stage_name
  script:
    - ls -la
  when: manual

```

**Expected behavior**
This job should not be executed among other, regular jobs.

**Host information**
Manjaro
gitlab-ci-local 4.36.1

**Additional context**
According to https://docs.gitlab.com/ee/ci/jobs/job_control.html#create-a-job-that-must-be-run-manually this shouldn't be executed, unless a strict manual trigger is being performed by the used, e.g. typing the job name explicitly:
``` shell
$ gitlab-ci-local manually_triggered_job
```
