### ISSUE TITLE
Using CI_COMMIT_TAG in include:rules seems to have no effect

### ISSUE THREAD

**Issue by peterbbeu** [firecow/gitlab-ci-local#685]
**Minimal .gitlab-ci.yml illustrating the issue**
I made a minimal test case here, but I'll replicate it below:
https://github.com/peterbbeu/gitlab-ci-local-testcase/tree/9bd6877

The output of gitlab-ci-local can be seen here:
https://github.com/peterbbeu/gitlab-ci-local-testcase/actions/runs/3639775229/jobs/6143584731

**.gitlab-ci.yml**
```yml
variables:
  IMAGE_TAG: $CI_COMMIT_REF_SLUG

include:
  - local: ci/version-tag.yml
    rules:
      - if: $CI_COMMIT_TAG

hello-world:
  stage: build
  script:
    - echo $IMAGE_TAG
```

**ci/version-tag.yml**
```yml
variables:
  IMAGE_TAG: $CI_COMMIT_TAG

hello-world2:
  stage: build
  script:
    - echo hello world
```

**Expected behavior**
See these two pipelines:
Branch: https://gitlab.com/petervv/gitlab-ci-test/-/pipelines/715969962
Tag: https://gitlab.com/petervv/gitlab-ci-test/-/pipelines/715970789

I expect the `hello-world2` job to show up in the pipeline list when there's a `CI_COMMIT_TAG`, like happens on gitlab itself. Perhaps the include rule is not being correctly handled in this case?

**Host information**
Ubuntu 20.04
gitlab-ci-local 4.36.1

**Additional context**
Perhaps I'm using the wrong way of providing a tag?
