### ISSUE TITLE
Job declared as optional raises pipeline error if not exists due to rules

### ISSUE THREAD

**Issue by alexander-matthiesen** [firecow/gitlab-ci-local#689]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
skipped-job:
  stage: build
  when: always
  script:
    - echo "Job skipped!"
  rules:
    - when: never

executed-job:
  stage: test
  script:
    - echo "Job executed!"
  needs:
    - job: skipped-job
      optional: true
```

**Expected behavior**
The job `executed-job` should be executed when the `skipped-job` was not added to the pipeline.
(tested same functionality in a gitlab pipeline and it works)

**Assumption**
It might be, that gitlab-ci-local is analyzing the needs before the rules.
