### ISSUE TITLE
Undefined variables should not ba allowed on gitlab ci local

### ISSUE THREAD

**Issue by rroemer** [firecow/gitlab-ci-local#69]
Gitlab will fail with error 
`jobs:<jobname>:variables config should be a hash of key value pairs `
if undefined variables are used, but gitlab-ci-local runs just fine.

**Comment by firecow** [comment]
```
---
test-job:
  variables:
    UNDEF_VAR: ${NON_EXISTING_VAR}
  script:
    - echo "Test something ${UNDEF_VAR}"
```
@rroemer Can you come up with more test cases ?

**Comment by firecow** [comment]
Nvm, I think I found what you guys were experiencing
```
test-job:
  variables:
    UNDEF_VAR: ["Lala"]
  script:
    - echo "Test something ${UNDEF_VAR}"
```
You've basicly been mangling the entire structure of variables, which is probably why you saw this message.
I will reproduce this "variables" validation step as well, so we can noticed such mistakes earlier
