### ISSUE TITLE
Running as root is not recommended

### ISSUE THREAD

**Issue by dannywillems** [firecow/gitlab-ci-local#701]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
  - test-alpine

build-ocaml-4.08-alpine-3.14:
  image: ocaml/opam:alpine-3.14-ocaml-4.08
  stage: test-alpine
  script:
    - echo "hello"
```

**Expected behavior**

See https://gitlab.com/dannywillems/gitlab-ci-local-test-discrepancy/-/jobs/3496300546

**Host information**
Ubuntu
gitlab-ci-local 4.1.33

**Additional context**

The error
```
  > [WARNING] Running as root is not recommended
  > [ERROR] Opam has not been initialised, please run `opam init'
```
comes from the docker image, and it is from `opam`, the OCaml Package Manager. However, it should not make the job fail.
