### ISSUE TITLE
PIP Cache and permissions 

### ISSUE THREAD

**Issue by kferrone** [firecow/gitlab-ci-local#705]
When caching pip packages according to the docs from Gitlab CI itself, this error happens when loading the cache:

> WARNING: The directory '/gcl-builds/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
image: python:3.9
​
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
​
cache:
  paths:
  - .cache/pip
  - venv/
​
before_script:
  - pip install virtualenv # this won't cache and is downloaded every time
  - virtualenv venv
  - source venv/bin/activate
​
install:
  script: # just random packages on top of my mind
  - pip install flake8 kubernetes pyyaml awscli
```

**Expected behavior**
Properly load the cache with the correct user and permissions so PIP doesn't completely rebuild the dependencies. 

**Host information**
Macbook Pro 14 M1 Ventura
gitlab-ci-local 4.36.1

**Additional context**
The docs I based my example on: https://docs.gitlab.com/ee/ci/caching/#cache-python-dependencies

It is only the contents of the `PIP_CACHE_DIR` which have this issue. In the example above I also included the `venv` directory which was loaded just fine. So without venv a 4min build will always take 4min locally with GCL.

**Comment by firecow** [comment]
What runner are you using?
And is `FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR` flag set on that runner?

**Comment by kferrone** [comment]
I am using the Docker runner, which I believe is default correct? I just type `gcl` and Docker is used. 
I have not set or seen this variable: `FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR`. 
To set this variable, can I just export right in terminal then run `gcl`. 
When I simply export the variable as true in the terminal, nothing different happens and the problem persists.

**Comment by firecow** [comment]
I need you to test this using gitlab.com runners, not GCL at all.

Prove to me that this example is in fact functioning on reallife gitlab runners.

**Comment by kferrone** [comment]
I tested on gitlab.com runners and I don't get the error. 
Here is the output from the part where it would get the error. It does say: 'Using cached somepackage'
```
Restoring cache
00:06
Checking cache for default-protected...
Downloading cache.zip from https://storage.googleapis.com/gitlab-com-runners-cache/project/4[20](https://gitlab.com/me/ci-fun/-/jobs/3532188042#L20)16611/default-protected 
WARNING: venv/bin/python: chmod venv/bin/python: no such file or directory (suppressing repeats) 
Successfully extracted cache
Executing "step_script" stage of the job script
00:13
Using docker image sha256:75cc8d87cc34bdb26dfcbe6c9e4483d9b483761510b5069852f52bd8431b8012 for python:latest with digest python@sha256:250990a809a15bb6a3e307fec72dead200c882c9405[23](https://gitlab.com/duplo-kelly/ci-fun/-/jobs/3532188042#L23)fb1694baa78eb0e47c6 ...
$ python -V
Python 3.11.1
$ pip install virtualenv
Collecting virtualenv
  Using cached virtualenv-20.17.1-py3-none-any.whl (8.8 MB)
Collecting distlib<1,>=0.3.6
  Using cached distlib-0.3.6-py2.py3-none-any.whl (468 kB)
Collecting filelock<4,>=3.4.1
  Using cached filelock-3.9.0-py3-none-any.whl (9.7 kB)
Collecting platformdirs<3,>=2.4
  Using cached platformdirs-2.6.2-py3-none-any.whl (14 kB)
Installing collected packages: distlib, platformdirs, filelock, virtualenv
Successfully installed distlib-0.3.6 filelock-3.9.0 platformdirs-2.6.2 virtualenv-20.17.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

Here is the equivalent output from GCL which gives the warning and always fully downloads again:

```
test starting python:latest (test)
test copied to docker volumes in 657 ms
test imported cache 'default' in 396 ms
test $ python -V
test > Python 3.11.1
test $ pip install virtualenv
test > WARNING: The directory '/gcl-builds/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
test > Collecting virtualenv
test >   Downloading virtualenv-20.17.1-py3-none-any.whl (8.8 MB)
test >      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 20.4 MB/s eta 0:00:00
test > Collecting distlib<1,>=0.3.6
test >   Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)
test >      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.5/468.5 kB 23.8 MB/s eta 0:00:00
test > Collecting filelock<4,>=3.4.1
test >   Downloading filelock-3.9.0-py3-none-any.whl (9.7 kB)
test > Collecting platformdirs<3,>=2.4
test >   Downloading platformdirs-2.6.2-py3-none-any.whl (14 kB)
test > Installing collected packages: distlib, platformdirs, filelock, virtualenv
test > Successfully installed distlib-0.3.6 filelock-3.9.0 platformdirs-2.6.2 virtualenv-20.17.1
test > WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

The remote runner is the official gitlab runner from gitlab.com, not a self hosted one. 

Sorry for my lack of understanding here, I'm still a bit lost on how I know if that flag is set or not or even where to set it. I never set it locally or on the remote. Gitlab says that flag is false by default. Exporting it as env var as true or false makes no difference to gcl. Setting the variable inside the variables in `.gitlab-ci.yml` seems to have no effect either. Is there somewhere else I'm supposed to set it like a global runner config for GCL? 

[According to the docs](https://docs.gitlab.com/runner/configuration/feature-flags.html#enable-feature-flag-in-pipeline-configuration), it says I can just set the variable in the ci file. I also tried setting it to true and false for the gitlab.com and gcl. 

Gitlab.com runner does say the following in the output when set to true:

> Not using umask - FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR is set!

This does prove to me at least that that flag is false by default. However, nothing is different on gitlab.com runner and the cache is successfully used with no warning or errors. 

I made an even simpler example showing off the issue: 

```yaml
image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"

cache:
  paths:
  - .cache/pip

install:
  script:
  - pip install pyyaml
```

I tried with other versions of python as well, problem persists.

**Comment by kferrone** [comment]
This is interesting when I added `ls -al`

From gcl:
```
test > drwxr-xr-x 3  501 dialout 4096 Dec 30 20:16 .cache
```

From gitlab itself
```
drwxr-xr-x 3 root root 4096 Dec 30 20:54 .cache
```

**Comment by firecow** [comment]
@kferrone Did you manage to find anything that can be done on MacOS ?

**Comment by geoffreyarthaud** [comment]
Hello ! 

I've got the same issue on Linux (Pop_Os 22.04, derived from ubuntu) :

The result of `ls -al` is : 

```
drwxr-xr-x 1 1000 1000   18 Jan 11 14:35 .cache
...
drwxrwxrwx 1 1000 1000   12 Jan 11 14:43 gcl-builds
```

I think this dir is a protected folder for gcl, as `gcl_builds` folder. The workaround is simply to use another cache folder name for pip !

```
image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache2/pip" # .cache is a reserved dir for gcl

cache:
  paths:
  - .cache2/pip

install:
  script:
  - pip install pyyaml
```

No more warnings, cache is working and the script is compatible with usual runners on gitlab.com.
