### ISSUE TITLE
There is no support for cache:when

### ISSUE THREAD

**Issue by broneq** [firecow/gitlab-ci-local#717]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - exit 1
  cache:
    - when: always
      paths:
        - build
```

**Expected behavior**
Cache will be publish'ed, when job failed

**Host information**
Ubuntu
gitlab-ci-local 4.36.1

**Additional context**
I'll publish Pull Request soon
