### ISSUE TITLE
Artifacts are not imported with `needs: [job: jobname]` syntax

### ISSUE THREAD

**Issue by sh0shin** [firecow/gitlab-ci-local#722]
Created atrtifacts are exported, but not imported in the following stage/job if the `needs: [job: jobname]` syntax is used.

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
  - dump
  - artif

# @Description Dump the artifacts
# @NoArtifactsToSource
dump-artif:
  stage: dump
  image: "alpine:latest"
  script:
    - pwd
    - echo "ARTIF" > artif.txt
    - ls -la $(pwd)
  artifacts:
    paths:
      - artif.txt

# @Description Test the artifacts
test-artif:
  stage: artif
  image: "alpine:latest"
  script:
    - pwd
    - ls -la $(pwd)
    - test -e artif.txt && cat artif.txt || echo no
  needs:
    - job: dump-artif
```

**Expected behavior**
```sh
test-artif $ pwd
test-artif > /gcl-builds
test-artif $ ls -la $(pwd)
test-artif > total 20
test-artif > drwxrwxrwx    4 root     root          4096 Jan 13 11:15 .
test-artif > drwxr-xr-x    1 root     root          4096 Jan 13 11:15 ..
test-artif > drwxrwxrwx    5 root     root          4096 Jan 13 08:16 .git
test-artif > drwxrwxrwx    2 root     root          4096 Oct 12 13:28 .gitlab
test-artif > -rw-rw-rw-    1 root     root            49 Oct 12 13:34 README.md
test-artif > -rw-r--r--    1 root     root             6 Jan 13 11:15 artif.txt
test-artif $ test -e artif.txt && cat artif.txt || echo no
test-artif > ARTIF
```

**Actual behavior**
```sh
test-artif $ pwd
test-artif > /gcl-builds
test-artif $ ls -la $(pwd)
test-artif > total 20
test-artif > drwxrwxrwx    4 root     root          4096 Jan 13 11:15 .
test-artif > drwxr-xr-x    1 root     root          4096 Jan 13 11:15 ..
test-artif > drwxrwxrwx    5 root     root          4096 Jan 13 08:16 .git
test-artif > drwxrwxrwx    2 root     root          4096 Oct 12 13:28 .gitlab
test-artif > -rw-rw-rw-    1 root     root            49 Oct 12 13:34 README.md
test-artif $ test -e artif.txt && cat artif.txt || echo no
test-artif > no
```

**Host information**
macOS
gitlab-ci-local 4.37.0
