### ISSUE TITLE
Crash on erroneous `!reference` usage

### ISSUE THREAD

**Issue by jg-cantaa** [firecow/gitlab-ci-local#738]
given this `gitlab-ci.yml`:

```
.template_job:
  after_script:
    - echo done with something

job_using_references_from_other_jobs:
  script:
    - !reference [.template_job]
    # It should be this instead:
    # - !reference [.template_job,after_script]
```
The program throws the following error message, which does not point to the fact that the usage of `!reference` is erroneous.
```
parsing and downloads finished in 35 ms
job_using_references_from_other_jobs starting shell (test)
TypeError: script.split is not a function
    at /usr/local/lib/node_modules/gitlab-ci-local/src/job.ts:455:34
    at Array.forEach (<anonymous>)
    at Job.generateScriptCommands (/usr/local/lib/node_modules/gitlab-ci-local/src/job.ts:453:17)
    at Job.execScripts (/usr/local/lib/node_modules/gitlab-ci-local/src/job.ts:625:21)
    at Job.start (/usr/local/lib/node_modules/gitlab-ci-local/src/job.ts:363:36)
```

Instead of the current behavior I'd like an error message actually pointing out that the reference usage is invalid.
