### ISSUE TITLE
Jest branch coverage not working

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#746]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
jest:
  coverage: /All files.*?\|.*?\|.*?([\d\.]+)/
  script:
    - echo "File                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s "
    - echo "---------------------|---------|----------|---------|---------|-------------------"
    - echo "All files            |    99.3 |    97.91 |     100 |     100 |                   "
```

**Expected behavior**
I'm expecting coverage percent to show up as 97.91, but it shows 99.3

**Host information**
Ubuntu
gitlab-ci-local 4.38.1
