### ISSUE TITLE
CI_REGISTRY and CI_REGISTRY_IMAGE is not expanded recursively

### ISSUE THREAD

**Issue by udalrich** [firecow/gitlab-ci-local#756]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
  - build

variables:
  RUST_IMAGE: $CI_REGISTRY_IMAGE/rust

build:
  image: docker:19-git
  stage: build
  tags:
    - docker
  script:
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_REGISTRY_IMAGE/rust
    - echo $RUST_IMAGE
```

**Expected behavior**
$ gitlab-ci-local 

```
parsing and downloads finished in 59 ms
build starting docker:19-git (build)
build copied to docker volumes in 914 ms
build $ echo $CI_REGISTRY_IMAGE
build > local-registry.example.com/me/gcl-exp
build $ echo $CI_REGISTRY_IMAGE/rust
build > local-registry.example.com/me/gcl-exp/rust
build $ echo $RUST_IMAGE
build > local-registry.example.com/me/gcl-exp/rust
build finished in 2.13 s

 PASS  build
pipeline finished in 2.27 s
```

**Host information**
Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64
$ gitlab-ci-local --version
4.38.1

**Additional context**

**Actual behavior**
$ gitlab-ci-local 

```
parsing and downloads finished in 59 ms
build starting docker:19-git (build)
build copied to docker volumes in 914 ms
build $ echo $CI_REGISTRY_IMAGE
build > local-registry.example.com/me/gcl-exp
build $ echo $CI_REGISTRY_IMAGE/rust
build > local-registry.example.com/me/gcl-exp/rust
build $ echo $RUST_IMAGE
build > /rust
build finished in 2.13 s

 PASS  build
pipeline finished in 2.27 s
```

When defining the `RUST_IMAGE` variable, `CI_REGISTRY_IMAGE` expands to an empty string.
