### ISSUE TITLE
gcl-cmd: line 4: composer: command not found

### ISSUE THREAD

**Issue by Morgy93** [firecow/gitlab-ci-local#757]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
cypress:run:
  image: cypress/base:16.18.1
  script:
    - echo "hello world"
```

**Error**
```
cypress:run              $ $COMPOSER_BIN --version
cypress:run              > /gcl-cmd: line 4: composer: command not found
```

I have no clue where the gcl-cmd is coming from and why it needs composer. Any idea?

**Host information**
macOS 13.1
gitlab-ci-local 4.38.1
