### ISSUE TITLE
artifact.reports.dotenv is evaluated too late, leading to var expand in next job to be empty

### ISSUE THREAD

**Issue by greenmaid** [firecow/gitlab-ci-local#772]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
  - vars
  - job

vars:
  image: alpine
  stage: vars
  script:
    - echo "MY_VAR=v1" | tee -a vars.env
  artifacts:
    reports:
      dotenv: vars.env

job1:
  image: alpine
  stage: job
  variables:
    EXPANDED_VAR: $MY_VAR
  script:
    - echo "MY_VAR = $MY_VAR / EXPANDED_VAR = $EXPANDED_VAR"
```

**Actual behavior**
```
$ echo "EXPANDED_VAR = $EXPANDED_VAR"
MY_VAR = v1 / EXPANDED_VAR = 
```

**Expected behavior**
```
$ echo "EXPANDED_VAR = $EXPANDED_VAR"
MY_VAR = v1 / EXPANDED_VAR = v1
```

**Host information**
Ubuntu 20.04 WSL
gitlab-ci-local 4.39.0
