### ISSUE TITLE
not specified in --manual ?

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#777]
Hello my friend, long time no see 😊

I ran into this message, which I don't quite understand why it is a blocker :

```
api-admin is when:manual, its needed by infra-aws, and not specified in --manual
```

If a manual job is needed, and not triggered, just ignore the last job, as GitLab do ?

**Host information**
MacOS
gitlab-ci-local 4.1.33

**Comment by firecow** [comment]
@bcouetil Heya... 
Can you paste the whole `.gitlab-ci.yml` or at least the needs graph

**Comment by bcouetil** [comment]
I tried to reproduce with that, exact same rules, but no success :

```

needed:
  stage: 🏗-build
  script: echo "Im needed"
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual

next-job:
  stage: 🏗-build
  needs: [needed]
  script: echo "I need a manual job"
  rules:
    - if: $CI_MERGE_REQUEST_ID
```

Real life pipeline is much more complicated :

<img width="1138" alt="Screenshot 2023-03-09 at 11 45 08" src="https://user-images.githubusercontent.com/42612335/224000932-7c0a0d11-3da8-433d-ace4-a0e4ebedfe16.png">
