### ISSUE TITLE
docker login error: Cannot perform an interactive login from a non TTY device

### ISSUE THREAD

**Issue by typoworx-de** [firecow/gitlab-ci-local#778]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
  - build

build:
  image: docker/compose:latest
  stage: build
  services:
    - docker:dind
  # .. shortened
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - cd ./docker/
```

**Expected behavior**
On gitlab.com the gitlab-ci.yml runs fine, but for some debugging I don't always want to run it there.

This looks like some local issue.

**Host information**
Ubuntu 16.04
gitlab-ci-local 4.28.2

**Additional context**
I have local docker registry:v2 with mkcert ssl cert which works fine with host 'docker push' to it.

Throws error running the ci-pipeline:
```
build           $ docker login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
build            > Error: Cannot perform an interactive login from a non TTY device
```
