### ISSUE TITLE
Expand variables in include fields

### ISSUE THREAD

**Issue by saheerb** [firecow/gitlab-ci-local#780]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
include:
  - project: '${OPEN_IOT_SDK_BASE_GROUP}/tools/developer-tools'
    ref: 1e0fb5dbc3ca75e3379944db42ba5148dfc11d87
    file:
      - '/templates/pipeline-baseline-sdk.yml'
```

With the above `include` I am getting an error 

```
Project include could not be fetched { project: ${OPEN_IOT_SDK_BASE_GROUP}/tools/developer-tools, ref: 1e0fb5dbc3ca75e3379944db42ba5148dfc11d87, file: templates/pipeline-baseline-sdk.yml }
```
`OPEN_IOT_SDK_BASE_GROUP` is defined in `.gitlab-ci-local-variables.yml `

**Expected behavior**
Project is fetched

**Host information**
Mac OS 13.2.1
gitlab-ci-local 4.1.33

**Additional context**
I also tried to hard code,  `OPEN_IOT_SDK_BASE_GROUP` which  also resulted in same error
