### ISSUE TITLE
include default remote-uri for relative includes

### ISSUE THREAD

**Issue by typoworx-de** [firecow/gitlab-ci-local#786]
**Is your feature request related to a problem? Please describe.**
I'm testing gitlab.com ci/cd locally with gitlab-ci-local and this is real good. But I'm also testing around with gitlab.com include.templates like these and I think they're not correctly fetched as they're not using an absolute URI:

```yaml
stages:
  - build
  - test

build:
  stage: build
  # Do something here

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
```
I think the absolute URI should point to this URI in case of gitlab.com template includes:
https://gitlab.com/gitlab-org/gitlab/-/tree/master/lib/gitlab/ci/templates/Jobs/Container-Scanning.gitlab-ci.yml

**Describe the solution you'd like**
I think there's missing a place to define default remote URI to such relative includes.

**Describe alternatives you've considered**
Alternative would be to use absolute URI to includes 'in-place' where they're done. But this would also blow up the yaml code using such an URI multiple times.

Also tried using an Variable there, but obviously it's not being resolved in include.template context and it would be more clean (in respect to the real remote gitlab-ci processing) to keep off such hacks there.
