### ISSUE TITLE
Mixing template & !reference doesn't work?

### ISSUE THREAD

**Issue by typoworx-de** [firecow/gitlab-ci-local#787]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
.docker_build: &docker_build
  image: docker/compose:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_BUILDKIT: 1
    IMAGE_TAG: $CI_REGISTRY_IMAGE/php-$PHP_VERSION:$STAGE
---
build-php82:
  <<: *docker_build
  variables: !reference [.docker_build, variables]
    PHP_VERSION: 8.2
```

**Expected behavior**
Shouldn't it work to expand variables from .docker_build?

for build-php82 it should finally look like this I think, combining variables from .docker_build and build-php82:
```
  variables:
    DOCKER_BUILDKIT: 1
    IMAGE_TAG: $CI_REGISTRY_IMAGE/php-$PHP_VERSION:$STAGE
    PHP_VERSION: 8.2
```

Or do I have something screwed in my code? Looking at this docs it should be possible:
https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#nest-reference-tags-in-script-before_script-and-after_script

**Host information**
gitlab-ci-local 4.39.0

**Comment by typoworx-de** [comment]
I'm not finally sure it work's, but I think my mistake was mixing !reference and the inheritance syntax ```<<: *docker_build``` which I figured out I can replace with ```extends: .docker_build```. Just having to check it works as expected.

Currently testing this which at least began to run without initial errors:
```yaml
---
.docker_build: &docker_build
  image: docker/compose:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_BUILDKIT: 1
    IMAGE_TAG: $CI_REGISTRY_IMAGE/php-$PHP_VERSION:$STAGE
---
build-php82: &build-php82
  extends: .build-php82
  variables: !reference [.docker_build, variables]
    PHP_VERSION: 8.2
```
