### ISSUE TITLE
`gcl-cmd: applet not found` error

### ISSUE THREAD

**Issue by plcarman** [firecow/gitlab-ci-local#793]
First of all, great tool! I am excited to use it more, but I'm having some hiccups getting started.

I have an M1 (arm64) Mac, and I'm trying to run `gitlab-ci-local` against some images that have been built only for `amd64`. I am noticing an error that I can't seem to figure out. I'm not sure if this has something to do with the image itself, or that my laptop's architecture is different than the image's architecture. I am hoping this is me being an idiot and nothing to do with the tool itself. :)  

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
passing-job:
  script:
    - echo "this passes"
  image: alpine:latest


failing-job:
  script:
    - echo "I'm not sure why this fails"
  image: amd64/alpine:latest

```

**Actual behavior**

The job running `amd64/alpine:latest` fails with a `gcl-cmd: applet not found` error.

```
$ gitlab-ci-local 
git remote -v didn't provide valid matches
parsing and downloads finished in 69 ms
failing-job starting amd64/alpine:latest (test)
passing-job starting alpine:latest (test)
passing-job copied to docker volumes in 1.17 s
failing-job copied to docker volumes in 1.21 s
failing-job > gcl-cmd: applet not found
passing-job $ echo "this passes"
passing-job > this passes
failing-job finished in 2.5 s  FAIL 127  
passing-job finished in 2.52 s

 PASS  passing-job
 FAIL  failing-job
  > gcl-cmd: applet not found
pipeline finished in 2.64 s
```

**Expected behavior**
I expect both jobs to pass 🤭

**Host information**
Apple M1 Pro, macOS 13.2.1 (22D68)

gitlab-ci-local 4.39.0

**Additional context**
