### ISSUE TITLE
Support for !reference in parallel.matrix

### ISSUE THREAD

**Issue by fiskhest** [firecow/gitlab-ci-local#806]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
.TEST:
  - NAME: apa
  - NAME: boll

stages:
  - test-stage

test-job:
  image: alpine
  stage: test-stage
  parallel:
    matrix: !reference [.TEST]
  script:
    - echo test
```

**Expected behavior**
Execute testsuite with parallel matrix while expanding the reference

**Host information**
arch linux
gitlab-ci-local 4.39.0

**Additional context**
Currently running `gitlab-ci-local` errors with a `test-job parallel.matrix is not an array`.
