### ISSUE TITLE
GitLab takes the last occurence of coverage, GCL takes the first

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#809]
Hello 👋

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
job:
  script:
    # awk -F"," '{ lines += $8 + $9; covered += $9 } END { print covered, "/", lines, "lines covered"; print 100*covered/lines, "% covered" }' target/site/jacoco/jacoco.csv || echo "0 % covered"
    - echo "88.4176 % covered"
  coverage: /\d+[\.*\d+]* \% covered/
```

This coverage, for jacoco, does not seem to work.

<img width="661" alt="Screenshot 2023-04-05 at 12 15 35" src="https://user-images.githubusercontent.com/42612335/230052292-3f0f8ab2-29de-4a48-a375-677dc2daf4aa.png">

Works on GitLab and https://regex101.com/

On a side note, I suspect that `\%` does not need the escaping, tried OK on https://regex101.com/, not yet on GitLab, but no change on GCL.

**Host information**
MacOS M1
gitlab-ci-local 4.39.0

**Comment by firecow** [comment]
The example you provided, works on my machine.
![image](https://user-images.githubusercontent.com/973602/230679000-4bdd7db7-f2b0-43a7-b3e3-b45599e01aab.png)

There must be more to it.

**Comment by bcouetil** [comment]
You are right this exact example works... Closing it, I will dig into it to see difference with my real world example.

**Comment by bcouetil** [comment]
Found out 🤗

GitLab takes the last occurence of coverage, GCL takes the first.

```
job:
  script:
    - echo "print coverage from files" && echo "or print 0 % covered"
    - echo "88.4176 % covered"
  coverage: /\d+[\.*\d+]* % covered/
```

Gives 0% coverage on GCL, 88.4176 % on GitLab.

If you switch the script lines, you get the right coverage on GCL.
