### ISSUE TITLE
--volume should work before the job name

### ISSUE THREAD

**Issue by bcouetil** [firecow/gitlab-ci-local#810]
Hello 👋

for now, `--volume` has to be after a named job, else the job is ignored and all is launched :

<img width="835" alt="Screenshot 2023-04-05 at 12 23 58" src="https://user-images.githubusercontent.com/42612335/230053987-c091cc4b-98f6-40de-a156-49c26586e168.png">

So I have to write it this way for now : `gitlab-ci-local 📦✅-auth-server-package-and-test --volume my-volume:/host/`

It's then harder to change only the job name when launching multiple times. And I can't easily make an alias for a permanent volume mount, like `--volume /var/run/docker.sock:/var/run/docker.sock`

Or I missed a configuration to set this locally in a project ?

**Comment by firecow** [comment]
You have definently missed this part of the readme.
https://github.com/firecow/gitlab-ci-local#dotenv-file

```bash
export GCL_VOLUME="/var/run/docker.sock:/var/run/docker.sock"
```
Also does the trick.


The order of the cli options `--something` should work where ever you place them.
I'll run some tests to verify.

**Comment by firecow** [comment]
![image](https://user-images.githubusercontent.com/973602/230640161-516ed3c2-675c-4ec4-8d4f-757e6b9a81d9.png)

@bcouetil Everything seems to work just fine.

Feel free to reopen, if this isn't a mistake by you.

**Comment by bcouetil** [comment]
How many jobs in parallel with your test-job ? If there are no other, you cannot experience the bug.

**Comment by bcouetil** [comment]
Trust me, I experience this for months on multiple versions, there is something.

**Comment by firecow** [comment]
So the "bug" is not consistent?

**Comment by bcouetil** [comment]
What I want to say, is that it launchs the whole pipeline instead of the job when arg order is switched.

In your example, the whole pipeline and the single job are the same, if your pipeline consists of one job. I can't say with your screenshot.

Please test with this :

```
test-job-a:
  stage: test
  script: echo "hello world a"

test-job-b:
  stage: test
  script: echo "hello world b"
```

You will have a different behavior depending on the position of the volume arg.

**Comment by bcouetil** [comment]
Yes, this is systematic.

I did not speak about parallelism, but you can see this is the case in my first screenshot.

Sorry I must be not clear enough, I should have given a minimal script in the first place.

**Comment by firecow** [comment]
```
test-job-a:
  stage: test
  script: echo "hello world a"

test-job-b:
  stage: test
  script: echo "hello world b"
```

So, what would I have to execute to see the problem in this example ?

**Comment by bcouetil** [comment]
Let's put it all together in one message for us to understand each other 😅

**Minimal .gitlab-ci.yml illustrating the issue**

```yml
test-job-a:
  stage: test
  script: echo "hello world a"

test-job-b:
  stage: test
  script: echo "hello world b"
```

then :

```
gitlab-ci-local --volume my-volume:/host/ test-job-a
```

Launches both `test-job-a` and `test-job-b` : the argument after `--volume my-volume:/host/` is ignored.

**Expected behavior**

Only `test-job-a` is launched.

**Host information**
MacOS / ZSH
gitlab-ci-local 4.39.0

**Additional context**

<img width="603" alt="Screenshot 2023-04-08 at 09 53 18" src="https://user-images.githubusercontent.com/42612335/230710862-ef285e09-9912-4b80-9717-f273eb34c47f.png">
