### ISSUE TITLE
$VARIABLE not working when passing --variable

### ISSUE THREAD

**Issue by yonixw** [firecow/gitlab-ci-local#818]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stepDirect:
  image: bash
  stage: build
  script:
    - echo c:X=$X #from .gitlab-ci-local-env
    - echo c:CLI_X1=$CLI_X1 #from --variable
    - echo c:CLI_X2=$CLI_X2 #from --variable
```
**.gitlab-ci-local-env**
```
VARIABLE="DOCKER_TLS_CERTDIR=/certs X=Y"
```

**Additional context**
Variables declared in `.gitlab-ci-local-env` are not populated when a `--variable` param is passed. I don't know if it is expected behavior, since multiple `--variable` params act as append.

Here I run with multiple `--variable`, both work, and `$VARIABLE` is ignored :
![image](https://user-images.githubusercontent.com/5826209/232334325-eda1b393-ce52-4f1b-83ba-66fbc8a9ed21.png)

And here I run with no cli variables, so `$VARIABLE` is used:
![image](https://user-images.githubusercontent.com/5826209/232334305-f78a2323-8b0c-4d93-8a82-dbdb40ca39e3.png)

**Expected behavior**
I guess, append `--variable` to `$VARIABLE`, not ignore.

In my case, I had shared variables I put in  `.gitlab-ci-local-env` and some specifiec ones I wanted to update with `--variable` on a case by case scenarios. But for now I moved to use only `--variable` 

**Host information**
Ubuntu
```
gitlab-ci-local --version
4.39.1
```
