### ISSUE TITLE
ENV not present when running gitlab-ci-local

### ISSUE THREAD

**Issue by jakoberpf** [firecow/gitlab-ci-local#819]
**Minimal .gitlab-ci.yml**
```yml
---
# @Description Print out all CI variables for debugging
init:print-vars:
  stage: init
  image: ${CI_IMAGE}/base:${CI_IMAGE_TAG}
  script:
    - |
      echo "MAVEN_OPTS=$MAVEN_OPTS"
```

**Minimal ~/.gitlab-ci-local/variables.yml**
```yml
---
global:
  MAVEN_OPTS: ...
  CI_IMAGE: registry.example.com
  CI_IMAGE_TAG: 1.2.3
```

**Terminal Output**
```bash
parsing and downloads finished in 89 ms
init:print-vars                        starting /base: (init)
Error: Command failed with exit code 1: docker image inspect /base:
Error response from daemon: no such image: base:: invalid reference format
[]
    at makeError (/opt/homebrew/Cellar/gitlab-ci-local/4.39.1/libexec/lib/node_modules/gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/opt/homebrew/Cellar/gitlab-ci-local/4.39.1/libexec/lib/node_modules/gitlab-ci-local/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Job.pullImage (/opt/homebrew/Cellar/gitlab-ci-local/4.39.1/libexec/lib/node_modules/gitlab-ci-local/src/job.ts:681:13)
    at Job.execScripts (/opt/homebrew/Cellar/gitlab-ci-local/4.39.1/libexec/lib/node_modules/gitlab-ci-local/src/job.ts:543:13)
    at Job.start (/opt/homebrew/Cellar/gitlab-ci-local/4.39.1/libexec/lib/node_modules/gitlab-ci-local/src/job.ts:386:36)
```

**Expected behavior**
I did expect that then envs in the image definition would be replaced to resemble `registry.example.com/base:1.2.3`, as they are in the actual GitlabCI. Am I wrong in assuming this or is my setup not correct?

**Host information**
macOS Ventura
gitlab-ci-local 4.39.1
