### ISSUE TITLE
Missing support for premium feature needs:project

### ISSUE THREAD

**Issue by cniry** [firecow/gitlab-ci-local#822]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
jobname:
  script:
    - echo "Heya"
  needs:
    # GITLAB PREMIUM FEATURE - see https://docs.gitlab.com/ee/ci/yaml/#needsproject
    - project: my/other/project
      job: release_version
      ref: master
      artifacts: true
```

**Current behavior**
Checks for local job "release_version" and throws 
`needs: [release_version] for jobname could not be found`

**Expected behavior**
If `needs` entry has `project` field, it is external dependency a it should be silently skipped in validation proces using `gitlab-ci-local --list-all`

**Host information**
Ubuntu
gitlab-ci-local 4.39.0

**Additional context**
Your tool is awesome. I am validating my configuration using `gitlab-ci-local --list-all` but when I use premium feature needs:project, I experiencing validation error now.
