### ISSUE TITLE
Overriding entrypoint to be empty is not compatible with references

### ISSUE THREAD

**Issue by fiskhest** [firecow/gitlab-ci-local#829]
Good day you magical fiery creature of the lands! 😄 I found the below and am unsure if it's a bug or me misunderstanding the merge functionality when extending included jobs. I do believe this is working on gitlab-ci, so I figured I'd at least ask. I had to mock the setup to redact secrets, I hope I got it right but just in case something doesn't match or you need more info lmk.

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
# see separate code block for content
include:
  - project: 'some-group/templates'
    file: 'common.yaml'

stages:
  - test

test1:
  stage: test
  extends: .common/some-job
  when: always
  image:
    name: !reference [.common/ci-image]
    entrypoint: ['']
  script:
    - echo $SHELL

test2:
  image:
    name: <redacted_registry_url>/ci-image
    entrypoint: ['']
  when: always
  stage: test
  script:
    - echo $SHELL
```
the included file `some-group/templates/common.yaml`  looks like
```yml
---
.common/ci-image: "<redacted_registry_url>/ci-image"

.common/some-job:
  image: !reference [.common/ci-image]
  [...]
  script:
    - echo $SHELL
```

**Expected behavior**
I would expect both `test1` and `test2` to pass since they are identical and my use case is to overwrite the entrypoint. However, this currently yields the following result when I execute this locally:
```
❮ gitlab-ci-local --mount-cache --volume /var/run/docker.sock:/var/run/docker.sock --file .gitlab-ci-test.yml
parsing and downloads finished in 149 ms
test2 starting <redacted_registry_url>/ci-image (test)
test1 starting <redacted_registry_url>/ci-image (test)
test2 copied to docker volumes in 1.37 s
test1 copied to docker volumes in 1.43 s
test2 $ echo $SHELL
test2 > /bin/ash
test1 > /entrypoint.sh: line 6: SOME_BOOTSTRAP_VAR1: unbound variable
test1 > /entrypoint.sh: line 7: SOME_BOOTSTRAP_VAR2: unbound variable
test2 finished in 2.86 s
test1 finished in 3 s  FAIL 1

 PASS  test2
 FAIL  test1
  > /entrypoint.sh: line 6: SOME_BOOTSTRAP_VAR1: unbound variable
  > /entrypoint.sh: line 7: SOME_BOOTSTRAP_VAR2: unbound variable
pipeline finished in 3.27 s
```

**Host information**
Arch linux
gitlab-ci-local 4.39.0

**Additional context**
For good measure, here's a --preview aswell:
```
parsing and downloads finished in 148 ms
---
stages:
  - .pre
  - test
  - .post
test1:
  image:
    name: <redacted_registry_url>/ci-image
  script:
    - echo $SHELL
  when: always
  stage: test
test2:
  image:
    name: <redacted_registry_url>/ci-image
    entrypoint:
      - ''
  when: always
  stage: test
  script:
    - echo $SHELL
```

**Comment by firecow** [comment]
I shall check it out in my gitlab ci debugging project, oh mighty horse of the sea !! :smile:

**Comment by fiskhest** [comment]
👍🏼 I tried replacing the image with alpine and was unable to reproduce the crash, but preview still says one of them does not have it's entrypoint overwritten, which is my actual use case. Here's my .gitlab-ci.yml:
```
include: 'common-test.yaml'

stages:
  - test

test1:
  stage: test
  extends: .common/some-job
  when: always
  image:
    name: !reference [.common/ci-image]
    entrypoint: ['']
  script:
    - echo $SHELL

test2:
  image:
    name: alpine
    entrypoint: ['']
  when: always
  stage: test
  script:
    - echo $SHELL
```

And the preview:
```
---
stages:
  - .pre
  - test
  - .post
test1:
  image:
    name: alpine
  script:
    - echo $SHELL
  when: always
  stage: test
test2:
  image:
    name: alpine
    entrypoint:
      - ''
  when: always
  stage: test
  script:
    - echo $SHELL
```

**Comment by firecow** [comment]
Much easier example, thanks 👍

**Comment by firecow** [comment]
```--yml
---
.common/ci-image: "alpine"
.common/some-job:
  image: !reference [.common/ci-image]

test1:
  extends: .common/some-job
  image:
    name: !reference [.common/ci-image]
    entrypoint: ['']
  script:
    - echo "test hest"
```

```
mjn@mjn-laptop:~/workspace/mjn-gitlab-ci-debugging$ gitlab-ci-local --preview
parsing and downloads finished in 43 ms
---
stages:
  - .pre
  - build
  - test
  - deploy
  - .post
test1:
  image:
    name: alpine
  script:
    - echo "test hest"
```

Here is the smallest possible example illustrating the issue.

It must have something to do, with extends or reference expansion.
