### ISSUE TITLE
Allow needs to use the parallel keyword

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#843]
https://gitlab.com/gitlab-org/gitlab/-/issues/254821 Is not in release candidate.

```yaml
test:
  needs:
    - job: build
      parallel:
        matrix:
          - PLATFORM: ubuntu
            STACK: [ruby, python]

# depends on build[ubuntu, ruby] and build[ubuntu, python]
```

```yaml
test:
  needs:
    - job: build
      parallel:
        matrix:
          - PLATFORM: ubuntu

# depends on build[ubuntu, *]
```

```yaml
test:
  needs:
    - job: build
      parallel:
        matrix:
          - PLATFORM: ubuntu
            STACK: []

# depends on build[ubuntu]
```
