### ISSUE TITLE
Files seem not to be cached at all 

### ISSUE THREAD

**Issue by akohlbecker** [firecow/gitlab-ci-local#857]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages: 
  - prepare
  - cleanup
  - test

prepare-files-job:
  stage: prepare
  cache:
    key: var-files-cache
    paths:
      - the-file.txt
  script:
    - echo "the file content" > the-file.txt # the-file.txt is expected to be put into the cache
  
cleanup-job:
  stage: cleanup
  script:
    - rm the-file.txt

test-cached-file-job:
  stage: test
  cache:
    key: var-files-cache
    paths:
      - the-file.txt
  script:
    - cat the-file.txt # fails !

```

**Expected behavior**
The file `the-file.txt` is expected to be put into the cache, but there is no notion of cache usage in the log. 
Also, removing `the-file.txt` in the intermediate job causes the last job to fail as the  var-files-cache is apparently not being used at all.

**Host information**
Ubuntu
gitlab-ci-local 4.38.0 and latest (2023-05-12)
