### ISSUE TITLE
override parallel matrix job, like gitlab.com

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#860]
```
---
test-job:
  parallel:
    matrix:
      - SITE: denmark
        TIER: stage
      - SITE: sweden
        TIER: stage
  script: echo "Ok"

"test-job: [denmark, stage]":
  script: echo "Over"
```

```
mjn@mjn-laptop:~/workspace/mjn-gitlab-ci-debugging$ gitlab-ci-local --list
parsing and downloads finished in 46 ms
name                        description  stage   when        allow_failure  needs
test-job [denmark,stage]                 test    on_success  false      
test-job [sweden,stage]                  test    on_success  false      
test-job: [denmark, stage]               test    on_success  false 
```

![image](https://github.com/firecow/gitlab-ci-local/assets/973602/191dd03a-b725-45b7-9866-c9ef5b2a9c1b)

test-job: [denmark,stage] actually prints "Over"
