### ISSUE TITLE
Fail without any error code

### ISSUE THREAD

**Issue by SomaGallai** [firecow/gitlab-ci-local#861]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
default:
  image: docker:latest
  services:
    - docker:23.0.3-dind
stages:
 - build

initial-build-hello:
  stage: build
  script:
    - echo "Empty step to trigger pipeline."
```

**Expected behavior**
No public URL, but should echo `Empty step to trigger pipeline.` and succeed.

**Host information**
MacOS Ventura 13.3.1
gitlab-ci-local 4.40.1

**Additional context**
Actual behaviour/output:
```bash
$ gitlab-ci-local         
parsing and downloads finished in 31 ms
initial-build-hello               starting docker:latest (build)
initial-build-hello               copied to docker volumes in 504 ms

 FAIL  initial-build-hello              
pipeline finished in 743 ms
```
