### ISSUE TITLE
Service specific variables aren't supported

### ISSUE THREAD

**Issue by repomaa** [firecow/gitlab-ci-local#862]
Passing service specific variables has no effect.

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  services:
    - name: busybox
      variables:
        TEST: foobar
      command:
        - env
  script:
    - echo "Heya"
```

**Expected behavior**
I would expect to see TEST=foobar in the logs for the service

**Additional information**
I had a quick look at the code for service and think it would be pretty straight forward to add.
