### ISSUE TITLE
`extends` values parsed incorrectly when jobs are defined out of order

### ISSUE THREAD

**Issue by nfeltrin-dkb** [firecow/gitlab-ci-local#880]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
.template-1:
  image: alpine:latest

job:
  extends: .template-2

.template-2:
  extends: .template-1
  script:
    - echo "Hello World"
```

**Unexpected behavior**

```sh
gitlab-ci-local job 
Using fallback git commit data
Using fallback git remote data
. is unspecified, used by .template-2 extends
```

**Expected behavior**

```sh
gitlab-ci-local job 
Using fallback git commit data
Using fallback git remote data
parsing and downloads finished in 59 ms
job starting alpine:latest (test)
job copied to docker volumes in 771 ms
job $ echo "Hello World"
job > Hello World
job finished in 1.81 s

 PASS  job
```

**Host information**
MacOS 13.4 (Intel)
gitlab-ci-local 4.41.0 (brew)

**Additional context**
The issue is quite strange. The expected result can be achieved by making the extend into an explicit list OR by changing the order of the jobs; working examples:

```yml
.template-1:
  image: alpine:latest

job:
  extends:
    - .template-2

.template-2:
  extends: .template-1
  script:
    - echo "Hello World"
```

```yml
.template-1:
  image: alpine:latest

.template-2:
  extends: .template-1
  script:
    - echo "Hello World"
 
job:
  extends: .template-2
```

I guess that the value of `extends` is parsed as a list of chars (so it's trying to find a job named `.` instead of `.template-1`), but I can't figure out why the order of the jobs would matter 🤔 a (much more complex) version of the problematic definition runs in gitlab without issue...

If more information/tests are needed, please let me know and I'll do my best to provide it :) thank you very much for the awesome project!
