### ISSUE TITLE
image: !reference is broken

### ISSUE THREAD

**Issue by fiskhest** [firecow/gitlab-ci-local#890]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
include: 'common-lib.yaml'

stages:
  - plan
  - change-notifications

plan:
  stage: plan
  image: alpine
  script:
    - echo "hi"

notify-on-change:
  stage: change-notifications
  image: !reference [.common/util-image]
  script:
    - echo "bye"
```
**common-lib.yaml**
```yml
.common/util-image: "alpine"
```

**Expected behavior**
That gitlab-ci-local will execute successfully

**Host information**
Arch Linux
gitlab-ci-local 4.41.1

**Additional context**
This has to my knowledge been working fine previously.

Currently errors out with the following stderr:
```
❯ gitlab-ci-local --list
TypeError: Cannot read properties of undefined (reading 'includes')
    at Job.get imageName [as imageName] (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/job.ts:267:26)
    at new Job (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/job.ts:211:18)
    at /home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/parser.ts:147:29
    at Function.forEachRealJob (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/utils.ts:52:13)
    at Parser.init (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/parser.ts:135:15)
    at Function.create (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/parser.ts:57:9)
    at handler (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/handler.ts:91:18)
    at Object.handler (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/index.ts:25:34)
```

This was reproduced in a completely new git repo with the following dir contents:
```
❯ ls -la
total 12
drwxr-xr-x  3 johan johan  120 May 30 09:27 .
drwxrwxrwt 77 root  root  9100 May 30 09:28 ..
-rw-r--r--  1 johan johan   29 May 30 09:25 common-lib.yaml
drwxr-xr-x  8 johan johan  260 May 30 09:25 .git
-rw-r--r--  1 johan johan  250 May 30 09:21 .gitlab-ci.yml
```

If I comment out the `change-notifications` stage/job, `gitlab-ci-local` executes successfully
