### ISSUE TITLE
$CI_REGISTRY_IMAGE should be lowercase

### ISSUE THREAD

**Issue by niki9796dk** [firecow/gitlab-ci-local#893]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - echo $CI_REGISTRY_IMAGE
```

**Expected behavior**
example repo path: `niki9796dk/MyProject`

local-registry.gitlab.com/niki9796dk/myproject

**Actual behavior**
local-registry.gitlab.com/niki9796dk/MyProject

**Host information**
Ubuntu
gitlab-ci-local 4.1.33
