### ISSUE TITLE
paths is always needed when using cache keyword

### ISSUE THREAD

**Issue by aka2dev** [firecow/gitlab-ci-local#898]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
  - test
testjob:
  stage: test
  image: alpine:latest
  script:
    - echo "Hello World"
  cache:
    - key: $CI_COMMIT_REF_SLUG
```

**Unexpected behavior**
 ~/projects/github-bugreport  gitlab-ci-local testjob

Using fallback git commit data
Using fallback git remote data
**testjob cache[0].paths must be array**

**Expected behavior**
(By commenting out the cache part in .gitlab-ci.yml)
 ~/projects/github-bugreport  gitlab-ci-local testjob

Using fallback git commit data
Using fallback git remote data
parsing and downloads finished in 21 ms
testjob starting alpine:latest (test)
testjob copied to docker volumes in 489 ms
testjob $ echo "Hello World"
testjob > Hello World
testjob finished in 1.02 s

**Host information**
MacOS 13.3.1 
gitlab-ci-local 4.41.2

**Additional context**
It expects always an array for "paths". In many cases we don't need "paths" in Gitlab. 
"paths" in cache should be optional

**Comment by firecow** [comment]
What does it default to?

**Comment by firecow** [comment]
It copies the files/folders to a hidden folder, and copies it to the build folders that utilize the same cache keys.

**Comment by firecow** [comment]
Ok, `cache: { key: something }` effectively mean, cache disable on gitlab.com

Nothing happens on cache pull or cache push steps in the job log output.

`gitlab-ci-local` should act the same way.

**Comment by aka2dev** [comment]
I agree firecow 👍 if a paths is given, it has to be checked!

**Comment by aka2dev** [comment]
```yaml
stages:
  - test
  
create-cache:
  stage: test
  image: alpine:latest
  script:
    - echo "Hello World" > /some/path/file.txt
  cache:
    - key: $CI_COMMIT_REF_SLUG
        path: /some/path

use-cache:
  stage: test
  image: alpine:latest
  script:
    - cat /some/path/file.txt
    - rm /some/path/file.txt
  cache:
    - key: $CI_COMMIT_REF_SLUG
        policy: pull
  needs:
    - create-cache

use-cache-2:
  stage: test
  image: alpine:latest
  script:
    - cat /some/path/file.txt
  cache:
    - key: $CI_COMMIT_REF_SLUG
        policy: pull
  needs:
    - create-cache
```

This should be closer to what we have in our pipelines... I would expect gitlab-ci-local to:
- be able to run the jobs without complaining that in the second case the path is not defined
- be able to run the second job after the first and being able to access the cached file
- not remove the file from the hidden folder, so that use-cache-2 would still work (in gitlab.com the amended cache would not have been updated because of the pull only policy)
