### ISSUE TITLE
Multiple cross-document references causes errors

### ISSUE THREAD

**Issue by fiskhest** [firecow/gitlab-ci-local#899]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
include: 'common-lib.yaml'

stages:
  - plan
  - change-notifications

plan:
  stage: plan
  image: alpine
  script:
    - echo "hi"

notify-on-change:
  stage: change-notifications
  image: !reference [.common/util-image]
  script:
    - echo "bye"
```

**common-lib.yaml**
```yml
include: other-lib.yaml
.common/util-image: !reference [.other/image]
```

**other-lib.yaml**
```yml
.other/image: "bash"
```

**Expected behavior**
That gitlab-ci-local will execute successfully

**Host information**
Arch Linux
gitlab-ci-local 4.41.2

**Additional context**
This works on a self-hosted gitlab-instance.

Currently errors out with the following stderr:
```
❯ gitlab-ci-local --preview
TypeError: Cannot read properties of undefined (reading 'includes')
    at Job.get imageName [as imageName] (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/job.ts:267:26)
    at new Job (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/job.ts:211:18)
    at /home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/parser.ts:147:29
    at Function.forEachRealJob (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/utils.ts:52:13)
    at Parser.init (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/parser.ts:135:15)
    at Function.create (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/parser.ts:57:9)
    at handler (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/handler.ts:78:18)
    at Object.handler (/home/johan/.nvm/versions/node/v18.13.0/lib/node_modules/gitlab-ci-local/src/index.ts:25:34)

```

This was reproduced in a completely new git repo with the following dir contents:
```
❯ ls -la
total 12
drwxr-xr-x  3 johan johan   120 Jun  5 14:55 .
drwxrwxrwt 80 root  root  25160 Jun  5 14:57 ..
-rw-r--r--  1 johan johan    70 Jun  5 14:55 common-lib.yaml
drwxr-xr-x  8 johan johan   260 May 30 09:25 .git
-rw-r--r--  1 johan johan   250 May 30 23:00 .gitlab-ci.yml
-rw-r--r--  1 johan johan    21 Jun  5 14:55 other-lib.yaml
```

I'm sorry 😢
