### ISSUE TITLE
Single reference (i.e. no array) in services field results in a TypeError

### ISSUE THREAD

**Issue by jameshi16** [firecow/gitlab-ci-local#904]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
  - minimal_example

.something-to-ref:
  services:
    - name: "alpine:latest"

minimal_example:
  stage: minimal_example
  services: !reference [.something-to-ref, services]
  script: echo "hello world"
```

**Expected behavior**
https://gitlab.com/jameshi16/gitlab-ci-local-services-issue/-/jobs/4485354756 (green pipeline)

There are two problems here:
- https://github.com/firecow/gitlab-ci-local/blob/master/src/data-expander.ts#L151 reassigns `jobData.services = services`, which basically invalidates the line before.
- If a reference is passed directly without being in a YAML array, an object, like `{ referenceData: [ '.something-to-ref', 'services'] }` is given to the `reference` function call, which doesn't get parsed right, and also results in a `TypeError` (`jobData.services.flat` is not a function)

**Host information**
Ubuntu
gitlab-ci-local 4.1.33

**Additional context**
I'll open a PR shortly in an attempt to fix the issues above, and link it to this issue.
