### ISSUE TITLE
Script containing !reference named `cache` fails

### ISSUE THREAD

**Issue by fschrempf** [firecow/gitlab-ci-local#909]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
.scripts:
  cache:
    - echo TEST

job:
  script:
    - !reference [.scripts, cache]
```

results in:

```
test script contains non string value
```

whereas this works fine:

```yml
---
.scripts:
  test:
    - echo TEST

job:
  script:
    - !reference [.scripts, test]
```

**Expected behavior**

```
cache starting shell (cache)
cache $ echo TEST
cache > TEST
cache finished in 11 ms

PASS  cache
```

**Host information**
Arch/Manjaro
gitlab-ci-local 4.41.2
