### ISSUE TITLE
Missing limit on cache:key:files:

### ISSUE THREAD

**Issue by atli-c** [firecow/gitlab-ci-local#910]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
example_job:
  script:
    - echo "Heya"
  cache:
    key:
      files: [foo.txt, bar.txt, oh-no-too-many-files-for-cache-key.txt]
```
gitlab-ci-local works, but gitlab (EE 15.11) fails with:
> Unable to create pipeline
> * jobs:example_job:cache:key:files config has too many items (maximum is 2)

**Expected behavior**
gitlab-ci-local should fail the same way. I.e. max 2 cache key files.

**Host information**
macOS Ventura 13.4
gitlab-ci-local 4.40.0

**Additional context**
n/a
