### ISSUE TITLE
Concurrent jobs with docker login (dind)

### ISSUE THREAD

**Issue by dfyz011** [firecow/gitlab-ci-local#918]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
stages:
  - build

job:
  stage: build
  services:
    - docker:dind
  image: docker:latest
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
job2:
  stage: build
  services:
    - docker:dind
  image: docker:latest
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
```

**Expected behavior**
concurrent jobs runs ok (same as in gitlab-ci)

**Host information**
Macos 13.4 (22F66)
gitlab-ci-local 4.41.2

**Additional context**
Hello.
When I try to run more that 1 job at the same time (stage).
```sh
gitlab-ci-local --cleanup --stage build
```
where in each stage i need to do "docker login". Only one job will login. success and other will fail with this error:
`error during connect: Post "https://docker:2376/v1.24/auth": tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "docker:dind CA"`
<img width="1036" alt="Снимок экрана 2023-07-03 в 07 50 17" src="https://github.com/firecow/gitlab-ci-local/assets/45315708/fa8e1a9d-f31f-4f5a-b48c-295490df04b5">
But run them separate is ok.
Here is my `.gitlab-ci-local-env` as in your dind example
```sh
PRIVILEGED=true
ULIMIT=8000:16000
VOLUME=certs:/certs/client
VARIABLE="DOCKER_TLS_CERTDIR=/certs"
```
Here is my `.gitlab-ci-local-variables.yml` (i use registry from gitlab, you need to provide your user and deploy-token)
```yml
CI_REGISTRY: "registry.gitlab.com"
CI_REGISTRY_USER:
CI_JOB_TOKEN:
```

Thank you!
