### ISSUE TITLE
parallel matrix artifacts are not copied

### ISSUE THREAD

**Issue by naweiss** [firecow/gitlab-ci-local#923]
Using the following .gitlab-ci.yml file:
```yml
stages:
    - prebuild
    - build

setup:
    image: ubuntu:18.04
    stage: prebuild
    parallel:
        matrix:
            - FILE_NAME: [aaaa, bbbb]
    script:
        - touch "${FILE_NAME}"
    artifacts:
        paths:
            - ./${FILE_NAME}

build_package:
    image: ubuntu:18.04
    stage: build
    script:
        - cat aaaa
        - cat bbbb
```

You get the following error:
```
build_package > cat: aaaa: No such file or directory
```

**Expected behavior**
The expected behaviur is that the build_package job will finish successfully like [here](https://gitlab.com/naweiss/gitlab-ci-local-testing/-/jobs/4614933576)

**Host information**
Ubuntu 20.04
gitlab-ci-local 4.41.2

**Additional context**
It is important to notice that if you add to build_package:
```yml
build_package:
    needs: 
        - setup
```
gitlabi-ci-local print the correct output.

And, if you does not use parallel matrix for setup like so:
```yml
setup:
   ...
    variables:
        FILE_NAME: aaaa
...
build_package:
    ...
    script:
        - cat aaaa
```
gitlabi-ci-local also print the correct output.

**Comment by firecow** [comment]
I'm able to reproduce. 

This is a bug with the "old way of needing" jobs.

If you add `needs: [setup]` to `build_package` job is works as it should
```
stages:
  - prebuild
  - build

setup:
  image: ubuntu:18.04
  stage: prebuild
  parallel:
    matrix:
      - FILE_NAME: [aaaa, bbbb]
  script:
    - touch "${FILE_NAME}"
  artifacts:
    paths:
      - ./${FILE_NAME}

build_package:
  needs: [setup]
  image: ubuntu:18.04
  stage: build
  script:
    - cat aaaa
    - cat bbbb
 ```
