### ISSUE TITLE
limit concurrency

### ISSUE THREAD

**Issue by naweiss** [firecow/gitlab-ci-local#925]
You can reach a big number parallel jobs very easily using a CI script like the following:
```yml
setup:
    image: ubuntu:18.04
    parallel:
        matrix:
            - FILE_NAME: [a, b, c]
            - DIR_NAME: [a, b, c]
    script:
        - mkdir "${DIR_NAME}"
        - touch "${DIR_NAME}/${FILE_NAME}"
```
I'm using an Ubuntu VM for deveopment and since the VM has low resources this scripts causes the VM to be compeletly stuck. 
Currently there is no way to solve this problem. I think it will be greate if we could offer some option to limit the number of concurrenct tasks.
