### ISSUE TITLE
Show warning on remote project triggers instead of exiting

### ISSUE THREAD

**Issue by Guits32** [firecow/gitlab-ci-local#929]
**Is your feature request related to a problem? Please describe.**
The related gitlab documentation - [specify-a-branch-for-multi-project-pipelines](https://docs.gitlab.com/ee/ci/pipelines/downstream_pipelines.html#specify-a-branch-for-multi-project-pipelines)
Exemple of CI

```yaml
deploy-exemple:
  stage: deploy
  trigger:
    project: mytarget/project
    branch: master
```

Currently this job is not working. It crash with this trace:
```bash
TypeError: Cannot read properties of undefined (reading 'split')
    at /home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/job.ts:559:34
    at Array.forEach (<anonymous>)
    at Job.generateScriptCommands (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/job.ts:557:17)
    at Job.execScripts (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/job.ts:705:21)
    at Job.start (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/job.ts:458:36)
    at async Promise.all (index 0)
    at Function.runLoop (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/executor.ts:17:13)
    at Function.runJobs (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/commander.ts:79:9)
    at handler (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/handler.ts:112:9)
    at Object.handler (/home/gaufrere/.nvm/versions/node/v18.16.1/lib/node_modules/gitlab-ci-local/src/index.ts:25:34)
```

If I add to the job a `script` statement it runs successfully, but the trigger is not launched.

I check this issue [94](https://github.com/firecow/gitlab-ci-local/issues/94) but I think it doesn't answer to this use case.

**Describe the solution you'd like**
Trigger the remote CI properly.

[Edited]
**Describe the expected behavior**
Do not crash, show a warning on remote project trigger.

**Comment by firecow** [comment]
Gitlab CI Local shouldn't fail hard here.

But I'm not sure if we want to actually implementing spawning remote pipelines.

**Comment by Guits32** [comment]
Ok, after thinking about it I think indeed it's not a good idea.

**Comment by firecow** [comment]
Rename the title to "show warning on remote project triggers instead of exiting"

**Comment by firecow** [comment]
```
---
pipe-gen-job:
  stage: build
  variables:
    VAR_FROM_ANOTHER_MOTHER: "echo me i'm generated"
  artifacts:
    paths: [.gitlab-ci-child.yml]
  script:
    - cat .gitlab-ci.tmpl | envsubst > .gitlab-ci-child.yml

include-trigger:
  stage: test
  trigger:
    include:
      - artifact: .gitlab-ci-child.yml
        job: pipe-gen-job

remote-trigger:
  trigger:
    project: mytarget/project
    branch: master
```

Outputs 
![image](https://github.com/firecow/gitlab-ci-local/assets/973602/bd7cc5ee-a7c0-490d-a4aa-d4cc47410179)

You shouldn't by any change run a very old `gitlab-ci-local --version` @Guits32
