### ISSUE TITLE
Home file variables - envrionment variable issue

### ISSUE THREAD

**Issue by Guits32** [firecow/gitlab-ci-local#931]
**Minimal .gitlab-ci.yml illustrating the issue**
Here is my local variable config (/home/$USER/.gitlab-ci-local/variables.yml):

```yml
project:
  gitlab.fr/exemple:
    MY_EXEMPLE_VAR:
      type: variable
      values:
        '*': not_production_value
        'prod': production_value
```

Here is an exemple CI job:
```yml
---
job:
  environment:
    name: preproduction
  script:
    -  echo "${MY_EXEMPLE_VAR}"
```

This will output:
```bash
job       $ echo "${MY_EXEMPLE_VAR}"
job       > production_value
```

The variable `MY_EXEMPLE_VAR` take the `prod` value while I was expecting it to take the `*` value.

**Expected behavior**

I would expect:

```bash
job       $ echo "${MY_EXEMPLE_VAR}"
job       > not_production_value
```

**Host information**
Debian 11
gitlab-ci-local 4.41.2

**Additional context**

My assumption is that the check on the environment is valid if the variable file environment value is a substring of the job environment value.

In my exemple above: `prod` is a substring of `preproduction`.

For exemple, I tested to updated the value of the home file variable environment:
```yml
project:
  gitlab.fr/exemple:
    MY_EXEMPLE_VAR:
      type: variable
      values:
        '*': not_production_value
        '__prod__': production_value
```

And now my variable is set to the rigth value.
