### ISSUE TITLE
Jobs with trigger, should automatically spawn the generated pipeline

### ISSUE THREAD

**Issue by firecow** [firecow/gitlab-ci-local#94]
This missing feature can be "circumvented" by using the --file parameter

```shell
gitlab-ci-local
gitlab-ci-local --file yml-generated-by-first-run.yml
```

**Comment by jsnordhealth** [comment]
I'm not sure if this is why I can't trigger pipelines.

I'm trying to do something like

`.gitlab-ci.yml`
```
trigger_job:
  variables:
    MY_VAR: world
  trigger:
     include: path/to/local-pipeline.yml
````

`path/to/local-pipeline.yml``
```
child-job:
  script:
    - echo "Hello $MY_VAR"
```

I would expect the jobs in the child pipeline to run and echo "Hello world" I don't understand how this workaround would help with trigger jobs.
