### ISSUE TITLE
Unexpected conversion of a variable starting with "/" from .gitlab-ci-local-variables.yml

### ISSUE THREAD

**Issue by Jony321** [firecow/gitlab-ci-local#950]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
printenv:
  script:
    - printenv | grep TEST
```

**Expected behavior**
If
```
$ cat .gitlab-ci-local-variables.yml 
TEST: "/asdfasd"
```
Expected
```
$ gitlab-ci-local --cleanup printenv
parsing and downloads finished in 86 ms
printenv starting shell (test)
printenv $ printenv | grep TEST
printenv > TEST=/asdfasdf
printenv finished in 15 ms
```
But now I get
```
$ gitlab-ci-local --cleanup printenv
parsing and downloads finished in 94 ms
printenv starting shell (test)
printenv $ printenv | grep TEST
printenv > TEST=/tmp/gitlab-ci-local-file-variables-fallback.group-fallback.project-92103/TEST
printenv finished in 37 ms
```

**Host information**
Ubuntu (22.04), Alpine (3.18)
gitlab-ci-local 4.41.2

**Additional context**
I've noticed strange behavior when using variable values that start with "/". Such variables are unexpectedly converted to a path, which, of course, incorrectly affects the CI.
I can be wrong, but it seems that this should not be, because. the problem arises even if the path (/var/log, for example) will act as the value of the variable.

**Comment by firecow** [comment]
Its not unexpected, it's just stupid 🤣

Use 

```yml
TEST: 
  type: variable
  values:
    '*': "/asdfasd"
```

This will be changed in 5.x.x, but its a breaking change.

**Comment by JZubero** [comment]
Just ran into the very same thing. Maybe adding this to the docs until v5 lands?

**Comment by Jony321** [comment]
> Just ran into the very same thing. Maybe adding this to the docs until v5 lands?

If you're interested, I fixed this issue on my local fork and attached a screenshot.
Since this change I haven't had any problems with slashes in variable values and have been using my fork successfully, but I can't guarantee that these changes won't break something for you.

![Screenshot from 2023-10-27 14-09-10](https://github.com/firecow/gitlab-ci-local/assets/58134781/1bfa8291-745c-49c9-afb8-e1db7277fc41)

**Comment by JZubero** [comment]
Great, thanks @Jony321. I'll use this as my workaround until v5.

**Comment by firecow** [comment]
The / "bug" isn't present if you are a little more explicit if you be a little more specific by using type:variable in variables files.

```
project:
  gitlab.com/test-group/test-project.git:
    # Will be type Variable and only available if remote is exact match
    AUTHORIZATION_PASSWORD: djwqiod910321
  gitlab.com:project/test-group/test-project.git: # another syntax
    AUTHORIZATION_PASSWORD: djwqiod910321

group:
  gitlab.com/test-group/:
    # Will be type Variable and only available for remotes that include group named 'test-group'
    DOCKER_LOGIN_PASSWORD: dij3213n123n12in3

global:
  # Will be type File, because value is a file path
  KNOWN_HOSTS: '~/.ssh/known_hosts'
  DEPLOY_ENV_SPECIFIC:
    type: variable # Optional and defaults to variable
    values:
      '*production*': 'Im production only value'
      'staging': 'Im staging only value'
  FILE_CONTENT_IN_VALUES:
    type: file
    values:
      '*': |
        Im staging only value
        I'm great for certs n' stuff
```
