### ISSUE TITLE
!reference doesn't work in project default before_script/after_script

### ISSUE THREAD

**Issue by atli-c** [firecow/gitlab-ci-local#954]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
.hidden:
  script:
    - echo Hello from ${CI_JOB_NAME}

normal_job:
  image: alpine
  before_script:
    - !reference [.hidden, script]  # before_script and after_script under a job work
  script:
    - !reference [.hidden, script]  # This also works
  #after_script:
  # - !reference [.hidden, script]  # Uncommenting the job after_script makes it work

after_script:
  - !reference [.hidden, script]  # before_script and after_script in root of YAML document fail
```
Outputs error:

> normal_job after_script contains non string value

**Expected behavior**
`!reference […]` should work like gitlab CI:

> Executing "step_script" stage of the job script
> Using docker image sha256:7e01a0d0a1dcd9e539f8e9bbd80106d59efbdf97293b3d38f5d7a34501526cdb for alpine with digest alpine@sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a ...
> $ echo Hello from ${CI_JOB_NAME}
> Hello from normal_job
> $ echo Hello from ${CI_JOB_NAME}
> Hello from normal_job
> Running after_script
> Running after script...
> $ echo Hello from ${CI_JOB_NAME}
> Hello from normal_job

**Host information**
macOS 12.6.7 Monterey x86_64 intel CPU.
gitlab-ci-local 4.42.0

**Additional context**
Nesting `after_script:` under `default:` does not make a difference:

```yml
#...
default:
  after_script:
    - !reference [.hidden, script]  # before_script and after_script in root of YAML document fail
```
