### ISSUE TITLE
Job variables not passed to image entrypoint

### ISSUE THREAD

**Issue by okuuva** [firecow/gitlab-ci-local#96]
Might be that I missed something obvious but it seems that job variables aren't exported to Docker executor. The following example works in Gitlab CI but not in gitlab-ci-local:

entrypoint.sh:
```bash
#!/usr/bin/env bash

: "${SPECIAL_VARIABLE?"Requires SPECIAL_VARIABLE"}"

echo "Special variable: $SPECIAL_VARIABLE"
```
Dockerfile:
```Dockerfile
from bash:5

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT /entrypoint.sh
```

.gitlab-ci.yml:
```yaml
job-variable-test:
  image: spikeb/gcl:job-variable-test  # built using the files above
  variables:
    SPECIAL_VARIABLE: "test"
  stage: build
  script:
    - echo "$SPECIAL_VARIABLE"
 ```

Expected output:
```bash
❯ gitlab-ci-local job-variable-test
yml files         processed in 36 ms
job-variable-test starting gcl:variable-expansion (build)
job-variable-test pulling gcl:variable-expansion
job-variable-test pulled in 217 ms
job-variable-test copying to container /builds/
job-variable-test copied in 249 ms
job-variable-test > Special variable: test
job-variable-test finished in 1.25 s
test
successful job-variable-test
```

What I get instead:
```bash
❯ gitlab-ci-local job-variable-test
yml files         processed in 31 ms
job-variable-test starting spikeb/gcl:job-variable-test (build)
job-variable-test pulling spikeb/gcl:job-variable-test
job-variable-test pulled in 415 ms
job-variable-test copying to container /builds/
job-variable-test copied in 274 ms
job-variable-test > /entrypoint.sh: line 3: SPECIAL_VARIABLE: Requires SPECIAL_VARIABLE
job-variable-test finished in 1.6 s exited with code 1

failure job-variable-test
```
