### ISSUE TITLE
[Improvement] Log when Docker is not launched

### ISSUE THREAD

**Issue by sneko** [firecow/gitlab-ci-local#964]
Hi,

That's a fancy feature but it could be great to tell the pipeline is failing due Docker not being launched.

Currently it just says:
```
gitlab-ci-local --file .gitlab/workflows/ci.yml --state-dir .gitlab/.gitlab-ci-local/
parsing and downloads finished in 65 ms
requirements starting sneko/xxx:yyy (requirements)

 FAIL  requirements
pipeline finished in 345 ms
```

Thank you,

**Comment by firecow** [comment]
Can you upgrade to latest gitlab-ci-local and see if this is still the case @sneko. (I'm pretty sure it's already fixed.)

**Comment by sneko** [comment]
@firecow I started to use your library 3 days ago and used the npm setup

**Comment by firecow** [comment]
Hmmm....
What does your .gitlab-ci.yml look like?

**Comment by sneko** [comment]
It's a work in progress but:
```yaml
image: ubuntu:latest

variables:
  PHP_VERSION: '8.2.9'
  NODE_OPTIONS: '--max_old_space_size=4096'
  NODE_VERSION: '16.15.0'
  PNPM_VERSION: '7.27.1'
  PLAYWRIGHT_BROWSERS_CACHE_FOLDER_SUFFIX: '.cache/ms-playwright'

stages:
  - requirements
  - publish-chromatic

before_script:
  - STORE_PATH=$(pnpm store path)

cache:
  - key:
      files:
        - apps/api/composer.lock
    paths:
      - apps/api/var/cache
      - apps/api/vendor
  - key:
      files:
        - pnpm-lock.yaml
    paths:
      - $STORE_PATH
      - apps/app/.next/cache

requirements:
  stage: requirements
  image: sneko/agents-en-intervention-ci-runner:php-$PHP_VERSION-node-$NODE_VERSION-pnpm-$PNPM_VERSION # Please have a look at `.gitlab/workflows/README.md` for details
  script:
    - echo "Install pnpm dependencies with $STORE_PATH set"
    - pnpm install

    - ...
```

**Note it stopped failing just after launching Docker, so I guess this is the origin.**
