### ISSUE TITLE
Can't override image entrypoint

### ISSUE THREAD

**Issue by okuuva** [firecow/gitlab-ci-local#97]
When trying to override image entrypoint gitlab-ci-local crashes with a stack trace.

.gitlab-ci.yml:
```yaml
gcl-test:
  image:
    name: gcr.io/kaniko-project/executor:v1.5.1-debug
    entrypoint: [""]
  stage: test
  script:
    - echo "blah"
```

Expected output:
```shell
yml files            processed in 80 ms
gcl-test             starting gcr.io/kaniko-project/executor:v1.5.1-debug (test)
gcl-test             pulling gcr.io/kaniko-project/executor:v1.5.1-debug
gcl-test             pulled in 230 ms
gcl-test             copying to container /builds/
gcl-test             copied in 307 ms
gcl-test             $ echo "blah"
gcl-test             > blah
gcl-test             finished in 1.48 s
```

I get a stacktrace instead:
```shell
yml files            processed in 110 ms
TypeError: image.includes is not a function
    at Job.get image [as image] (/snapshot/gitlab-ci-local/src/job.ts:116:22)
    at Job.start (/snapshot/gitlab-ci-local/src/job.ts:167:85)
    at Function.runSingleJob (/snapshot/gitlab-ci-local/src/commander.ts:113:13)
    at handler (/snapshot/gitlab-ci-local/src/default-cmd.ts:53:9)
    at Object.handler (/snapshot/gitlab-ci-local/src/default-cmd.ts:65:9)
```

My guess is that there's no handling for hash map version of `image` key so either a bug or enhancement request depending on how you look at it.
