### ISSUE TITLE
CI_DEFAULT_BRANCH is missing

### ISSUE THREAD

**Issue by atli-c** [firecow/gitlab-ci-local#970]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "You have the default branch checked out."
```

**Expected behavior**
Current git branch can be compared to the default branch

**Host information**
macOS
gitlab-ci-local 4.40.0

**Additional context**
A workaround is to set the environment variable `VARIABLE="CI_DEFAULT_BRANCH=master"` in `.gitlab-ci-local-env`.

The default `$CI_DEFAULT_BRANCH` should be "main". Since some projects still use the old "master" (or "trunk"), the value should be easy to change.
