### ISSUE TITLE
error: clone test repo cache[0].paths must be array

### ISSUE THREAD

**Issue by remyleone** [firecow/gitlab-ci-local#979]
**Minimal .gitlab-ci.yml illustrating the issue**

```yml
stages:
- prepare
- fips helper binaries
- prebuild
- prerelease
- test
- coverage
- build
- package
- release
- postrelease
- docs

include:
- local: /.gitlab/ci/_common.gitlab-ci.yml
- local: /.gitlab/ci/_rules.gitlab-ci.yml
- local: /.gitlab/ci/prepare.gitlab-ci.yml
- local: /.gitlab/ci/fips-helper-binaries.gitlab-ci.yml
- local: /.gitlab/ci/prebuild.gitlab-ci.yml
- local: /.gitlab/ci/prerelease.gitlab-ci.yml
- local: /.gitlab/ci/test.gitlab-ci.yml
- local: /.gitlab/ci/coverage.gitlab-ci.yml
- local: /.gitlab/ci/build.gitlab-ci.yml
- local: /.gitlab/ci/package.gitlab-ci.yml
- local: /.gitlab/ci/release.gitlab-ci.yml
- local: /.gitlab/ci/postrelease.gitlab-ci.yml
- local: /.gitlab/ci/docs.gitlab-ci.yml
- project: 'gitlab-org/quality/pipeline-common'
  file:
    - '/ci/danger-review.yml'
  rules:
    - if: '$CI_SERVER_HOST == "gitlab.com"'
```

```
$ gitlab-ci-local   
clone test repo cache[0].paths must be array
```

**Expected behavior**

I expect to have either a help menu or to have an error message that I can understand.

**Host information**
macos

```
$ gitlab-ci-local --version
4.43.0
```

**Containerd binary**

No.

**Additional context**
