### ISSUE TITLE
Cannot use variables from artifacts:reports:dotenv in other job image: field

### ISSUE THREAD

**Issue by atli-c** [firecow/gitlab-ci-local#994]
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
my_docker_image:
  variables:
    ARTIFACT_ENV_FILE: artifact_vars.env
  script:
    - export VAR_NAME="${CI_JOB_NAME_SLUG//-/_}_reference"; VAR_NAME="${VAR_NAME^^}"  # Uppercase
    - export IMAGE_REF="local-test:ci-${CI_PIPELINE_IID}-${CI_JOB_ID}"

    - echo 'FROM alpine' | docker build -t "${IMAGE_REF}" -
    - echo "${VAR_NAME}=${IMAGE_REF}" |tee -a "${ARTIFACT_ENV_FILE}"
  artifacts:
    reports:
      dotenv: ${ARTIFACT_ENV_FILE}

.say_hello:
  script:
    - echo "Hello World -- From MY_DOCKER_IMAGE_REFERENCE='${MY_DOCKER_IMAGE_REFERENCE}'"

say_hello_with_alpine:
  extends: [.say_hello]
  image: alpine

say_hello_with_needy_alpine:
  extends: [.say_hello]
  needs: [my_docker_image]
  image: alpine

say_hello_with_new_image:
  extends: [.say_hello]
  needs: [my_docker_image]
  image: ${MY_DOCKER_IMAGE_REFERENCE}
```

**Expected behavior**
Alle jobs (including 'say_hello_with_new_image') show be run. Like on the 'real' gitlab-ci.

**Host information**
macOS Ventura 13.6
gitlab-ci-local 4.43.0

**Containerd binary**
Are you using docker or podman, or any other relevant containerization tool.
Docker Desktop v4.22.1. `Docker version 24.0.5, build ced0996`, `containerd v1.6.21`.

**Additional context**
`gitlab-ci-local say_hello_with_new_image --needs` fails with:

> say_hello_with_new_image    starting :latest (test)
> say_hello_with_new_image    copied to docker volumes in 477 ms
> Error: Command failed with exit code 1: docker image inspect :latest
> Error response from daemon: invalid reference format
> []
>    at makeError (/usr/local/lib/node_modules/gitlab-ci-local/node_modules/execa/lib/error.js:60:11)
>    at handlePromise (/usr/local/lib/node_modules/gitlab-ci-local/node_modules/execa/index.js:118:26)
>    at processTicksAndRejections (node:internal/process/task_queues:95:5)
>    at Job.pullImage (/usr/local/lib/node_modules/gitlab-ci-local/src/job.ts:760:13)
>    at Job.execScripts (/usr/local/lib/node_modules/gitlab-ci-local/src/job.ts:622:13)
>    at Job.start (/usr/local/lib/node_modules/gitlab-ci-local/src/job.ts:474:36)
>    at /usr/local/lib/node_modules/gitlab-ci-local/node_modules/p-map/index.js:57:22

**Comment by atli-c** [comment]
Add to tests/test-cases/artifacts-reports-dotenv/.gitlab-ci.yml:
```yaml
# Test with image:$dotenv variable
build-image-ref:
  stage: build
  needs: []
  script:
    - echo "BUILD_IMAGE_REF=alpine" > build.env
  artifacts:
    reports: { dotenv: build.env }
use-image-ref:
  stage: deploy
  needs: [build-image-ref]
  image: ${BUILD_IMAGE_REF}
  script:
    - if [ "$BUILD_IMAGE_REF" = "" ]; then exit 1; else cat /etc/os-release; fi
```

add test to tests/test-cases/artifacts-reports-dotenv/integration.artifacts-reports-dotenv.test.ts:  
```ts
test("artifacts-reports-dotenv <use-image-ref> --needs", async () => {
    const writeStreams = new WriteStreamsMock();
    await handler({
        cwd: "tests/test-cases/artifacts-reports-dotenv",
        job: ["use-image-ref"],
        needs: true,
        shellIsolation: false,
    }, writeStreams);

    expect(writeStreams.stderrLines.join("\n")).not.toMatch(/FAIL/);
});
```
